### ISSUE TITLE
Inconsistencies in "gloss_in_source"

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1000]
```bash
$ grep 'GLOSS_IN' *.tsv
Chacon-2017-129.tsv:ID	NUMBER	ENGLISH	SPANISH	CATEGORY	CONCEPTICON_ID	CONCEPTICON_GLOSS	GLOSS_IN_SOURCE
Huber-1992-375.tsv:ID	NUMBER	SPANISH	ENGLISH	CONCEPTICON_ID	CONCEPTICON_GLOSS	GLOSS_IN_DIGITAL_SOURCE
PharaoHansen-2020-100.tsv:ID	NUMBER	SPANISH	ENGLISH	CONCEPTICON_ID	CONCEPTICON_GLOSS	GLOSS_IN_DATA
Zhang-2019-308.tsv:ID	NUMBER	GLOSS	GLOSS_IN_SOURCE	CONCEPTICON_ID	CONCEPTICON_GLOSS	REMARK
```

We need to make sure to have this done more consistently, I think, but I am not entirely sure. In Huber, the gloss is clearly in the digital source, while in the other cases, this is not entirely sure (yet PharaoHansen is similar).

**Comment by LinguList** [comment]
IN any case, documenting this somewhere (maybe in lexibank) would be useful?

**Comment by LinguList** [comment]
To remind of the use-case: often, the digital source is different from the concept list in the paper, which makes comparison difficult, so we now tend to say that we keep both, but keep the digital source in an extra column, at times even comma-separated, since there may be more than one "digital_gloss".

**Comment by chrzyki** [comment]
See also the discussion here: https://github.com/lexibank/pylexibank/issues/222. I can prepare text for `lexibank`.

**Comment by LinguList** [comment]
very good! Maybe, we could even use a technical term, like "lexibank"? I
mean, we use this mainly for integration with lexibank, right?

**Comment by chrzyki** [comment]
Yes, I like that. Makes it clear that this is something required by Lexibank only (as far as I can tell).

**Comment by chrzyki** [comment]
See https://github.com/lexibank/lexibank/pull/238. I'll open a separate issue for refining the lists.
