### ISSUE TITLE
ITCH 148 declared as n. but lists a number of verbal concepts

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#1018]
There are currently quite a number of lists mapped to this concept set. If we decide to split it into substantive and verbal 'itch' concept sets, all of the lists have to be examined thoroughly to determine what specific meaning of 'itch' they refer to.

**Comment by Kristina-Pianykh** [comment]
I would suggest adding the concept ITCH (CAUSE ITCHING) for verbal concepts that are currently mapped to ITCH (`Person/Thing`) (and?) ITCHY (`Property`). There is quite a number of Chinese 痒 currently mapped to ITCHY that have several English verbal translations and should not be moved, I assume. Since there are also some verb-like concepts in English (to itch/to be itchy/feel itchy (v)) and German ('Es juckt mich.'), I am not sure if ITCHY was initially meant to cover both property and action concepts and thus should not be thought of in terms of a word category, roughly speaking. This brings me to the question if there is a need to split ITCHY and move some of the unambiguous action-concepts to ITCH (CAUSE ITCHING).

Could I ask you, @LinguList, @CarolinHu, @AnnikaTjuka, @Schweikhard, to have a brief look at the concepts and share your opinion?

**Comment by LinguList** [comment]
Yes, it seems useful to remap the concepts. The Chinese case is tricky, as it is definitely a noun, but can also function as verb. So I'd follow English glosses in identifying the mapping here.

**Comment by AnnikaTjuka** [comment]
So we would have the following mappings:

CONCEPTION_GLOSS | Mapping
--|--
ITCH (Person/Thing) | the itch
ITCHY (Property) | itchy
ITCH (CAUSE ITCHING) (Action/Process) | to itch, to be itchy, feel itchy (v), 'Es juckt mich.'

There are plenty of glosses with only "itch". It might be useful if you list them here so that we can decide whether the lists need to be remapped before you open a PR.

**Comment by Kristina-Pianykh** [comment]
Here is the table of all the lists with the ambiguous reference to 'itch':
| List      | ID           | GLOSS|Comments
| ------------- |:-------------:| -----|-------|
| Bodt-2019-664 |Bodt-2019-664-254| itch| I checked the publication and couldn't find where the data come from
|Bowern-2011-204|Bowern-2011-204-89|itch|It is said to be based on Swadesh except for the concepts marked with *. his gloss should probably be marked, too. Based on the gloss 'itch (to) in Bowern-2012-644-279, I would map all ambiguous 'itch' glosses in Bowern's lists to ITCH (CAUSE ITCHING) (Action/Process).
Bowern-2012-189|Bowern-2012-189-81|itch*|same as above
Bowern-2012-205|Bowern-2012-205-89|itch*|same as above
Bowern-2017-348|Bowern-2017-348-170|itch|same as above
Mann-1998-406|Mann-1998-406-266|itch|The list's description says it's originally based on the SIL list? similar to [this one](https://concepticon.clld.org/contributions/SIL-2002-436). There 'itch' is verbal
Nagano-2013-1256|Nagano-2013-1256-362|feel itchy (v)
TeilDautrey-2008-430|TeilDautrey-2008-430-211|itch|On the [website ](https://abvd.shh.mpg.de/bantu/word.php?v=211)where the data were taken from the gloss has the French equivalent 'démanger', which is a verb.

The rest of the 'itch' glosses are more clear. In the case of the Chinese concepts, I'll follow the English translation then.

**Comment by LinguList** [comment]
I'd leave Bodt's list for the time being as is. For the list of 
Teil-Dautrey, I think we should make a separate issue and add the French 
terms, as they are useful for our mapping algorithm.

Otherwise, I support the suggestions.

**Comment by AnnikaTjuka** [comment]
Looks good, thanks @Kristina-Pianykh !
