### ISSUE TITLE
Columns in Chacon-2017-129 are incorrectly labeled

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#1020]
Columns in [Chacon-2017-129](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Chacon-2017-129.tsv) are incorrectly labeled, the `ENGLISH` column contains the spanish (or portuguese?) glosses, `SPANISH` the english ones.

> Thanks to @fmatter for bringing this to our attention.

**Comment by chrzyki** [comment]
See #1021.
