### ISSUE TITLE
Concept Net Resource as Metadata?

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#103]
- http://conceptnet5.media.mit.edu/

I still did not fully check the integration of this dataset, but it might be interesting to some degree at least to be added as concepticon metadata.

**Comment by AnnikaTjuka** [comment]
This looks really cool. I checked out the GitHub page (https://github.com/commonsense/conceptnet) but couldn't figure out how to add this to norare.

**Comment by LinguList** [comment]
@AnnikaTjuka, I think this will need some "crawling", that is: a script that repeatedly iterates over a website to search for data. This is not that difficult for me to write, but it always costs some time to fiddle around with things, which is why it is not my favorite enterprise. But we may want to look into some of these cases anyway. So you could transfer this issue to norare-data, and add a tag "crawling".

**Comment by LinguList** [comment]
BTW, maybe crawling not needed, it is also on github: https://github.com/commonsense/conceptnet5

**Comment by LinguList** [comment]
Perfect, they have a Python [API](https://github.com/commonsense/conceptnet5/wiki/API).

**Comment by AnnikaTjuka** [comment]
Great! I'm not able to transfer issues from concepticon-data to norare-data. But I can open a new issue in norare-data and refer to this one.

**Comment by LinguList** [comment]
That's what I meant ;)

**Comment by AnnikaTjuka** [comment]
I know, but I do not have admin rights in concepticon-data ;) That's why I'm not able to transfer issues.

**Comment by LinguList** [comment]
I didn't even know it is possible to transfer, that's what I meant.

**Comment by AnnikaTjuka** [comment]
Ah ok. Are you able to transfer the issue? 
<img width="360" alt="Screenshot 2020-06-15 at 10 34 56" src="https://user-images.githubusercontent.com/45693807/84635714-e164ff80-aef3-11ea-8ca8-b20e41aad0f0.png">

**Comment by AnnikaTjuka** [comment]
Just out of curiosity. Because it worked when I transferred issues from the old norare repository to norare-data.

**Comment by LinguList** [comment]
I have admin rights, so I should be able to do it, I assume, but I have
never tried...

**Comment by AnnikaTjuka** [comment]
I like this feature because it saves the copy and paste. But I have already set up a new issue in norare-data so I'll close this issue here.
