### ISSUE TITLE
Blomberg-2020-160: Swedish stimuli for study on N400

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1031]
This is a very interesting study, looking at semantic associations and arousal, providing a short norm dataset: https://www.jbe-platform.com/content/journals/10.1075/ml.19021.blo#abstract_content

The main values are three:

1. nice example for small wordlist data where NoRaRe would have offered more items to compare with
2. the importance of semantic associations for N400 calls for testing their results against CLICS data
3. the authors do not by any means distinguish words from concepts: they talk about words, but what they seem to want to investigate are concepts, since concepts are evoked by words (at least one would speculate that)

The third point may be important for the arguments we face when discussing word/concepts: if authors assign a unique value for emotion arousal to a word, they treat it as a single unit that does not have different meanings, similar to the idea of "concrete word". A meaning/sense/concept is concrete, not a word. But this can be a key argument to justify why we allow for a certain interchangeability of word/meaning/sense/concept in concepticon.

**Comment by LinguList** [comment]
To convert the data form PDF, I recommend pdf2doc.com, it seems the tables can then be easily digitized.

**Comment by wlevene** [comment]
pdf2document.com - No loss of pdf layout
30 free page conversions daily for all users.
