### ISSUE TITLE
gerarditupi concept list now available

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1044]
The concept list was just published in Diachronica: https://benjamins.com/catalog/dia.18032.fer

**Comment by LinguList** [comment]
This relates to the original lexibannk dataset, which was already published, but without making use of a specific concepticon version: https://github.com/lexibank/gerarditupi

So concepts are mapped, we just need to add them to concepticon now.

**Comment by Kristina-Pianykh** [comment]
I can add the list but I currently don't have the source. It would very much appreciate it if someone who has one could send it to me.

**Comment by LinguList** [comment]
Just sent you the paper via email. Since it is still published before 
appearing in a real volume, page numbers will change later, as well as 
the number info (but the volume is 38 (for 2021).
