### ISSUE TITLE
Majid-2015-XX Body Part Terms

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1046]
The study (doi: 10.1111/tops.12159) uses a specific technique to elicit body part terms but collects them in a way that it should be in part mappable to concepticon.

The following image shows the questionnaire (as far as I understand):

![Majid2015](https://user-images.githubusercontent.com/2916210/107147844-84213100-6950-11eb-8db9-19ae7eec46b3.png)

**Comment by AnnikaTjuka** [comment]
I'm not sure if we can map this study to Concepticon. They use a coloring task. So participants get a picture and color the part that is supposed to be the body part. For some body parts, there is quite a bit of variation between speakers. To authentically depict the task of the study, we would need to map the images, not the words.

**Comment by AnnikaTjuka** [comment]
The results for individual participants look like this:
<img width="485" alt="Screenshot 2021-02-07 at 15 00 46" src="https://user-images.githubusercontent.com/45693807/107148780-5d192e00-6955-11eb-8fd9-25859424eb0e.png">

**Comment by LinguList** [comment]
I think we can map this, since van Staden and Majid (2006) clearly say 
that they start from a list of body part concepts and then ask the 
participants to color them. So they have a concept / word that they use 
and then have participants color. Without a reference point, one would 
not be able to point them to a lexeme anyway.

**Comment by AnnikaTjuka** [comment]
True, but the task is designed to show that a word can mean different things to different participants. I think the special issue by Enfield et al. (2006) wanted to make this point. Before their coloring task, studies about cross-linguistic nomenclature of body part terms were done by comparing dictionaries or lists (e.g., Brown 1976; Andersen 1978). The studies in Enfield et al. (2006) showed nicely that there are interesting variations in nomenclature that do not match the translation equivalent of the body part term.

**Comment by AnnikaTjuka** [comment]
If we map the list, I'd like to suggest that we add a PDF with figures 2-8 in Majid & van Staden (2015). This would illustrate the task and the variation.

**Comment by LinguList** [comment]
I don't think the pdf needs to be added, but that this could just be 
added to the NOTE in the conceptlists.tsv, where it would point readers 
to the article. What is interesting with respect to the whole debate 
about where a body part ends and where it starts in a language is that 
there are also quite clear hypotheses that certain parts are always 
expressed in some way (as you can see from Enfields elicitation guide in 
the SI from 2006). Unfortunately, those are shared in prose, but it 
might also be interesting to share these, as they reflect some kind of a 
hypothesis.

And btw: what we can also see in the list I shared is that the authors 
try to somehow elicit in words how certain mergers could be 
characterized, so listing "arm/hand" along with "arm" and "hand" is also 
a worthwhile enterprise for documentation.

**Comment by AnnikaTjuka** [comment]
Yes, Brown (1976) and Andersen (1978) established principles for body part naming patterns (supposedly universals based on samples of 71 or 81 languages, respectively) some of which Enfield et al. investigated empirically. However, for example, the claim that every language has a word for _head_ and _body_, did not hold in all of the languages for which they conducted the coloring task.

**Comment by LinguList** [comment]
My opinion on these studies is very pragmatic: every study would 
probably need a starting point (either use an elicitation gloss or 
pre-color a body and then ask people to name the part). If elicitation 
glosses of this form are mentioned in some study, Concepticon is the 
right place to store it, since it allows users later on to check, e.g., 
if a study discusses a body part, such as the "arm". So even if it 
doesn't matches the clear intentions or what you find inside this very 
interesting study by Majid and van Staden, it is a first hint, and even 
if it's not what some people might expect, they will find information on 
the lexification of "arm" in this study, right?

**Comment by AnnikaTjuka** [comment]
Ah ok, if this is the intention then the list can be mapped without hesitation. I was a bit cautious because it isn't a "classic" elicitation study and for me, the main results are the pictures.
