### ISSUE TITLE
New concept CUT OR HACK

### ISSUE THREAD

**Issue by CarolinHu** [concepticon/concepticon-data#1052]
Thank you @AnnikaTjuka for pointing this out.

There are a number of lists that combine "cut" and "hack" in their glosses in some way (Blust 1981 and 2008, the Bowern lists, Lee 2011 and 2015), so a new concept encompassing both meanings might be necessary. Currently, most "cut/hacks" are mapped to CUT.

**Comment by LinguList** [comment]
Specifying this is surely useful!
