### ISSUE TITLE
Automated check for new concepts

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1055]
What I also realized is: we have many concepts now that occur in five or more lists but have no concepticon concept sets. I marked some sporadically (!CONCEPT) in the data, but I think we should in the future have some automated check to do this once in a while and add more concept sets. Maybe we should put this into an issue to discuss the procedure?

_Originally posted by @LinguList in https://github.com/concepticon/concepticon-data/issues/1054#issuecomment-779745993_

**Comment by chrzyki** [comment]
This has been added to the contributing guidelines and the GitHub workflow template (`notlinked`).
