### ISSUE TITLE
MEET and ENCOUNTER (MEET)

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#1077]
It has been suggested that we add the concept set ENCOUNTER (MEET), a hyponym of MEET, to imply unintentionality of meeting someone/something. There are currently two lists with the gloss 'encounter':

1. Lewis-2016-499-439
2. Lundgren-2020-275-91

None of the sources indicate explicitly whether they mean 'an encounter' or 'to encounter'. Lewis takes his data from the [MRC Psycholinguistic Database](https://websites.psychology.uwa.edu.au/school/mrcdatabase/uwa_mrc.htm), which apparently contains both instances. Due to the ambiguity of the concept here I'd suggest leaving it unmapped for the time being.

Ludgren, similarly, doesn't disambiguate the meaning but I found the [following grammar](http://etnolinguistica.wdfiles.com/local--files/tese%3Ao-hagan-2011/o-hagan_2011_proto-omagua-kokama.pdf), which specifies the use of 'encounter' in Omagua, one of the target languages in Ludgren. The word 'sawiti' in Omagua here means 'to find' and it's always verbal. So I think it would be safe to map it to the new ENCOUNTER (MEET).

**Comment by AnnikaTjuka** [comment]
Thanks, @Kristina-Pianykh!

So lists that could be mapped to ENCOUNTER (MEET):
- [ ] https://concepticon.clld.org/values/Lundgren-2020-275-91
- [ ] https://concepticon.clld.org/values/Dellert-2017-1016-919
- [ ] https://concepticon.clld.org/values/Borin-2015-1532-772
- [ ] https://concepticon.clld.org/values/Haspelmath-2009-1460-1223
- [ ] https://concepticon.clld.org/values/Key-2016-1310-1221 (??)
- [ ] https://concepticon.clld.org/values/Kingsada-1999-303-203
- [ ] https://concepticon.clld.org/values/Snider-2004-1700-414
- [ ] https://concepticon.clld.org/values/Steinthal-1875-1549-1086

I'm not sure about the Chinese glosses: 遇见 @MacyL Could you help?

**Comment by Schweikhard** [comment]
> Ludgren, similarly, doesn't disambiguate the meaning but I found the following grammar, which specifies the use of 'encounter' in Omagua, one of the target languages in Ludgren. The word 'sawiti' in Omagua here means 'to find' and it's always verbal. So I think it would be safe to map it to the new ENCOUNTER (MEET).

Lundgren's encounter is very likely the noun, as verbs are marked as transitive or intransitive in that list:https://concepticon.clld.org/contributions/Lundgren-2020-275 So it is strange that they nevertheless map a verb to it. Perhaps a misunderstanding on the side of the person who mapped that Omagua data?

I agree that Lewis is ambiguous, and I would argue to leave both Lewis and Lundgren unmapped.

@AnnikaTjuka Thanks for putting together that list! But as I wrote beneath the PR, Kingsada, Haspelmath and Borin make it clear that they mean *not* ENCOUNTER (MEET) but *MEET WITH.

**Comment by AnnikaTjuka** [comment]
Ah yes, I updated the list (also deleted Lundgren). You can check the box if one of the lists should be mapped to ENCOUNTER (MEET).

**Comment by Schweikhard** [comment]
I'm sure about Steinthal as it uses a German gloss, but the other 3 might be a bit too ambiguous.

Oh, and Gabelentz 1892 1074 should also be mapped to ENCOUNTER (MEET) for the same reason.

**Comment by Kristina-Pianykh** [comment]
I don't know who left notes against some concepts in the list of Dellert-2017-1016 but the note for Dellert-2017-1016-919 specifically says that the concept should not be linked to MEET. I see no reason why not as it seems general enough and there is no other concept to make a distinction. So I'd leave it the way it is.

In case with Key-2016-1310-1221, since it underlies the Intercontinental Dictionary Series and is used to map multiple languages (https://ids.clld.org/parameters/19-650#2/14.4/149.7), I'd suggest this concept be understood very generally.

I'm also inclined to leave the mapping in Snider's list unchanged, too. There seems to be nothing to indicate that the concept implies unintentional encountering. And in case of uncertainty or the lack of any further details, I'd give preference to a more general concept set.
