### ISSUE TITLE
Duplicate FOOT (UNIT) and 2782 FOOT (MEASURE) 

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1094]
I'm guessing that these two concepts are duplicates:

2688	FOOT (UNIT)	Basic actions and technology	A unit of length.	Person/Thing	
2782	FOOT (MEASURE)	Quantity	A measure unit.	Person/Thing	

Zero concepts are mapped to FOOT (UNIT). Since it is the "older" concept, I'd map all lists from 2782 to 2688 and update the semantic field for 2688 and the REPLACEMENT column for 2782.

**Comment by LinguList** [comment]
Yes, sounds reasonable!
