### ISSUE TITLE
PEANUT vs. GROUNDNUTS

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#1098]
Synonyms or different plants/species? (A note to myself).

**Comment by Kristina-Pianykh** [comment]
According to encycplediae, these terms refer to one and the same species of Arachis hypogaea (aka peanut). The difference (if any implied) could be in the reference to the plant before harvesting (groundnut) or after (peanut). But judging by the 'groundut' glosses currently in concepticon, it does not look like this subtle difference was implied in any of the lists. The question is now what to retire.

| CONCEPTICON_ID       | CONCEPTICON_GLOSS          | Definition |
| ------------- |-------------| -----|
| 595    | GROUNDNUTS | A nutlike fruit from the plant Arachis hypogaea that grows on long stems under ground.|
| 2364      | PEANUT     |   A species in the family Fabaceae (commonly known as the bean, pea or legume family). |

I personally find PEANUT more intuitive but it's also older.

**Comment by AnnikaTjuka** [comment]
We had a similar case with THIGH versus UPPER LEG and landed on the "retire-younger" strategy. I'd suggest that we retire 2364 PEANUT and refine 595 GROUNDNUTS (PEANUTS) so that it is clear what is meant.
