### ISSUE TITLE
Concepticon 2.5 release

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1101]
Dear concepticon editors, @Schweikhard, @AnnikaTjuka, @Kristina-Pianykh, and @chrzyki (as the ones who regularly contributed in our workflow since version 2.4), as @xrotwang will work on the release for 2.5 in CLLD, we should quickly check which issues we can solve within this week, and assign them to ourselves, and also assign them to a milestone. So if you all could look into the open issues and also generously close those which seem less important or which have been fixed, this would be very great. Then, add the milestone 2.5 to the issues you consider important, and we try to fix them this week.

**Comment by Kristina-Pianykh** [comment]
Sounds great, there are quite a few issues I've recently opened and I'll prepare an update regarding these small fixes today/tomorrow.

**Comment by LinguList** [comment]
Perfect, many thanks in advance!

**Comment by AnnikaTjuka** [comment]
Sound good. I'm working on a list right now for which I'll prepare a PR tomorrow.

**Comment by xrotwang** [comment]
What do we do about
```
/home/robert_forkel/projects/concepticon/pyconcepticon/src/pyconcepticon/api.py:307: Warning: WARNING:conceptlists.tsv: no PDF found for Huttenlocher1979
```

**Comment by chrzyki** [comment]
I'll upload the PDF tonight or tomorrow at the latest.

**Comment by AnnikaTjuka** [comment]
We are currently at concept lists number 385. When the two open PRs are merged, we'll reach 387. Are we aiming for a round number of 390 lists?

**Comment by xrotwang** [comment]
NO!

**Comment by xrotwang** [comment]
At some point @LinguList must get over his phase of number mysticism.

**Comment by LinguList** [comment]
This list is important for lexibank.

**Comment by LinguList** [comment]
Compromise is by nature an even number so so this seems fair enough :)

**Comment by chrzyki** [comment]
I'll prepare the list tomorrow morning (should be quick since @LinguList already did a lot of work for this list).

**Comment by chrzyki** [comment]
> 
> 
> But one more is coming with ratcliffe, so we will have an even number!

Hm, Ratcliffe already appears to be in Concepticon: 

- https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Ratcliffe-2020-100.tsv
- https://github.com/concepticon/concepticon-data/commits/master/concepticondata/conceptlists/Ratcliffe-2020-100.tsv

This is basically the list for the Lexibank dataset except for the `LEXIBANK_GLOSS`, correct?

**Comment by SimonGreenhill** [comment]
There are a few errors in `concepticon test`: 

```
ERROR:Scherer-2013-20: '<' not supported between instances of 'int' and 'str'
ERROR:Jonauskaite-2020-12: '<' not supported between instances of 'int' and 'str'
ERROR:Goddard-2002-59: '<' not supported between instances of 'int' and 'str'
ERROR:Goz-2017-600: '<' not supported between instances of 'int' and 'str'
ERROR:Feleke-2021-150: '<' not supported between instances of 'int' and 'str'
```

**Comment by chrzyki** [comment]
Hm, culprit seems to be the quoted `NUMBER` minimum in the metadata: https://github.com/concepticon/concepticon-data/blob/558d4a6c50ac20cf43cd754e45734b98d46af5f7/concepticondata/conceptlists/Scherer-2013-20.tsv-metadata.json#L32-L35

Weird that I don't see that locally (and GitHub CI also doesn't seem to mind)? Will investigate, thanks!

**Comment by SimonGreenhill** [comment]
Could it be a py version issue? I think the venv I’m using is 3.6?

**Comment by chrzyki** [comment]
> 
> Could it be a py version issue? I think the venv I’m using is 3.6?
> […](#)
> On 3/06/2021, at 17:47, Christoph Rzymski ***@***.***> wrote: ﻿ Hm, culprit seems to be the quoted NUMBER minimum in the metadata: https://github.com/concepticon/concepticon-data/blob/558d4a6c50ac20cf43cd754e45734b98d46af5f7/concepticondata/conceptlists/Scherer-2013-20.tsv-metadata.json#L32-L35 Weird that I don't see that locally (and GitHub CI also doesn't seem to mind)? Will investigate, thanks! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Can you check the version of `csvw` in your local environment?

**Comment by xrotwang** [comment]
@SimonGreenhill 
```
pip install -U csvw
```
should fix this. See https://github.com/cldf/csvw/commit/e55978be5f13fc66bc81208f85899964094577a6

**Comment by SimonGreenhill** [comment]
that's it:
```shell
INFO    all integrity tests passed: OK
```

**Comment by SimonGreenhill** [comment]
oops, sorry for the close.

**Comment by LinguList** [comment]
From my side, the data is now ready for release. I already modified the `.zenodo.json`.

**Comment by LinguList** [comment]
The light-weight app is already online: https://digling.org/calc/concepticon/

**Comment by LinguList** [comment]
I'll update the linkdata one more time, as there was an ugly mistake linking "but" to "buy".

**Comment by LinguList** [comment]
This is done now.
