### ISSUE TITLE
2.5 editorial board and release instructions

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1102]
With [pysem](https://github.com/lingpy/pysem), we have a package that takes concepticon data from the most recent release, so it should be updated to the next version when 2.5 is released. 

For the editorial board, we include this time all active members from 2.4 to 2.5, which would be @AnnikaTjuka, @Kristina-Pianykh, @chrzyki, @xrotwang, and myself (I'd take the order from last time). If you think anybody else should be included let me know.

**Comment by LinguList** [comment]
Ah, @carolinhu has been contributing after 2.4, and @SimonGreenhill is 
our lexibanker and something like a senior editor, so we can leave them 
on board. Mei-Shin and Tiago would leave the group of editors, as their 
last involvement was for version 2.4. Is that okay?

**Comment by xrotwang** [comment]
As a senior editor myself, I welcome this proposal :)

**Comment by chrzyki** [comment]
> 
> Ah, @CarolinHu has been contributing after 2.4, and @SimonGreenhill is our lexibanker and something like a senior editor, so we can leave them on board. Mei-Shin and Tiago would leave the group of editors, as their last involvement was for version 2.4. Is that okay?

Sounds good!
