### ISSUE TITLE
Goddard-2001-1?? list of semantic primes

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#111]
It would generally be good to have some official version of the NSM primes which are potentially yet another category which we are missing or should provide. Goddard compares these with Swadesh terms in page 9 table 3 of the source. While we have table 1 of Goddard-2001, we lack this one.

**Comment by LinguList** [comment]
Apparently, there are quite a few translations of the primes into different languages. We should definitely include these (although its a pity, most of the translations are in word-format):

* https://www.griffith.edu.au/humanities-languages/school-humanities-languages-social-science/research/natural-semantic-metalanguage-homepage/resources

**Comment by AnnikaTjuka** [comment]
This list was already added: [Goddard-2001-42](https://concepticon.clld.org/contributions/Goddard-2001-42)
