### ISSUE TITLE
Check Lexibank datasets that might depend on lists in Concepticon 2.5

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#1114]

**Comment by chrzyki** [comment]
- https://github.com/digling/chingelong/
- https://github.com/lexibank/johanssonsoundsymbolic (list is ready, Lexibank repo is still private)
- https://github.com/digling/servamalagasy

**Comment by LinguList** [comment]
Servamalagasy was added by me two weeks ago or so. Chingelong as well.

**Comment by LinguList** [comment]
The Johanssonlist also, but we can make the soundsymbolic data now unprivate (as some other leixbank datasets on our list, I suppose).

**Comment by chrzyki** [comment]
Ah, perfect, that means just updating the datasets themselves. Thanks!

**Comment by LinguList** [comment]
Yes: Chin-2015-100.tsv and Serva-2020-207.tsv
