### ISSUE TITLE
Concept List by Epps (2021) 

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1129]
I have created a first concept list in a [lexibank repo here](https://github.com/lexibank/eppsnorthgermanic). The concept list gives some 800 word forms for Swedish and Norwegian with frequency information and information on animacy, mass noun, etc., for the terms. So this may also be interesting for NoRaRe.

**Comment by LinguList** [comment]
[concepts.tsv.zip](https://github.com/concepticon/concepticon-data/files/7070336/concepts.tsv.zip)

**Comment by LinguList** [comment]
This concept list may need to be double checked, also with the original data (I have tried hard to render it correctly).

**Comment by marthuis** [comment]
For convenience, here's the relevant repo for this issue: https://github.com/gerdcarling/gendernorthscandinavian !

**Comment by marthuis** [comment]
@LinguList I have this data ready, I'll open the PR as soon as I finish reviewing the mappings!

**Comment by LinguList** [comment]
You mean, you have the conceptlist from our lexibank repository and have it mapped?

**Comment by LinguList** [comment]
That would be nice then!

**Comment by marthuis** [comment]
@LinguList I've extracted, formatted and mapped all the data from Gerd Carling's repo! Hopefully there are no discrepancies relative to the Lexibank repo (I don't have access to it)?

**Comment by LinguList** [comment]
@marthuis, if you used the concept list which I linked above (on top of the issue), this is exactly the work that I have done before. Or have you extracted the data again, independently (which would be unfortunate, as this would be unnecessary extra work)?

**Comment by LinguList** [comment]
To be more concrete, I talk about [concepts.tsv.zip](https://github.com/concepticon/concepticon-data/files/7070336/concepts.tsv.zip)

**Comment by LinguList** [comment]
But now, you also have access to the lexibank repo (which however, is identical with the concepts here).

**Comment by marthuis** [comment]
@LinguList Yes indeed, I had your file with me already! I just quickly extracted the entire dataset from Appendix A, just in case it was useful to have that version handy too (with all cognates, etc.). It didn't take extra time, so no losses there :). Now I see such a file was already in the Lexibank repo, but no problem. Should I submit the PR with the 'extended' version or the shortened one here?

**Comment by marthuis** [comment]
@LinguList This is my raw file, just for reference: 
[Epps-2021-1129.zip](https://github.com/concepticon/concepticon-data/files/8246000/Epps-2021-1129.zip)

**Comment by LinguList** [comment]
The shortened version is not a shortened version, but a more correct representation of the whole concept list. If you check closely, you see that I render the repeating concepts in the data by putting repeating concept glosses (labelled X 1, X 2, X 3) in an extra column. So in the end, the concept list is the same, information-wise, as the long one, but it is easier to map, since redundancy has been removed. So when adding, it should be the one that I prepared above, not the long one, which has redundancy which I deliberately resolved in the lexibank repository.

**Comment by marthuis** [comment]
@LinguList Just a heads up that I'm finishing the new concept definitions for this list, which are many. I got a bit of delay the past week, but I should be done quickly!

**Comment by LinguList** [comment]
Thanks for letting me know! I think, if there are many empty concepts, it is not really needed to define them all, you can leave them unmapped first, and we decide if it's worth adding them. Otherwise, we end up with very idiosyncratic concepts in concepticon and may even add duplicates.
