### ISSUE TITLE
Sidwell-2021-116: Concept list for Vietic Languages

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1131]
[concepts.tsv.zip](https://github.com/concepticon/concepticon-data/files/7072607/concepts.tsv.zip)

The list has been linked by me. 

```bibtex
@book{Sidwell2021,
  author       = {Sidwell, Paul and
                  Alves, Mark},
  title        = {Vietic 116 item phylogenetic lexicon},
  year         = {2021},
  note         = {The dataset was created for a paper provisionally 
                   entitled "The Vietic Languages: A Phylogenetic
                   Analysis". The paper is submitted for journal
                   publication and a version submitted for
                   presentation at ICAAL9, November 2021.},
  publisher    = {Zenodo}, address = {Geneva}, 
  version      = {1.0},
  doi          = {10.5281/zenodo.5263195},
}
```

**Comment by LinguList** [comment]
The linked list is also on lexibank: https://github.com/lexibank/sidwellvietic

**Comment by mathildavz** [comment]
Thank you for mapping this list, @LinguList! Have you already checked the mappings manually or should I go through them again?

**Comment by LinguList** [comment]
If you double-check them, it would be nice. I assume the list is rather uncontroversial, but good to have a second or third eye on it.

**Comment by mathildavz** [comment]
As far as I can see, this list was already added to Concepticon. At least, there is a file that seems to be identical already in the conceptlists directory.

**Comment by AnnikaTjuka** [comment]
Thanks, @mathildavz. Since the list is already included in Concepticon, I'll close the issue.
