### ISSUE TITLE
Daniel-2021-XXX: Languages from Daghestan

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1134]
compare our issue in https://github.com/lexibank/daniellinguafrancas/issues/15

**Comment by LinguList** [comment]
Github notifications are somehow not reaching my email. Can you let me know, once you started the pull request so I can watch and help, @ilchec?

**Comment by ilchec** [comment]
> @ilchec, please see also my commen to the PR, as you give page ranges for the full article, although the concept list is NOT in there. So could I ask you to modify this?

I am not sure I understand what you mean, I thought the idea is to quote the paper when someone's using the list. Wasn't it? The list is at page 555, so should I just update the page?

**Comment by LinguList** [comment]
No, it is to quote WHERE the list can be found.

**Comment by LinguList** [comment]
A screenshot converted to PDF is also fine.

**Comment by LinguList** [comment]
It should be called `Daniel2021`, and you need to add the `Daniel2021` to the conceptlists.tsv as well in the PDF field.
