### ISSUE TITLE
Swadesh-1961-XXX in Spanish

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1136]
From Evgenia Korovina (to be acknowledged for this):

> This is a Swadesh list in Spanish that Swadesh himself used for the compilation of his Mexican word lists - I've send you variant as it is in his article about Mayan languages (but as seems the same list was used in his Uto-Aztecan (1963) classification https://www.revistas.inah.gob.mx/index.php/anales/article/view/7232 - and maybe two separate lists don't need for this case)
https://www.revistas.inah.gob.mx/index.php/anales/article/view/7261

**Comment by LinguList** [comment]
[Swadesh-1961.txt](https://github.com/concepticon/concepticon-data/files/7271064/Swadesh-1961.txt)

Evgeniya even linked the list to concepticon already.

**Comment by mathildavz** [comment]
@LinguList Is this the same list as in issue #341? The link in the named issue doesn't work for me anymore, so it's difficult to check.

**Comment by LinguList** [comment]
Yes, I think this is likely. We need to find the original tests to verify. If we don't find them (using library services if needed), we'd better say we leave this issue for now.

**Comment by LinguList** [comment]
Starting point to investigate is: https://revistas.inah.gob.mx/ and here, you'd have to find Swadesh's original text. If you found it, can you send it to me via PDF? And if you don't find it, let me know and if it is paywalled (you have to pay for it), please write an email to ask the librarians to help to buy it.

**Comment by mathildavz** [comment]
@LinguList I've looked through the website and the INAH PDF linked there, but I was only able to find the edition of 1977, which quotes, but does not contain Swadesh's original text, as far as I can see. I've also searched the library catalogue and google scholar, but wasn't able to find this. Should I write an email to the library services and see if they can help?

**Comment by LinguList** [comment]
I just googled "Interrelaciones de las Lenguas Mayas swadesh" and found [this link](https://revistas.inah.gob.mx/index.php/anales/article/view/7261). The PDF link still works, and it seems to be the real paper. Concepts are spread across some 20 pages, as they are in tables and provided as header.

**Comment by mathildavz** [comment]
Thank you for your support, @LinguList! It seems the two lists are identical then. Since Evgenia already linked the list, I will continue with adding the additional files and creating a PR to add this to Concepticon.

**Comment by mathildavz** [comment]
> From Evgenia Korovina (to be acknowledged for this):
> 
> > This is a Swadesh list in Spanish that Swadesh himself used for the compilation of his Mexican word lists - I've send you variant as it is in his article about Mayan languages (but as seems the same list was used in his Uto-Aztecan (1963) classification https://www.revistas.inah.gob.mx/index.php/anales/article/view/7232 - and maybe two separate lists don't need for this case)
> > https://www.revistas.inah.gob.mx/index.php/anales/article/view/7261

How should we acknowledge her? @LinguList

**Comment by LinguList** [comment]
There is a category for people who have pointed us to new concept lists. That is the category we need here (see the abbreviations in the `CONTRIBUTORS.md` file or the `CONTRIBUTIONS.md` file (don't know right now, which file it is).

**Comment by LinguList** [comment]
A, sorry, if she linked the list, there may be one more category for the ackonwledgement you can check, but they are all described in the MD file.
