### ISSUE TITLE
Core Vocabulary List with Frequencies

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1152]
https://github.com/wswu/corevoc

The study is by Wu et al. (2020) and quite interesting: https://aclanthology.org/2020.lrec-1.519.pdf

Somehow, they know about concepticon but do not use the resource at all and rather type off their own version of Dolgopolsky, which does not really follow the original, etc.

**Comment by LinguList** [comment]
But their 3000 item list is compared against frequency counts from the Bible and other corpora, which I find interesting.

**Comment by martino-vic** [comment]
oh and they even went for "Dogolpolsky" instead of "Dolgopolsky", which must have been copied from the [typo in Panphon](https://github.com/dmort27/panphon/issues/28) which is partly fixed now. It's almost a sound change by now.

**Comment by LinguList** [comment]
Hehe, nice spot.

**Comment by AnnikaTjuka** [comment]
Just saw that we have already added the data in NoRaRe in 2020: https://github.com/concepticon/norare-data/pull/77
