### ISSUE TITLE
Simko-2020-212: Extended Swadesh List with Modern Bulgarian Entries

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1156]
This study from 2020 was published here: https://library.oapen.org/bitstream/handle/20.500.12657/52146/9783631806043.pdf?sequence=1#page=231

It is interesting, since the authors mention another list by Mel'nyčuk from 1966.

**Comment by LinguList** [comment]
But this reference is missing. The data is also not shared.

**Comment by LinguList** [comment]
As it has modern Bulgarian entries, this list contributes to adding more multiple languages and was therefore tagged with NoRaRe.

**Comment by marthuis** [comment]
@LinguList Could the reference for Mel'nyčuk 1966 be this one? The authors do not reference but it would seem plausible.
https://www.worldcat.org/title/rozvytok-struktury-slovjanskogo-recennja/

**Comment by LinguList** [comment]
It could, but I could not find a scan of the book, so I'll have to order 
it via library loans... Thanks for following up!

**Comment by LinguList** [comment]
I ordered the book, but could nit find a wordlist there. So we ignore the older list.

**Comment by AnnikaTjuka** [comment]
This was solved with #1278
