### ISSUE TITLE
CSVW Metadata for boolean values in Conceptlists

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1172]
@xrotwang, @chrzyki, I have a question on boolean data. We have a list like Epps2021, contrtibuted in this PR #1170, where we have values for animacy of nouns, mass nouns (or not), etc., which have three values in the original: 1, 0 and x, x indicating "don't know". Can we elegantly model this in CSVW, e.g., using a boolean datatype, where we define symbols? Sorry for bothering with this, but I tried to find an answer in the online tutorial on csvw, but a longer search did not give me the answer.

**Comment by chrzyki** [comment]
CSVW allows for mapping strings to boolean values with [this](https://www.w3.org/TR/tabular-data-primer/#boolean-format). I.e.:

```json
"datatype": {
  "base": "boolean",
  "format": "1|0"
}
```

However, as far as I'm aware this only makes it possible to link two possible values to `true` and `false`. I'm not sure how to handle the _don't know_ cases. Validation could be done with expressions for the respective columns:

```
{
  "titles": "ANIMACY",
  "datatype": {
    "base": "string",
    "format": "1|0|dontknow"
  }
}
```

**Comment by LinguList** [comment]
Then we would go for the third option. @AnnikaTjuka, would you have time to check this in the Epps list, so we can be more explicit there? If this is specified, and you run `concepticon test`, it will through an error if the list contains more chars.

**Comment by LinguList** [comment]
Thanks, @chrzyki !

**Comment by AnnikaTjuka** [comment]
This issue seems to have been solved by @LinguList in PR https://github.com/concepticon/concepticon-data/pull/1176.
