### ISSUE TITLE
Bastin's Bantu Wordlists

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1179]
They have these mysterious 92 items. We'd need to read the original study, and provide this as a concept list, I think it is not yet in Concepticon.

* https://www.africamuseum.be/en/research/discover/human_sciences/culture_society/lexicostatistic-study-bantu-languages

Perfect work for student assistants.

**Comment by LinguList** [comment]
I have the book now. We should scan the initial pages, but before, read them to find out:

1. if there is a list of the concepts in the book as well, for reference, potentially with English translation (?)
2. how they decided about the concepts, so we can mention this in the field NOTE in the file `conceptlists.tsv` when adding this list.

This is what we typically always do: we try to find out a bit about the motivation behind these lists. So it is more than just adding data, but also understanding where data come from.

**Comment by LinguList** [comment]
@mathildavz, FYI, I wrote a [blogpost](http://hiphilangsci.net/2018/10/31/concept-list-compilation/) on the history of compiling concept lists, which shows a bit our motivation in the concepticon project.

**Comment by AnnikaTjuka** [comment]
Added in this PR: https://github.com/concepticon/concepticon-data/pull/1188
