### ISSUE TITLE
West Old Turkic

### ISSUE THREAD

**Issue by martino-vic** [concepticon/concepticon-data#1180]
I have this conceptlist here from "West Old Turkic" by András Róna-Tas and Árpád Berta:

https://github.com/martino-vic/ronatasbertawot/blob/main/cldf/parameters.csv

I would like to add this to concepticon as suggested [here](https://github.com/martino-vic/ronatasbertawot/issues/3#issuecomment-1079646083) by @LinguList 

Would be happy about some guidance, as this is the first time I'm submitting something to concepticon.

Thank you in advance,
best

**Comment by LinguList** [comment]
So with such a short concept list of about 500 items, we can make a classical submission to Concepticon, where we also double check the data.

**Comment by LinguList** [comment]
We have a new student assistant, who could also help checking concepts, running through the data. She will get a github account these days, and I'd try and involve her here.

**Comment by LinguList** [comment]
@martino-vic, if you want to go through the workflow of adding this concept list, let me know, we then give you basic instructions, and @mathildavz will also be involved, as she will learn the workflow by watching and reviewing mappings.

Here is our beginners' guide by @AnnikaTjuka: https://calc.hypotheses.org/2225

**Comment by martino-vic** [comment]
That would be a great thing to learn, would enjoy going through it!

**Comment by LinguList** [comment]
So we wait for your PR then, @martino-vic, I can already give you write access to concepticon, or you make a clone of the repository with your own user account (a fork) and then submit from there (easiest way to work). @mathildavz, you could also already make a "fork" by clicking on "fork" right on top and then selecting this to be forked to your account.

**Comment by martino-vic** [comment]
Alright, I put it on my todo-list. Currently I'm working myself through the other issues in https://github.com/martino-vic/ronatasbertawot (taking out ipatok, adding column "years"). Then I'll continue here. Or should I prioritize this one?

**Comment by LinguList** [comment]
No, take your own rhythm!

**Comment by martino-vic** [comment]
Alright, working on this now, will create a pull request soon! I read through the recommended blog entry and compared with [this recent PR](https://github.com/concepticon/concepticon-data/pull/1181/files). Seems everything pretty clear so far
