### ISSUE TITLE
Description of 925: CASSAVA

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1182]
I would like to propose to change the description of item 925 of Concepticon `CASSAVA`. Since this ID and Gloss superseeds others such as `MANIOC`, it would be more appropriate that the description refers to the root vegetable or the shrub itself.

Old: `A starchy pulp made with the roots of the cassava plant.`

**Comment by LinguList** [comment]
So we would use the definition of Manioc?

**Comment by LinguList** [comment]
In fact, @Tarotis, you can just make a PR with this change. These are fast to do, as you only change the Definition field then. If you want to change the name of the GLOSS, this is more work.

**Comment by Tarotis** [comment]
Closed via #1183
