### ISSUE TITLE
Pavia Verb Database

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1184]
This database has some 150 verbs, which we should map to Concepticon: https://hodel.unipv.it/paveda/meanings

To quote the DB, we should just use their paper: https://sigtyp.github.io/workshops/2022/sigtyp/papers/SIGTYP2022_proceedings.pdf#page=111

**Comment by LinguList** [comment]
Here, we have an English gloss, so the column should be called ENGLISH. The structure would be identical to the table you see linked, but with few modifications:

NUMBER | ENGLISH | URLBASE | ROLE FRAME | MICROROLES
--- | --- | --- | --- | --- 
19 | ASK FOR | ask-for | A asks (X) for Y | asker, askee, requested thing, ask for causer

**Comment by LinguList** [comment]
Note that the URLBASE is usually the same as the ENGLISH gloss, but in lowercase, but at times, when the gloss has spaces or brackets, they leave things out. Here, we need to pay attention to *hover* with the mouse over the URL to check its name. The final part, not the `https://hodel.unipv.it/paveda/meanings/` part is the base.

**Comment by LinguList** [comment]
So if you merge `https://hodel.unipv.it/paveda/meanings/` and `ask-for`, you get the website [https://hodel.unipv.it/paveda/meanings/ask-for](https://hodel.unipv.it/paveda/meanings/ask-for).

**Comment by mathildavz** [comment]
Thanks for your help!  I'll create the google sheet and .tsv file as soon as possible.

**Comment by AnnikaTjuka** [comment]
Added in this PR: https://github.com/concepticon/concepticon-data/pull/1188
