### ISSUE TITLE
Jonauskaite-2020-12-2 Wrong Translation

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1185]
There is a mistake in https://concepticon.clld.org/values/Jonauskaite-2020-12-2 . French "Noir" is part of the concept set BLUE, while "noir" actually means "black".

**Comment by LinguList** [comment]
It seems several glosses are mixed here, for black and blue.

**Comment by mathildavz** [comment]
There is another mistake: they translated rouge (and the Dutch rood) as green. https://concepticon.clld.org/values/Jonauskaite-2020-12-4

**Comment by mathildavz** [comment]
Similar problem with this one https://concepticon.clld.org/values/Jonauskaite-2020-12-1

**Comment by LinguList** [comment]
Good catch! We have to double-check the whole list then.

**Comment by LinguList** [comment]
Maybe, @mathildavz (this is basic concepticon work, finding and correcting errors), you could have a look at the original publication and then check how the data looks and was added?

**Comment by mathildavz** [comment]
Of course! I'll take a look on Thursday.

**Comment by mathildavz** [comment]
Turns out, I've already done a presentation on this article in Annika's seminar, so I'm pretty familiar with it. The publication itself is on emotional associations of colours in different languages and, as far as I can see it, it does not contain a word list - so I struggle to reconstruct where the Concepticon data was taken from and where the mistakes could have resulted from. Is there a way to find the finished Issue on GitHub to reconstruct this?

**Comment by LinguList** [comment]
Yes, you can filter issues by `Jonauskaite in:title` and extending search to old issues.

**Comment by LinguList** [comment]
And you can also search on https://github.com/concepticon/norare-data where we may also have had the issue. The concepts are definitely wrong, they are somehow shuffled across all languages, as I now saw.

**Comment by LinguList** [comment]
But the data is also available, as you can see from the original article:

```
All data and materials have been made publicly available
and can be accessed at https://forsbase.unil.ch/datasets/
dataset-public-detail/15126/2060/ and https://forsbase
.unil.ch/project/study-public-overview/15126/1474/,
respectively. The complete Open Practices Disclosure for
this article can be found at http://journals.sagepub.com/
doi/suppl/10.1177/0956797620948810. The design and
analysis plans for this study were not preregistered. The
complete Open Practices Disclosure for this article can be
found at http://journals.sagepub.com/doi/suppl/10.1177/
0956797620948810. This article has received the badges
for Open Data and Open Materials. More information
about the Open Practices badges can be found at http://
www.psychologicalscience.org/publications/badges.
```

**Comment by LinguList** [comment]
You should have institutional access via offsitelib.eva.mpg.de, then click on doi, insert the doi, and you get access to all data by the journal. I checked from the institute, so I had access automatically, I guess.

**Comment by mathildavz** [comment]
Have you also been able to download the data this way? Because I do get to the button that says download, but then when I click it they still require a login.

**Comment by LinguList** [comment]
And as an alternative I have the data.

**Comment by mathildavz** [comment]
It would be great if you could send it to me @LinguList. Then I'll look it through today and tomorrow. I have created an account, but it doesn't end there: they also require a text explaining the purpose for use and time frame.

**Comment by LinguList** [comment]
Did you check eith institutional access, as I suggested?

**Comment by mathildavz** [comment]
No hurry, I'll take a look at it tomorrow!

**Comment by LinguList** [comment]
Did you check the link to the journal supplement?

**Comment by LinguList** [comment]
In section Supplemental Material of the actual paper? I think you find the data we need there.

**Comment by mathildavz** [comment]
First finding: in the list you sent me, the German colour terms have a different order than the rest of the languages. That might be the origin of the mistakes - I'll look into this further.

**Comment by LinguList** [comment]
@mathildavz, do you want to write an email to them, ccying me, or would you prefer me to do that?

**Comment by mathildavz** [comment]
I can write the email. I'll send a draft to you first via Mattermost, so you can check whether it's okay. One question left: do you remember where you got the Excel file in the original issue from? Was it provided by the authors or did you create it?

**Comment by LinguList** [comment]
The excel file is shared as part of the supplemental material, right? So 
the errors are there? I think we have no other excel file than the one 
that the authors share as part of their supplement...

**Comment by AnnikaTjuka** [comment]
@mathildavz  Could you give me a brief update on whether they have replied to your email? If not, we should add a note to the description of the list that the translations are incorrect and link to the original Excel file. I found the link to the file in the old issue #928: https://www.swissubase.ch/en/catalogue/studies/13018/16941/datasets/888/1861/overview

The article supplementary material includes only a PDF: https://journals-sagepub-com.offsitelib.eva.mpg.de/doi/suppl/10.1177/0956797620948810/suppl_file/jonauskaite_tables_s1-s14_rev.pdf

Maybe the PDF is based on the Excel file or the other way around.

**Comment by mathildavz** [comment]
@AnnikaTjuka, I haven't received an answer to my email.

**Comment by LinguList** [comment]
Given that swapped columns are the problem, we could maybe do as follows:

1. correct all languages we can correct easily (I can for example make Ukrainian, French, Greek, Italian, Dutch, Serbian, Spanish, Swedish, but I don't need to make all)
2. Ignore all languages where we cannot do that
3. Indicate so in the update.

Bad links are problematic for concepticon's mapping method, since it would then take this as a precedence to map white to black in some languages.

**Comment by AnnikaTjuka** [comment]
Good point! @mathildavz Could you copy the current list to a Google Sheet and share it with us in a Mattermost chat? This way, we can work on correcting the languages that we know.
