### ISSUE TITLE
4lang conecpts

### ISSUE THREAD

**Issue by HMRLKE** [concepticon/concepticon-data#1187]
4lang v2 concept dictionary is released at (https://github.com/kornai/4lang/releases/tag/v2.0); So we would like to add the new concept list to concepticon. Moreover, the list of concepts is being machine translated to 40+ languages as well. (it will be of the same format - with 40+ columns added for the 40+ language translations)

Some kind of guidance would be great, direct pull request to the "[unlinked](https://github.com/concepticon/concepticon-data/tree/master/unlinked)." seems not to be possible (404 error).

Thank you in advance!

**Comment by LinguList** [comment]
We could prepare the mapping from our side and have you review it. Or we 
give you instructions and ask you to prepare and then review the 
mapping. Both is fine for us. The first may be slightly faster, as we 
have our specific tools for mapping and have done this several times.

**Comment by xrotwang** [comment]
last activity on the 4lang repos was 2 year ago. I think this is not really relevant anymore.
