### ISSUE TITLE
Only one concept list has no english glosses at all

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#1191]
When trying to turn concept lists into a CLDF Wordlist, I faced the problem of assigning a language to the `Concept.gloss` (assuming `Concept.english` will always be english, as advertised :) ). My first guess was that in cases where there's a `GLOSS` column rather than `ENGLISH`, the only(?) or first(?) language listed as `SOURCE_LANGUAGE` would apply to `GLOSS`. That's not the case, though. It turns out that 32 out of 33 concept lists with a `GLOSS` column list english glosses here. Only `Dellert-2018-1016` lists german glosses as `GLOSS`.

Can we fix that? I'd see two options:
- Make my first assumption work, i.e. rename `GLOSS` to `ENGLISH` for the 32 lists.
- Copy `CONCEPTICON_GLOSS` to `GLOSS` for the Dellert list (the german gloss is listed as `GERMAN` as well).

I think, I'd prefer the first option for being more explicit and transparent.

**Comment by AnnikaTjuka** [comment]
I think in most cases, we used `GLOSS' when the list didn't include an English translation. So the `Gloss' is our own translation instead of the English glosses given by the authors. @LinguList I'm not sure if there are lists where it's essential to make that distinction?

**Comment by xrotwang** [comment]
Ok, so this would be an argument to go with option 2. Another one is that
this affects only one list and not 32.

Annika Tjuka ***@***.***> schrieb am Do., 21. Juli 2022,
12:56:

**Comment by xrotwang** [comment]
Thinking a bit more about this, I'd say if `GLOSS` being present means the English translation was provided by us - rather than by the source of the conceptlist - these English translations should not be part of the CLDF data. Maybe they shouldn't be part of Concepticon at all?

**Comment by xrotwang** [comment]
I can see these English translations being useful for involving more people in concept mapping. So maybe they have a place in the curation workflow (and then also in concepticon-data). But they seem to play no role in the web app, and I'd exclude them from the CLDF data.

**Comment by LinguList** [comment]
Yes, as @AnnikaTjuka says, it refers to our translations, which are also drawing from previous translations, etc., so it is nothing that should be labeled ENGLISH.

**Comment by LinguList** [comment]
They are important in the curation, as they reflect how a person interprets a word in another glossing language than English and can therefore avoid misunderstandings.

**Comment by LinguList** [comment]
They may not be needed in the web app. But they are also useful to show erroneous mappings being due to misconceptions in translations, etc.

**Comment by LinguList** [comment]
Sorry, only now I could read the whole issue, and I'd argue that Dellert's list is an example for a wrong interpretation of "gloss" then and should indeed be modified. But it is even easier: Since we have the identical list [Dellert-2017-1016](https://concepticon.clld.org/values/Dellert-2017-1016), we can just copy the ENGLISH gloss as ENGLISH from there and even won't need the "GLOSS" anymore, since this is the translation by the authors.

**Comment by xrotwang** [comment]
Ok, I'll take care of that.
