### ISSUE TITLE
"call out"

### ISSUE THREAD

**Issue by SimonGreenhill** [concepticon/concepticon-data#1198]
There seems to be some issue with "call out":

[Cross-1964-241-31](https://concepticon.clld.org/values/Cross-1964-241-31)	call out — shout [english]	[SHOUT](https://concepticon.clld.org/parameters/715)
[Greenhill-2015-2525-805](https://concepticon.clld.org/values/Greenhill-2015-2525-805)	to call out [english]	[<NA>](https://concepticon.clld.org/parameters/0)
[Klamer-2018-607-438](https://concepticon.clld.org/values/Klamer-2018-607-438)	call out [english]	[CALL](https://concepticon.clld.org/parameters/1084)
[Robinson-2012-398-46](https://concepticon.clld.org/values/Robinson-2012-398-46)	call out [english]	[<NA>](https://concepticon.clld.org/parameters/0)
[Zgraggen-1980-380-367](https://concepticon.clld.org/values/Zgraggen-1980-380-367)	call out [english]	[<NA>](https://concepticon.clld.org/parameters/0)

.. i.e. sometimes this is mapped to "SHOUT" or "CALL" or nothing. My mental lexicon feels like "CALL" is wrong but "SHOUT" is closer. 

Should Klamer-2018-607-438 be remapped? should all the other instances be mapped to SHOUT?

**Comment by AnnikaTjuka** [comment]
Good catch! I would argue that "call out" is close to "cry out" which is consistently mapped to SHOUT. And there is at least one gloss that includes both: [Cross-1964-241-31](https://concepticon.clld.org/values/Cross-1964-241-31) "call out — shout". So all "call out" glosses could be mapped to SHOUT. @LinguList What do you think?

**Comment by SimonGreenhill** [comment]
yes, I think CALL is wrong here.

**Comment by LinguList** [comment]
Yes, that is fine. Should we ask @mathildavz to look into that next week? You could add this task then to our Project Tasks list, @AnnikaTjuka

**Comment by AnnikaTjuka** [comment]
Sure! I'll add it to the list.
