### ISSUE TITLE
Dyen-1964-154 only 153 items in the list

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1200]
https://concepticon.clld.org/contributions/Dyen-1964-154

Curiously, the highest rank is 154. So either there is an item missing or a counting error exists in the ranks.

**Comment by xrotwang** [comment]
That's what the note says:

> Of the 154 items, however, only 153 appear in the ranking, due to a typesetting error with a missing concept for rank 133.

**Comment by AnnikaTjuka** [comment]
Oh, I see. Thanks!
