### ISSUE TITLE
Fix definition for HAY

### ISSUE THREAD

**Issue by martino-vic** [concepticon/concepticon-data#1204]
Currently the defintion of HAY at https://github.com/concepticon/concepticon-data/blob/master/concepticondata/concepticon.tsv#L343 reads `Grass or cut and dried for use as animal fodder.`, I guess it should be changed to `Cut and dried grass for use as animal fodder.`?

**Comment by LinguList** [comment]
Sounds right to me. Do you want to change this and make a PR? This does 
not need any additional changes, just the definition.

**Comment by AnnikaTjuka** [comment]
I asked @mathildavz to create a PR for this change.
