### ISSUE TITLE
Mapping of Death Adder to VIPER in Greenhill-2015-2525

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1209]
[Greenhill-2015-2525-2101](https://concepticon.clld.org/values/Greenhill-2015-2525-2101) is mapped to VIPER. A Death Adder, however, is a snake native to Australia. Should we unmap this?

**Comment by LinguList** [comment]
Yes, good idea.

**Comment by SimonGreenhill** [comment]
it's probably this thing: https://en.wikipedia.org/wiki/Smooth-scaled_death_adder

**Comment by AnnikaTjuka** [comment]
In this case, I would suggest we leave the mapping as is.
