### ISSUE TITLE
Mapping of GRINDSTONE

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1211]
2459 GRINDSTONE currently includes top grinding stones and bottom grinding stones, even though we also have the concepts 3022 TOP GRINDSTONE and 3023 BOTTOM GRINDSTONE available. We should probably remap the more specific grindstones included in 2459. 
This also includes looking at Bowern-2017-348-56 again (see PR #1208).

**Comment by LinguList** [comment]
Very good spot, this should definitely be done!
