### ISSUE TITLE
URLs in Bulakh-2013-870 don't work anymore

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#1216]
The URLs to the Database of Semantic Shifts as given in [Bulakh-2013-870](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Bulakh-2013-870.tsv) don't work anymore.

There also seems to be no simple way of mapping the data we have to the new URL structure, i.e. `DSS_ID` doesn't show up in the database interface anymore, and the glosses for senses have changed in many cases, e.g. `taste` would now need to be linked to
[`taste (n.)`](https://datsemshift.ru/meanings_sense=taste%20(n.)) , `animal` to `<animal>`, etc.

So I guess the most appropriate thing to do here is removing the URLs.

**Comment by LinguList** [comment]
I am quite sure we can still show the old URLs with the waybay machine. But sure: URLs have changed completely now.

**Comment by xrotwang** [comment]
Since we have the year (2020) in the list name, we could just leave things as they are, and refer to the wayback machine.
If we do this more often, I'd refrain from turning URLs into proper links in the web app, though.

**Comment by LinguList** [comment]
Yes. I agree.

**Comment by LinguList** [comment]
Yes.
