### ISSUE TITLE
Mapping partial conceptlists to Concepticon with article-style publications

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1219]
Hello everybody,
I am currently digitalizing a couple of wordlists from large data assemblies in documents of colonial South America. In many cases, I am interested in only one or two languages, for which only a handful of concepts are provided. For example, I have one wordlist from a 1794 publication for the Chíriva language where only 7 items are given. For other languages in the same source, more than 50 concepts are provided. Is it possible to create a conceptlist here which is based on the 7 items only? As just discussed with @LinguList , this seems to be unanswered so far. 

Some observations:
a) The lists are different from language to language
b) However, they seem to be built around a common core of concepts
c) The data is not given in comparative tabular format, but are part of subsections for individual languages
d) They also do not appear as numbered concepts

Is it possible to add the concept list that is based on only the data for this specific language?

**Comment by LinguList** [comment]
My first reaction would be: if you make a good justification in NOTES, this is definitely possible and okay. It reflects glossing behavior, so it is what concepticon is made for. But it would be interesting to here what @xrotwang and @AnnikaTjuka think about this.

**Comment by xrotwang** [comment]
Hm. I'm not sure whether it's worth the administrative effort for such mini-conceptlists. I also think that these are not really **concept lists**, i.e. nothing that came **before** collecting data, but rather something that describes the data post-hoc. For cases like these, I'd say nothing is wrong with a lexibank dataset that just lists the concepts (including Concepticon links) in the ParameterTable - no need to derive this from something in Concepticon.

**Comment by LinguList** [comment]
And if you have a larger concept list for several of these, you can later still add to Concepticon the large list, and enjoy the enhanced curation, if concepticon changes, and you do not want to change your project-specific concept list.

**Comment by LinguList** [comment]
Since, as I undestand, @Tarotis has created one list for several of these smaller datasets now. So if you are fine with this solution, @Tarotis, we can close the issue.

**Comment by Tarotis** [comment]
Yes, we can close the issue.
