### ISSUE TITLE
correct Concept list Allen 2007 500

### ISSUE THREAD

**Issue by alien130922** [concepticon/concepticon-data#1227]
I stumbled across this by accident. You have used my data but have spelled my name wrong. It is Bryan not Brian. Please correct. And in the introduction to the data you say: 
'This list was taken as the reference for conducting field work on the Bai dialects, a minority language spoken in South-West China. Originally, 550 words were collected, but due to missing items in some of the languages of the survey, the list was further reduced to 500 languages.'
Which should read:
'This list was taken as the reference for conducting field work on dialects of Bai, a minority language spoken in South-West China. Originally, 550 words were collected, but due to missing items in some of the languages of the survey, the list was further reduced to 500 items.'

I would appreciate it if you could make those corrections. I had to create a github account just to leave this message. I have no idea how to edit the text myself, nor do I have time to learn.
Thanks
Bryan

**Comment by LinguList** [comment]
Thanks, @alien130922, we will correct this in the next revision of the project, it should be online available before the end of this year. You did the right thing in directly contacting us via GitHub. This is the preferred way of allowing us to handle problems in the dataset.

**Comment by LinguList** [comment]
With these additional hints, we should list @alien130922 also as as a contributor to the Concepticon project for Version 3.0.
