### ISSUE TITLE
Mapping of maternal aunt

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1229]
As @AnnikaTjuka pointed out, the Chinese gloss translated as aunt / maternal aunt is inconsistently mapped to MATERNAL AUNT, MATERNAL AUNT (MOTHER'S SISTER), MATERNAL AUNT (WIFE OF MOTHER'S BROTHER), or PATERNAL AUNT. We need to discuss how to map this gloss consistently.

**Comment by LinguList** [comment]
Can you pull out all Chinese glosses here? We can then just fix this, since Chinese is very clear with respect to these kinship terms.

**Comment by mathildavz** [comment]
2172 MATERNAL AUNT (WIFE OF MOTHER'S BROTHER) includes the following Chinese glosses:

- [ ] Chen-2012-888-78 | 舅母 [chinese] | Chen 2012 888
- [ ] Huang-1992-1820-239 | 舅母 [chinese]; aunt (mother’s brother’s wife) [english] | Huang 1992 1820
- [ ] Sun-1991-1004-328 | 舅母 [chinese]; aunt (wife of maternal uncle) [english] | Sun 1991 1004

**Comment by mathildavz** [comment]
2693 MATERNAL AUNT (MOTHER'S SISTER) includes the following Chinese gloss: 

- [ ] BeijingDaxue-1964-905-437 | 舅母 [chinese]

**Comment by mathildavz** [comment]
3042 MATERNAL AUNT (MOTHER'S OLDER SISTER) includes the following Chinese glosses:

- [ ] Castro-2010-511-361 | 姨母（妈的姐） [chinese]; aunt [english] | Castro 2010 511
- [ ] Yang-2011-1014-377 | 姨母 [chinese] | Yang 2011 1014

**Comment by mathildavz** [comment]
3043  MATERNAL AUNT (MOTHER'S YOUNGER SISTER) includes the following Chinese gloss:

- [ ] Castro-2010-511-362 | 姨妈（妈的妹） [chinese]; aunt‘s younger sis [english]

**Comment by mathildavz** [comment]
2175 PATERNAL AUNT includes the following Chinese glosses:

- [ ] Hou-2004-180-72 | 舅母 [chinese] | Hou 2004 180
- [ ] Saxena-2013-157-18 | paternal aunt [english] | Saxena 2013 157
- [ ] Sun-1991-1004-326 | 姑母 [chinese]; aunt (paternal) [english] | Sun 1991 1004

**Comment by mathildavz** [comment]
@LinguList, it would be great if you could clear this up.

**Comment by LinguList** [comment]
* BeijingDaxue-1964-905-437 | 舅母 [chinese] should be remapped to 2172
*  Castro-2010-511-361 | 姨母（妈的姐） [chinese]; aunt [english]  is correct
* Yang-2011-1014-377 | 姨母 [chinese] | Yang 2011 1014 should be 2176
*  Castro-2010-511-362 | 姨妈（妈的妹） [chinese]; aunt‘s younger sis [english] is correct
* Hou-2004-180-72 | 舅母 [chinese] | Hou 2004 180 should be mapped to 2172
* Sun-1991-1004-326 | 姑母 [chinese]; aunt (paternal) [english] is correct
