### ISSUE TITLE
Mapping of wring

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1230]
The gloss to wring is sometimes mapped to WRING, sometimes to TWIST and sometimes to TWIST (AROUND). We should discuss how to map this consistently. 
See PR #1223 for an example.

**Comment by mathildavz** [comment]
I've looked into this again and couldn't find any cases of wring being mapped to TWIST after all, @AnnikaTjuka. However, wring is sometimes mapped to SQUEEZE. Most of the mappings make sense, considering that the glosses often are _wring, squeeze_. However, I would propose the following changes: 

- [ ] [Nurse-1975-1038-344](https://concepticon.clld.org/values/Nurse-1975-1038-344): remap to WRING 
- [ ] [Castro-2015-608-404](https://concepticon.clld.org/values/Castro-2015-608-404): map to WRING (if @LinguList agrees, since this is a Chinese gloss)

**Comment by LinguList** [comment]
Yes, it says "wring (a piece of cloth)"!

**Comment by AnnikaTjuka** [comment]
Your suggestions are okay with me, too.
