### ISSUE TITLE
Create <IGNORE> class

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1235]
As discussed in PR #1232, it might be useful to have a way to EXCLUDE mappings, or refuse FOREVER to map, when things are unclear. @LinguList suggested that one could map to a new class IGNORE or similar in these cases, and we would then not look at the cases again when doing our check for left-over-mappings.

**Comment by LinguList** [comment]
@xrotwang, do you think this is a good idea? The advantage is that we can re-map more quickly and don't have to discuss accidentally cases again, which we solved a couple of years ago in discussions. Something like an authoritative "don't map this for the next couple of years".

**Comment by xrotwang** [comment]
I think this could be an option once we move to Concepticon 3.0 - when public data access should go through a Concepticon CLDF dataset, which will not include such pseudo conceptsets.

But I think it would be nice if assigning a concept to the "IGNORE" conceptset always means adding a summary of the relevant discussion as comment.

**Comment by xrotwang** [comment]
Yes, that would be a good way to start.

**Comment by LinguList** [comment]
@mathildavz do you want to set this up or do you prefer me or @AnnikaTjuka to do it?

**Comment by xrotwang** [comment]
Hm. Maybe rather store a summary of the discussion in a comment field?

Johann-Mattis List ***@***.***> schrieb am Mi., 5. Okt. 2022,
13:48:

**Comment by LinguList** [comment]
Yes, I am also fine with that!

**Comment by AnnikaTjuka** [comment]
Since the file was added a recent PR (https://github.com/concepticon/concepticon-data/pull/1240), I'll close the issue.
