### ISSUE TITLE
Release Concepticon 3.0

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1243]
I added several issues to the milestone for [Concepticon 3.0](https://github.com/concepticon/concepticon-data/milestones/3.0). I'm currently working through the issues and prioritizing the addition of new lists.

@LinguList We are currently at 409 concept lists. Are there particular concept lists that definitely need to be integrated into version 3.0?

Steps:

- [x] Resolve issues
- [x] Add lists in milestone
- [x] Update CONTRIBUTORS.md
- [x] update concepticon org profile on github

**Comment by LinguList** [comment]
I need some time to think about it...

**Comment by AnnikaTjuka** [comment]
Sure, I'll prioritize some NoRaRe data sets for now.

**Comment by LinguList** [comment]
Just added only two milestones, I think this is enough for now, from my side.

**Comment by xrotwang** [comment]
Are we clear about CONTRIBUTORS.md?

**Comment by LinguList** [comment]
Let me look at it now.

**Comment by LinguList** [comment]
I suggest, I make a suggestions, and @xrotwang and @AnnikaTjuka comment on this?

**Comment by LinguList** [comment]
Sorry, I wanted to make a PR, but then worked online, and pressed the wrong button. 

One question for @SimonGreenhill and @Schweikhard, as we are entering the 3.0 circle of Concepticon, we wanted to check with the current editors, if they are willing to take an active role for the next couple of years. So far, @chrzyki's role will consist in helping with the training and computational issues, @AnnikaTjuka will lead the integration of new concept lists interesting for NoRaRe with student assistants, @xrotwang will organize the CLLD app and the Concepticon to CLDF conversion and similar deep issues with the data, and I will coordinate adding new lists through Lexibank and the new project. Would you have time and be willing to keep helping us as editor for another release circle, e.g., by coordinating some concept mapping reviews or helping in any other way?

**Comment by LinguList** [comment]
We'd need to have you answer by Friday, as we plan on releasing Concepticon 3.0 over the weekend.

**Comment by SimonGreenhill** [comment]
Hi all, I'm happy to keep involved but I don't have any new lists etc planned to add anytime soon. Is there anything else I can do?

**Comment by LinguList** [comment]
We'd ask you to moderate prs by assigning reviewers and would involve you in some discussions about concepts and definitions?

**Comment by SimonGreenhill** [comment]
Sounds good -- and if I don't end up doing anything, feel free to drop me :)

**Comment by xrotwang** [comment]
Done: https://github.com/concepticon/concepticon-data/releases/tag/v3.0.0

Todo:
- release concepticon-cldf
- release norare-data + -cldf
- finish norare app
- deploy norare + concepticon apps
