### ISSUE TITLE
New concept COMPANION

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1246]
Similar to #1245 and #1244 , there are five cases of unmapped "companion", in addition to a new case from Kaufman-1973. There is also one case mapped to "FRIEND". I'd propose to include the new gloss "COMPANION" for all cases that do not explicitly include "FRIEND".

**Comment by LinguList** [comment]
What is the definition of companion? Can we give that? Do we identify a consistent usage in the lists? Which lists fo we talk about?

**Comment by Tarotis** [comment]
In the lists without mapping (Buck-1949-1110-1003, Hill-several, Dellert-2017-1016-252), `COMPANION` usually co-exists with `FRIEND` and seems to denote something like "comrade, accompanionship, associate". So something like a temporal association, e.g. while traveling.

**Comment by Tarotis** [comment]
@LinguList How do we proceed with this, #1244 and #1245 ?

**Comment by LinguList** [comment]
If the concept is there in Dellert, it may be worth adding it. Can you check translations there, in this list, for German, specifically, so we understand more closely what the meaning is here?

**Comment by Tarotis** [comment]
The german translation is "Kamerad". It is also part of one list of Hill (Hill-2015-999). A definition that I found in the web seems fitting: "One who accompanies or associates with another, either habitually or casually". This _can_ be a friendship, but it does not need to be.

**Comment by Tarotis** [comment]
The german annotation in Dellert lists "mit dem man Zeit verbringt", which fits the association/accompanionship of the definition.

**Comment by Tarotis** [comment]
Closed through #1268
