### ISSUE TITLE
duplicate concept in concepticon.tsv?

### ISSUE THREAD

**Issue by martino-vic** [concepticon/concepticon-data#1250]
There's `2211 CLOSE THE EYES` ["To shut down the eyes such that one cannot see anything anymore."](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/concepticon.tsv#L2212)
and `2063 CLOSE (EYES)` ["Move ones eyelids in such a way that the eyes are no longer visible."](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/concepticon.tsv#L2064)
So judging by the definitions these two mean the same thing. If not, then I think the definitions should be rewritten in a way that one can understand more clearly, what the difference between the two is. Any thoughts?

**Comment by AnnikaTjuka** [comment]
Yes, that's correct. However, the duplicate has already been detected. You can check the REPLACEMENT_ID column in `concepticon.tsv`, and also see that there are no mappings to the concept set 2211 CLOSE THE EYES.
