### ISSUE TITLE
Mapping of doorway

### ISSUE THREAD

**Issue by mathildavz** [concepticon/concepticon-data#1251]
As @AnnikaTjuka pointed out in PR #1242, _doorway_ is sometimes mapped to 1567 DOOR and other times left unmapped. We should try to find a way to do it consistently.

**Comment by AnnikaTjuka** [comment]
@mathildavz I agree with your findings. We should leave Vulic-2020 unmapped, as there are also glosses in parentheses that indicate that something like a portal is meant. I'll close this issue now.
