### ISSUE TITLE
ANATTO and ACHIOTE

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1259]
@tresoldi proposed adding a new concept ANATTO in issue https://github.com/concepticon/concepticon-data/issues/955, but [Bowern-2021-342b-3](https://concepticon.clld.org/values/Bowern-2021-342b-3) lists the gloss "achiote, anatto" which is mapped to ACHIOTE. While googling the two terms, I found out that "achiote" and "annatto" are used interchangeably.

@LinguList Should we map the _annatto_ glosses to ACHIOTE?

**Comment by LinguList** [comment]
Yes, I think that is a good idea.
