### ISSUE TITLE
Winter and Srinivasan (2022): some concept lists derived from Urban's list from 2011

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1270]
The paper by Winter and Srinivasan (https://doi.org/10.1080/10926488.2021.1945419) is interesting, since it offers data (that we may want to add to lexibank) and concept lists, one, for example, by Urban, which we have already, but this one is extended.

![urban](https://user-images.githubusercontent.com/2916210/199815848-a73eba73-d59d-4105-a3e8-428dd2152c20.png)

**Comment by LinguList** [comment]
Tasks would consist in:

1. reading the paper and checking the data
2. filing an issue for lexibank, if data comes with concrete word forms
3. assembling concept lists (discussing them here first)
4. mapping lists to concepticon

**Comment by LinguList** [comment]
The author correlate their experiment with concreteness ratings.

**Comment by AnnikaTjuka** [comment]
This was solved with #1346
