### ISSUE TITLE
"Pizza" mapped as `FOOD` in Luniewska-2019-299

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1275]
I just found that "Pizza" is mapped as `Food` in this conceptlist. Link:

https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Luniewska-2019-299.tsv#L106

Should probably be changed, but somehow I still want to eat a pizza now.

**Comment by xrotwang** [comment]
oh c'mon. Any food will do :)

**Comment by mathildavz** [comment]
So should this instance of "Pizza" be unmapped? @AnnikaTjuka

**Comment by AnnikaTjuka** [comment]
@mathildavz Yes, this should be unmapped.
