### ISSUE TITLE
New concepts: GUAVA and BREEZE

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1282]
Based on existing entries and a new list that I will add soon, I propose to add the following entries to Concepticon:

- GUAVA
  - fruit from the myrtle family, native to Latin America
  - unmapped in three existing lists, +1 that I will add
- BREEZE
  - a gentle to moderate wind
  - possibly conflicting concepts: WIND; however, I would interpret BREEZE as a sub-entry to WIND
  - unmapped in 4 existing lists, +1 that I will add

**Comment by LinguList** [comment]
I am not against adding the two concepts.

**Comment by Tarotis** [comment]
@AnnikaTjuka If you also agree, I would create the PR for this

**Comment by AnnikaTjuka** [comment]
I'm a bit hesitant about BREEZE because there are several glosses like _wind_breeze_ or WIND (BREEZE). So the distinction might not be so clear and at some point, we would need a WIND OR BREEZE concept. @LinguList Would it make sense to introduce WIND OR BREEZE directly and map all ambiguous glosses (e.g. _wind_breeze_) as well as the individual _breeze_ glosses to it?

**Comment by LinguList** [comment]
Yes, I see the point. We would need a detailed check of all currently mapped wind glosses. But those cases with BREEZE in brackets are not necessarily cases where it is wind or breeze, but rather it explains: wind is the wind like in breeze not like in "break wind" or whatever.

**Comment by Tarotis** [comment]
While in one case it says indeed "as in breeze", the other three cases do not specify. It says "WIND (BREEZE)" or "wind_breeze".

**Comment by LinguList** [comment]
The typical procedure is to use brackets in the meaning "as in", so I would rather say: they refere to WIND than to BREEZE.

**Comment by Tarotis** [comment]
Perfect. Then all "Wind (Breeze)" cases stay mapped to WIND, and only those cases that only have "breeze" will be added to BREEZE (four occurrences). If you agree to this, I would add a PR that adds the concepts from #1290 and this issue here.

**Comment by AnnikaTjuka** [comment]
Sounds good to me.
