### ISSUE TITLE
Release 3.1

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1300]
There are a couple of issues with minor corrections that could be included in release 3.1.

- [x] #1277
- [x] #1275

Other to-dos:
- [x] Update CONTRIBUTORS.md

**Comment by xrotwang** [comment]
Should we use the milestone https://github.com/concepticon/concepticon-data/milestone/17 to mark issues that should be resolved or not?

**Comment by AnnikaTjuka** [comment]
Yes, I just wanted to extract the two before transferring all the other issues to the 3.2 milestone.

**Comment by LinguList** [comment]
Yes, good idea.

**Comment by AnnikaTjuka** [comment]
I moved open issues that propose additional concept lists to the next milestone [3.2](https://github.com/concepticon/concepticon-data/milestone/18). There are 6 open issues (#928 and #1185 belong to the same discussion) for milestone [3.1](https://github.com/concepticon/concepticon-data/milestone/17). I assigned them to @mathildavz and myself.

We are at 421 lists at the moment and will get to 424 lists when all PRs (#1303, #1299, #1298) are merged.

**Comment by AnnikaTjuka** [comment]
@xrotwang All issues related to milestone 3.1 are now resolved and everything is ready for the release.

**Comment by AnnikaTjuka** [comment]
@mathildavz is consistently working on the unlinked concepts, but there are no urgent replacements or additions to be included in the version from my side. @LinguList Is there anything to consider from a Lexibank perspective?
