### ISSUE TITLE
Duplicate: 2992 TIP (OF OBJECT) and 3255 POINT (POINTED END)

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1302]
@LinguList I would like to merge these two concepts. Do you agree?

- https://concepticon.clld.org/parameters/2992
- https://concepticon.clld.org/parameters/3255

**Comment by LinguList** [comment]
yes!

**Comment by AnnikaTjuka** [comment]
Ok great, I'll open a PR as soon as the other pending PRs are resolved.
