### ISSUE TITLE
Possibly splitting LEAVE into GO AWAY and LEAVE

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1313]
Based on the discussion in #1311 , it was proposed that we should discuss whether we should split [LEAVE](https://concepticon.clld.org/parameters/1752) into LEAVE and GO AWAY, as both entries are part of the list separately. There are at least two lists where the entries co-occur as separate entries.

It will be quite difficult to find a good split I think, as most lists have an entry of the kind "to leave, to go away". Then, of course, there is also [GO OUT](https://concepticon.clld.org/parameters/1107), which we should probably consider in the discussion.

**Comment by mathildavz** [comment]
I've taken a look at the entries and agree that it is quite difficult to find a good split. Should we still try to divide them? 
@Tarotis & @AnnikaTjuka

**Comment by AnnikaTjuka** [comment]
I looked at the glosses and agree that it is too difficult to split them. I'll close the issue for now.
