### ISSUE TITLE
CROSS (River) mapped to several different concepts

### ISSUE THREAD

**Issue by Tarotis** [concepticon/concepticon-data#1316]
Reviewing #1315 , I found that "to cross (e.g. a river)" is currently mapped to different entries:

- CROSS (referring to the object)
- TRANSIT
- TRAVERSE

Possibly, all of them should be mapped to TRAVERSE to be consistent about this.

**Comment by AnnikaTjuka** [comment]
@Tarotis Good catch! Yes, they should be remapped but I'd suggest remapping them to TRANSIT because several "cross" glosses are already mapped to this concept set. @mathildavz Would you prepare a PR for this?

**Comment by Tarotis** [comment]
Then one entry (https://concepticon.clld.org/values/Nurse-1975-1038-319) should be re-mapped from TRAVERSE to TRANSIT as well, to stay consistent.

**Comment by mathildavz** [comment]
I can't find any entries under "to cross (e.g. a river)". The only thing I can find are a few cases of "cross (river)", which are all consistently mapped to TRANSIT. Should I still remap those to TRAVERSE, @AnnikaTjuka & @Tarotis?

**Comment by Tarotis** [comment]
- https://concepticon.clld.org/values/Greenhill-2015-2525-2422
- https://concepticon.clld.org/values/Kaufman-1973-1028-672
- https://concepticon.clld.org/values/Teit-1908-693-657
- https://concepticon.clld.org/values/TeilDautrey-2008-430-99
- https://concepticon.clld.org/values/Snider-2004-1700-850

.. and several others. My example above was only that: an example :)
