### ISSUE TITLE
Concept list by Lastra (Spanish)

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1332]
@MuffinLinwist or @mathildavz, would any of you have some additional capacities to type off and add to concepticon the following concept list that I attach here, by Lastra 1986?

```
@book{Lastra1986,
  author = {Lastra de Suárez, Yolanda},
  date = {1986},
  title = {Las Áreas Dialectales del Náhuatl Moderno},
  publisher = {Universidad Nacional Autónoma de México, Instituto de Investigaciones Antropológicas},
  language = {es},
  address = {Mexico}
}
```

[Lastra1986.pdf](https://github.com/concepticon/concepticon-data/files/13070871/Lastra1986.pdf)

**Comment by LinguList** [comment]
There is no real hurry, but we prepare this document for a dataset of @maunus, who is working on the data and has digitized parts for it, so it is useful for Lexibank and beyond.

**Comment by mathildavz** [comment]
I can begin working on it this week, @LinguList. Should I also include a column with English translations? 
Maybe @MuffinLinwist can help with the review later on as he is a Spanish native speaker :)

**Comment by LinguList** [comment]
English Translations would be super, thanks a lot to both of you!
