### ISSUE TITLE
RED DEER as sub-concept of DEER

### ISSUE THREAD

**Issue by MuffinLinwist** [concepticon/concepticon-data#1335]
As discussed in #1333, we can decide on adding `RED DEER` as a sub-concept of `DEER`. The gloss is also present in [Reinhard-1970-337-255](https://concepticon.clld.org/values/Reinhard-1970-337-255).

**Comment by LinguList** [comment]
I am happy with such a modification, you can proceed with a PR, if you want ;-)

**Comment by MuffinLinwist** [comment]
@LinguList, the PR #1339 is now ready :)

**Comment by MuffinLinwist** [comment]
This issue was implemented in Concepticon and has been finalized  (#1339).
