### ISSUE TITLE
Mapping of ear ornament

### ISSUE THREAD

**Issue by MuffinLinwist** [concepticon/concepticon-data#1336]
As discussed in #1333, there is no clearness on how to map `ear ornament`. There are many entries in Concepticon being unmapped and one mapped to [EARRING](https://concepticon.clld.org/parameters/770). That rises the question: Should we map it to that `concept set` or should we add a new `ear ornament` concept?

**Comment by chrzyki** [comment]
From my understanding (and some quick reading, I might have missed some culture-specifics here) `ear ring` and `ear ornament` are closely related enough as to map them interchangeably. I'd personally be fine with having `ear ornaments` mapped to `EARRING`.

**Comment by LinguList** [comment]
Me too.

**Comment by MuffinLinwist** [comment]
Thanks @chrzyki and @LinguList, I'll now implement this on the list and close the issue. Thanks to both of you for the clarification!
