### ISSUE TITLE
Duplicates 2288 METEROID and 2835 SHOOTING STAR

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1341]
We have two concepts: 2288 METEROID (SHOOTING OR SHINING STAR) and 2835 SHOOTING STAR (thanks to @katjabocklage for pointing out this issue). These seem to be duplicates. In addition, there is a spelling error in METEROID (METE**O**ROID). I'd suggest merging the two so that 2835 is replaced by 2288 and correcting the spelling error. @LinguList Do you agree?

**Comment by LinguList** [comment]
Yes!
