### ISSUE TITLE
Mappings of CLAW and CLAW OR NAIL

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#1343]
Based on a discussion in PR #1340, we discovered that the glosses mapped to CLAW and CLAW OR NAIL are not consistently mapped. There are multiple instances of `claw (nail)` or similar mapped to CLAW. These need to be checked and remapped to CLAW OR NAIL.

**Comment by chrzyki** [comment]
I'll have a look at this for 3.2.
