### ISSUE TITLE
Winter-2022-98 day and noon

### ISSUE THREAD

**Issue by AnnaDiNatale** [concepticon/concepticon-data#1344]
I found a problem with the Winter-2022 data. day and noon have {"polysemy": 3, "overt_marking": 20} if we look at the entry relative to day. If we look at the entry relative to noon, day and noon have {"polysemy": 2, "overt_marking": 24}. In Urban's paper, day and noon have 2 polysemies and 35 overt markings. Note that the direction is always the same (day -> noon). I do not know which one is the right one.

**Comment by LinguList** [comment]
I see, so the internal requirement that for two lines the data should be identical is not met here!
