### ISSUE TITLE
New concepts COLLAPSE, HOARSE, and PLATEAU

### ISSUE THREAD

**Issue by MuffinLinwist** [concepticon/concepticon-data#1377]
As raised in the (already closed) #1372 PR, we can discuss the incorporation of new concepts `COLLAPSE`, `HOARSE`, and `PLATEAU`. We have already six lists with the first concept, four with the second, and four with the last one. I can propose a modification on a new PR if we decide on it, @LinguList, @AnnikaTjuka, and @chrzyki.

**Comment by chrzyki** [comment]
Thanks! I'd be all for:

- `COLLAPSE` (6-7 unmapped instances)
- `HOARSE` (5 unmapped instances)
- `PLATEAU` (5 unmapped instances)
- `AGAVE` (5 unmapped instances)
- `LAWN` (5-6 unmapped instances, one mapping to review)
- `TORTILLA` (~5 unmapped instances)

6 new concepts, roughly 30-31 new mappings, seems like a good deal to me.

**Comment by LinguList** [comment]
Yes, I agree!

**Comment by MuffinLinwist** [comment]
Great, so I prepare a PR with this aggregations. One can also add `SARDINE` ( #1327) in the list of new mappings. Is it okay if I do so, @chrzyki and @LinguList?

**Comment by chrzyki** [comment]
Fine by me and thank you very much!

**Comment by MuffinLinwist** [comment]
The PR #1383 is ready for reviewers now :)
