### ISSUE TITLE
Starling sub-senses as Meta-Data

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#141]
Starling has a list of about 7500 concepts which are all split up into up to 5 subsenses (tree has, e.g., something like "plant", "green", "wood", if I remember properly). Starling uses these for internal concept comparison. We could likewise 
- either try to describe concepts in STARLING sub-senses

or 
- map STARLING concepts with sub-senses as metadata (probably easier and more consistent)

In any way, this will provide a rich additional resource for meta-data. The only problem is to find out how to quote STARLING in the end, and which data to use. Best would be to ask the ToB team whether they would share an actual list, and potentially also whether they could put it online, so that we can really quote it.

**Comment by xrotwang** [comment]
I agree, getting someone from ToB on board would be the best way to go about this.
