### ISSUE TITLE
New concept: MANATEE

### ISSUE THREAD

**Issue by FredericBlum** [concepticon/concepticon-data#1415]
There are three conceptlists that have manatee/manatí as an entry, but we do not have this mapped yet. We are also working with other datasets that will also feature this word. These are the forms in question:

- https://concepticon.clld.org/values/KochGrunberg-1914-821-439
- https://concepticon.clld.org/values/Gerardi-2022-705-304
- https://concepticon.clld.org/values/Bowern-2021-342b-188

If we agree that we should add this, I can prepare a PR.

**Comment by AnnikaTjuka** [comment]
Sounds good to me. I think we should add this.

**Comment by xrotwang** [comment]
I think it would be good to - whenever we add species (or genus) to concepticon - also add the GBIF ID, here [2435291](https://www.gbif.org/species/2435291). (We don't want to / cannot pin down a particular species here, right?)

**Comment by xrotwang** [comment]
If all the concept lists concern South American languages, https://www.gbif.org/species/2435296 might be appropriate. I don't know if African manatee species are called manatee, too, though.
