### ISSUE TITLE
Duplicate concept sets: 2688 FOOT (UNIT), 2782 FOOT (MEASURE)

### ISSUE THREAD

**Issue by bgo-eiu** [concepticon/concepticon-data#1424]
These concept sets seem to refer to the same concept and should be merged accordingly:

https://concepticon.clld.org/parameters/2688

https://concepticon.clld.org/parameters/2782

**Comment by AnnikaTjuka** [comment]
@bgo-eiu Thank you for pointing this out. We've already recognized that 2782 FOOT (MEASURE) is a duplicate. You can identify duplicate concepts by checking the column “REPLACEMENT_ID” in the file [concepticon.tsv](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/concepticon.tsv).
