### ISSUE TITLE
add meta-data on concept similarity from bigram-appraoches

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#167]
just found this repo on github (saw the talk):
- https://github.com/williamleif/histwords

and we might consider computing similarities between concept sets, or also comparing polysemy measures with CLICS-like polysemies

they have a python code for that, so it should be rather straightforward

**Comment by AnnikaTjuka** [comment]
@LinguList Should I transfer this issue to NoRaRe? I'm not sure about the scope of the data.

**Comment by LinguList** [comment]
Theoretically, one can add the embeddings for some 2000 words in
concepticon, where they can be found. So one could argue this is an
interesting dataset, and one can download all data (but it is huge). So
yes, for the time being transfering this seems okay.
