### ISSUE TITLE
Metadata from SemDom.org

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#171]
Thanks to @haspelmath, for pointing to this resource:
- http://www.semdom.org/

They offer semantic domains and apparently even more on connecting between these, all apparently manually done, which would make up for a nice meta-data to the concepts, where available.

**Comment by xrotwang** [comment]
Doesn't seem straightforward to scrape. Would be nice to have as [SKOS](https://en.wikipedia.org/wiki/Simple_Knowledge_Organization_System) document.

**Comment by AnnikaTjuka** [comment]
Same as #644 . The accessibility is very poor.
