### ISSUE TITLE
link to conceptnet5

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#249]
They offer a very nice API and many different concept relations, also in different languages. Parts of the data can be used as CCBY, but all data needs to be shared alike. Yet for us, this would mean we could directly include it, or just link to the API. More description is here:

* https://github.com/commonsense/conceptnet5/wiki/API

**Comment by LinguList** [comment]
The cool thing is that the links are weighted, so one can extract some network information from them, useful for further approaches.

**Comment by AnnikaTjuka** [comment]
Same as #103 and recently transferred to https://github.com/lingpy/norare-data/issues/80
