### ISSUE TITLE
LOGOS children dictionary with flashcards

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#28]
The [Logos Children](http://www.logosdictionary.org/childrendictionary.php?action=result&code=440021&lang=en) dictionary has translations for some 1000 concepts into some 60 languages. It may be interesting to link these concepts, especially since they offer images for each of the concepts, which may be useful to have for certain purposes.

**Comment by xrotwang** [comment]
The Logos data doesn't seem to have an open license, though.

**Comment by LinguList** [comment]
Can we still take their wordlist and link the images? I have already
assembled both the concepts and the links...

**Comment by xrotwang** [comment]
hotlinking images is considered bad practice, I think. Linking to the words should be ok, though. It might be worth asking how the data can be shared, though.
