### ISSUE TITLE
broaden definition of VINE

### ISSUE THREAD

**Issue by IrenH** [concepticon/concepticon-data#294]
the definition of VINE should be broader
VINE [343] "the climbing plant (genus: Vitis) that produces grapes"
maybe "that produces grapes" could be deleted and the definition could be phrased broader like on Wikipedia:
https://en.wikipedia.org/wiki/Vine

**Comment by LinguList** [comment]
Well, if we check the current concept labels in the seven lists that [HAVE this concept](http://concepticon.clld.org/parameters/343), it looks more like the narrow definition (German Weinstock is obviously the narrow definition, it does not mean Kletterpflanze). So we need the narrow and the broad definition, if native speakers are more likely to think of the broader definition. But what should we call the narrow concept then? *Vitis* sounds very technical, and I doubt the people who grow vine call them like this.

**Comment by IrenH** [comment]
grapevine?

**Comment by LinguList** [comment]
Yes, this will be fine, but just to confirm: native speakers of English, do they think of "VINE" as the plant that grows on walls and sticks, or do they think of the thing that produces the grapes? If the latter, we should redefine as VINE (CLIMBER) for the broad (?) sense, but we should only do so if we have confirmation that there are concept lists which actually WANT to express this general meaning. In my opinion, most of the seven concepts refer to the grapevine, not to the climbing plant.

**Comment by SimonGreenhill** [comment]
This native speaker thinks a VINE is a type of plant (sometimes CLIMBing), of which a GRAPEVINE is a specific type. 

I'm pretty sure the [Z'graggen](http://concepticon.clld.org/values/Zgraggen-1980-380-160) list is the generic VINE (not GRAPEVINE). 

My recommendation would be to create GRAPEVINE and move the wine specific vines to that?
