### ISSUE TITLE
DIACL-Concept Lists

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#304]
They offer different concept lists,e.g,:

* https://diacl.ht.lu.se/WordListCategory/Details/100

But we should beware that the data actually comes from IDS, so there is some overlap to be expected (which is not bad), but they refine the glosses and define different labels, so these are valid concept lists. Question is only, how to base deal with them: add the 100, the 200 "Swadesh" list plus the other lists separately, or make one big list with all their concepts and add the sublist in an extra field (general problem of some other lists in our concepticon, as the ones by Yakhontov, etc.).

**Comment by xrotwang** [comment]
I'd say add them separately. Didn't we have the idea of adding relations between concept lists anyway?

**Comment by LinguList** [comment]
Yes, and I just saw we can have the lists in some regular format, and we're just talking about 8 lists here. And they offer all data in XML format, so it will be easy to get the data.

**Comment by xrotwang** [comment]
@LinguList How should we name these lists? `DIACL-2017-XXXa` - `DIACL-2017-XXXl`?

**Comment by xrotwang** [comment]
Or `Carling-2017-XXXa` - `l`?

**Comment by LinguList** [comment]
Our current practice is using Author-Year-NumberListSuffix with ListSuffix=a, b, c, if numbers are identical, otherwise, without.

**Comment by xrotwang** [comment]
Ok, so in this case, we are dealing with the following sublists:
```
Colour terms - Eurasia 10
Culture words for the Caucasus 87
Culture words for old Middle-Eastern non-IE 97
Culture words for Uralic 97
Culture words for Turkic 87
Culture words for Austronesia 112
Culture words for South America 240
Culture words for Basque 127
Swadesh 100 104
Swadesh 200 209
Culture words for Indo-European 97
```
i.e. 87 and 97 item lists appear multiple times, thus would get a suffix, the others not. Giving all of them a suffix would appear more natural, I guess.

**Comment by LinguList** [comment]
Yes. In fact: the suffix can ALWAYS be added, I have just not done so in the past, if the item number was different, so you can also just add them. Code won't break.

**Comment by chrzyki** [comment]
That's all done & taken care of, correct? See this PR: https://github.com/concepticon/concepticon-data/pull/564.
