### ISSUE TITLE
Enhance documentation on collaboration

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#316]
With @SimonGreenhill joining the team, I see that we need to be a bit more verbose in those many implicit things we handle (the different lists, our implicit styles for naming). This should be done on the github contribution.mg, and will make it easier for other people to jump on the train.

**Comment by chrzyki** [comment]
Done with https://github.com/concepticon/concepticon-data/blob/master/CONTRIBUTING.md and tutorials like https://calc.hypotheses.org/2225.
