### ISSUE TITLE
make a more transparent procedure (information mainly) on definitions

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#333]
Make clear on the website on what our definitions are based, and maybe think of enhancing future definitions by cross-checking not only with wikipedia but also with some English dictionaries, such as [collins](https://www.collinsdictionary.com/) or similar. Unfortunately, they do not offer fixed urls to cite the relevant definitions, which makes wikipedia still the first choice for definitions that can be found there.

**Comment by xrotwang** [comment]
@LinguList can I get some input (a text paragraph, maybe) on this?

**Comment by LinguList** [comment]
Yes, sorry, will try and look into this today later or tomorrow!

**Comment by LinguList** [comment]
> Note that the most important contribution by the Concepticon project are not the definitions given for individual concepts, but the judgments on which individual elicitation glosses we assign to the same concept set in our Concepticon. As a result, the definitions may sometimes look less optimal and at times even utterly wrong. We appreciate any help in improving the definitions, but we recommend uses to check the actual assignment of elicitation glosses to concept sets at the same time, since this assignment should inform the definition, and not vice versa.

@xrotwang and @AnnikaTjuka, is that easy to understand?

**Comment by LinguList** [comment]
Yes. Do you think that makes sense? Or is it too long?

**Comment by AnnikaTjuka** [comment]
I'd propose a few minor changes:

- "As a result, the definitions may sometimes look less optimal." 
Without the "utterly wrong" part. 
- We appreciate any help in improving the definitions, but we recommend users to check the actual assignment of elicitation glosses to concept sets since this assignment should inform the definition, and not vice versa." 
 "users" instead of "uses" and without "at times"

**Comment by xrotwang** [comment]
And "less than optimal".

**Comment by AnnikaTjuka** [comment]
Oh yes, thanks!

**Comment by xrotwang** [comment]
https://github.com/concepticon/concepticon/commit/d5d7bd40feddc03b1ba0d9f2e1b752c17db20b7a
please close if that's ok

**Comment by AnnikaTjuka** [comment]
Looks good from my side!
