### ISSUE TITLE
LexiRuma Data: Klamer-2017-644

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#353]
The data is online and published in a first version. They link about 500 concepts already to concepticon, but 150 are missing, although I suspect we have many by now (like FOOTPRINT, etc.). So adjusting this list and adding it to concepticon would be useful.

**Comment by Anaphory** [comment]
Tell me how to make your life easier with this.

**Comment by LinguList** [comment]
Well, ideally, you would give another run to the automatic linking, and then manually clean the links that don't work (I spotted some links that I did not find quite satisfying in the current version). I could then review it, and we'd add new definitions for all the concepts we find missing. We did a similar workflow with Northeuralex. If you could point me to a pure concept list, without lexical data, which is ideally online, I'd start from there to make a first new auto-mapping, and then either refine myself, or if you find time, have you or your colleagues go through it. You could also then add it as a PR to concepticon, but ask me before on the data which is needed, as we'll need to have a source, a description and other stuff at the same time.

**Comment by chrzyki** [comment]
Done in https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Klamer-2018-607.tsv.
