### ISSUE TITLE
Historical Thesaurus of English

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#375]
This system offers a hierarchy. As metadata, this may be nice, but it will be difficult to parse all data: http://historicalthesaurus.arts.gla.ac.uk/

**Comment by AnnikaTjuka** [comment]
@LinguList Should I transfer this to NoRaRe?

**Comment by LinguList** [comment]
yes, and before releasing, we decide if we leave it or kick it out ...
