### ISSUE TITLE
MORTAR CRUSHER better as MORTAR

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#380]
suggestion by Abbie...

**Comment by LinguList** [comment]
@xrotwang, do we need/have a "retire" procedure for this kind of stuff, or can we simply replace the concepticon_gloss?

**Comment by xrotwang** [comment]
I think we could simply start with a CHANGES.md, see http://keepachangelog.com/en/1.0.0/

**Comment by LinguList** [comment]
Okay, this would mean something like:

```markdown
### Changed
#### Concepticon Gloss
- MORTAR CRUSHER replaces MORTAR 
```

seems that it would be useful to stick to some regular style (as it may happen in the future, that we refine some other glosses as well, especially also for kinship terms)

**Comment by xrotwang** [comment]
Maybe rather
```
### Conceptsets

- Gloss: MORTAR CRUSHER replaces MORTAR
```

**Comment by xrotwang** [comment]
But yeah, something simple. I wouldn't worry about machine readability until we have a couple more examples.
