### ISSUE TITLE
Concept mapping for gloss languages other than English 

### ISSUE THREAD

**Issue by IndianaTones** [concepticon/concepticon-data#389]
Apologies, but I cannot find the correct code for how to map using a glossing language other than English (in this case French). 

I usually use:

$ concepticon map_concepts INFILE.tsv > OUTFILE.tsv

so not sure where to indicate the difference.

**Comment by xrotwang** [comment]
I guess `map_concepts` could use a docstring:
```
$ concepticon help map_concepts
None
```

**Comment by xrotwang** [comment]
```
$ concepticon map_concepts --language fr  INFILE.tsv > OUTFILE.tsv
```
should do the trick.

**Comment by xrotwang** [comment]
Please leave this issue open until the command is documented.

**Comment by LinguList** [comment]
Documentation has been so far prepared for the tutorial: 

* https://github.com/digling/edictor-tutorial/blob/master/Historical%20Language%20Comparison%20with%20LingPy%20and%20EDICTOR.ipynb

Search for 2.5: "Enhancing your data".  This could probably be copy-pasted.

**Comment by IndianaTones** [comment]
Thank you - the solution is a bit tricky as I had to label the glosses column as ENGLISH (even though it is obviously French).

The string which works is:

$ concepticon --language=fr map_concepts Concepts-Fulfulde.tsv

as warned, the output isn't terrific- 430/3343, 13%, but better than nothing!

**Comment by LinguList** [comment]
Oh, that is annoying, but no need to label it to "ENGLISH", "GLOSS" will also work, but this is a real bug, we should fix that.

**Comment by IndianaTones** [comment]
Just wanted to update that the glosses it found were really accurate. I got a total of 414 solid entries from this so thank you!!!

**Comment by LinguList** [comment]
wow, this shows that it is a useful function. We hope wit the next release we'll have it working more properly. And with new data to be added (more lists in French, etc.), it will hopepfully even work better on different languages...
