### ISSUE TITLE
GECO corpus on mono- and bilingual sentence reading

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#426]
If you look at this corpus, you'll see that it is an excellent example for metadata, as it provides a rather detailed annotation of a full novel, along with eyetracking data:

* http://expsy.ugent.be/downloads/geco/

I imagine, one could automatically link the data as metadata, but it would require to transform the original dataset, as they have repeating words, so from these, we'll need to refererence back to lines in the original data. 

There is a study of the team that suggests that AoA has an impact on bilingual sentence reading. This is extremely interesting, as it means: if you know a concept in your mother-tongue, you'll learn it faster in another language.

**Comment by AnnikaTjuka** [comment]
We would need to find a solution for multiple occurrences of a word. In addition, sentence reading and eye-tracking are not the focus in NoRaRe. Thus, I'll close this issue.
