### ISSUE TITLE
Lieberherr-2017-100: Dataset on Kho-Bwa language cluster

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#428]
100 concepts in this dataset, url for the data is:

* https://cloudfront.escholarship.org/dist/prd/content/qt4t27h5fg/supp/dataset_khobwa.csv

Article URL is here:

* https://cloudfront.escholarship.org/dist/prd/content/qt4t27h5fg/qt4t27h5fg.pdf?t=p2q2o0

I already made the bibtex:

```
@Article{Lieberherr2017,
  author  = {Lieberherr, Ismael and Bodt, Timotheus Adrianus},
  title   = {Sub-grouping Kho-Bwa based on shared core vocabulary},
  journal = {Himalayan Linguistics},
  year    = {2017},
  volume  = {16},
  number  = {2},
  pages   = {25-63},
}
```

**Comment by LinguList** [comment]
Their code is also on github: https://github.com/metroxylon/subgrouping-kho-bwa

**Comment by Kristina-Pianykh** [comment]
I've just figured that this list has already been mapped to [Lexibank](https://github.com/lexibank/lieberherrkhobwa/blob/master/etc/concepts.csv). The question is whether it has to be mapped to Concepticon as well? It also looks like all the target lexical items on this list are represented in the IPA format.

**Comment by LinguList** [comment]
Nope, this is pending, but it was something that should be done with a paper we have to submit, so if you go ahead, this is cool. And less work, take the lexibank mappings and add the rest. @chrzyki and @tresoldi make sure to look into including this in our update for the MIT chapter.

**Comment by LinguList** [comment]
And if you include this, don't forget to thank @Kristina-Pianykh for her help in the acknowledgments.

**Comment by Kristina-Pianykh** [comment]
I have made all the necessary modifications to submit the list with the lexibank mappings but when I ran the concepticon test code in the command line, it returned the following errors:

1. the ARM OR HAND concept set on the list is assigned CONCEPTICON ID 212 (which is in fact mapped to FIELD on Concepticon whereas ARM OR HAND are mapped to 2121);
2. _smoke_ is mapped to the concept set SMOKE, which requires specification (namely, SMOKE (EXHAUST) in this case).

Does it mean that these mappings in the Lexibank datasheet should be corrected before I submit the list to the Concepticon repository?

**Comment by LinguList** [comment]
Ohoh, I wonder who did do that concept mapping in lexibank wihtout paying attention here. In any case, both @chrzyki and @tresoldi are first authors on our paper and should make sure that the lexibank dataset is now accordingly corrected, and also check your PR, if you submit hte list to concepticon.

**Comment by chrzyki** [comment]
Thanks @Kristina-Pianykh, will look at this!

**Comment by chrzyki** [comment]
(Will happily address and correct the problem, just wanted to note that this dataset is not included in our CLICS3 collection.)

**Comment by LinguList** [comment]
yes, but it's important for the MIT paper, right? We didn't do it by then, but should include it now...

**Comment by chrzyki** [comment]
Correct! Think so too.

**Comment by chrzyki** [comment]
Done
