### ISSUE TITLE
Link relevant concept sets to eol.org and/or gbif.org

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#43]
To allow specialized lexical collections like [Tsammalex](http://tsammalex.clld.org) to be linked to concepticon, it would be useful to provide [EOL](http://eol.org) and [GBIF](http://gbif.org) taxon identifiers for relevant concept sets.

**Comment by LinguList** [comment]
There are so many cool things which still need to be linked. At some point I would like to apply for some funding for this...

By the way: if we apply the additional meta-data structure with one json file per concept ID, as discussed, All wikipedia definitions, which I started to mark in the concept sets should also be exported to the meta-data. 

I would summarize the list of useful metadata as follows (I add information on where initial work has been made):

* [EOL](http://eol.org/)
* [GBIF](http://gbif.org/)
* [babelphy](http://babelphy.org): wrote a crawler that searches for concepticon glosses. There are often multiple links, however, so the data needs to be sieved, but one could start with subsets, like Swadesh 100, for example
* [wikipedia](http://en.wikipedia.org): started to annotate when definitions were taken from wikipedia, and added diverging links, where our concept set label is not the same as the name in wikipedia
* [Concreteness ratings](http://crr.ugent.be/papers/Concreteness_ratings_Brysbaert_et_al_BRM.txt): we could just go for gloss-identity
* [Omegawiki](http://www.omegawiki.org/): we already have large parts
* [LEGO](http://lego.linguistlist.org/): as provided in J. Goods original concepticon (source on github)
* [Word frequency measures](http://www.ugent.be/pp/experimentele-psychologie/en/research/documents/subtlexus/overview.htm): I know this is not necessary related to "concepts" but it would be useful, I think. And, again, one could start by searching for identity links.
* some taxonomy: maybe the one by the [stedt](http://stedt.berkeley.edu/%7Estedt-cgi/rootcanal.pl/chapters#2.0)

**Comment by xrotwang** [comment]
@LinguList one JSON file per **concept set ID**, right?

**Comment by LinguList** [comment]
That's how I thought that you suggested? Maybe it's easier to have one big file? Editing will anyway be tedious, so I think, I will need to write some thing that inserts new data into the json-file, once it has been assembled. 

An even simpler structure, but maybe more difficult to handle from within CLLD (?), would be to have a folder metadata/ and add csv-files in the folder, which give concept set ID, the ID of the linked resource, and probably a value (for word frequency etc. this would be useful, also for meta-data which is available in form of a text-file only, and not as a web-resource. We would still need a josn file to store information on the resources, similar to our conceptlists.tsv. What would you think about that structure? It would be easier to maintain it manually...

**Comment by xrotwang** [comment]
@LinguList Oh, no. In the comment above you said

> one json file per concept ID

so I only wanted to clarify it's per **concept set ID** not **concept ID**.

**Comment by LinguList** [comment]
Ah, I see: sorry! I meant: concept set ID!

**Comment by xrotwang** [comment]
@LinguList So in the comment above you mean a folder with one csv file per metadata type, i.e. one for GBIF and EOL ids, one for wikipedia URLs, etc? If so, yes, that sounds like an even better solution; in particular since metadata collection and editing will typically be done per metadata type and not per concept set.

**Comment by LinguList** [comment]
yes, that's what I also thought. And we may even start by adding a meta-data file completely, but just leaving links to the concepticon concept sets open, if we don't find them (provided there are files which are under a free licence). 

BTW: I forgot to add wordnet to the collection. 

One thing we need to decide here, is, however, how many links we allow:

Do we allow to link one concept set ID to multiple nodes of the same meta-data set? Do we allow the opposite?

Intuitively, I think we can do with a strict 1-1 linking, allowing to leave thinks un-linked on both sides (this is useful for purposes of editing the data manually).

**Comment by xrotwang** [comment]
So yes, new proposal: Have a folder `concept_set_meta`, containing files, e.g. `taxa.csv`:
```
CONCEPT_SET_ID    EOL_ID    GBIF_ID
1234                              5678         9123
...
```
etc., and a metadata record for concept set `1234` is simply the aggregated dictionary with keys from all column names in these files and corresponding values. If we want to re-use column names across csv files, we'd have to namespace the keys in the aggregation, i.e. have `taxa.GBIF_ID`.

**Comment by LinguList** [comment]
I think we can do without namespaces, since I assume that the meta-data will be added in separation. 

One question remains: do we allow values apart from IDs, like, for example:

```txt

CONCEPT_SET_ID     FREQUENCY_CLASS
1234                            8
```

**Comment by xrotwang** [comment]
I think we just allow anything, and only enforce constraints on types, etc. when we want to tie particular program logic to the data. So in the initial collection phase that would not be the case, I think.

**Comment by LinguList** [comment]
Sounds good. As an initial start, we can just outsource both the wikipedia links and the links from omegawiki. Shall I prepare this quickly and make a PR (I have four more lists in the collection, not counting the list by Bowern)?

**Comment by xrotwang** [comment]
Yes, go ahead - I won't be able to contribute much until next week, though.

**Comment by LinguList** [comment]
allright, then I'll just take my time and probably add some more lists before I make the PR. I'll head for end of next week, including initial examples for metadata and the remaining lists I wanted to add anyway.
