### ISSUE TITLE
MAKE (734) vs DO OR MAKE (2575)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#456]
I take it that 2575 is more general, but when do/should we use which? I think they are both used mostly equally among the different lists.

**Comment by AnnikaTjuka** [comment]
I think this has been cleaned-up. I only see the [Zgraggen-1980-380-354](https://concepticon.clld.org/values/Zgraggen-1980-380-354) list which could be mapped to MAKE.

**Comment by chrzyki** [comment]
Thanks for checking. Any other opinions on the mapping in this particular list?

**Comment by chrzyki** [comment]
(Oh, and I fully agree @AnnikaTjuka - this seems like a candidate for MAKE. I'm just not an expert on this list)

**Comment by AnnikaTjuka** [comment]
After some research I found a PR where the mapping was changed from MAKE to DO OR MAKE #395 . So I'll leave it as it is.
