### ISSUE TITLE
Fireplace, oven etc.

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#504]
I think we might want to distinguish between a fireplace (i.e. a fire at the bottom of a chimney in a wall), a hearth (i.e. a place for cooking in the mid of a room), a stove (a fire or other kind of heater where things are put onto to heat them) and an oven (something into which put things to heat them). But I'm a bit at a loss which concept lists to link where, how exactly to write the definitions etc.

Currently we have
fireplace http://concepticon.clld.org/parameters/185
stove http://concepticon.clld.org/parameters/859
oven http://concepticon.clld.org/parameters/1143

**Comment by AnnikaTjuka** [comment]
For me the mappings appear consistent. So I'm not sure what could be changed here.

**Comment by Schweikhard** [comment]
It's basically about splitting FIREPLACE into two by adding HEARTH and possibly a hyperonym. The problem is that hearth is an ambiguous term, so it all might just mean FIREPLACE.

**Comment by AnnikaTjuka** [comment]
I'd leave it as it is because the two concepts are too similar and most languages might not even have a clear-cut distinction.

**Comment by Schweikhard** [comment]
I agree that it's not worth adding new concepts. It might be an idea to unmap Marrison who only writes "hearth", though.

**Comment by AnnikaTjuka** [comment]
I'd be ok with FIREPLACE being a "catch-all" category of _hearth_ and _fireplace_ glosses.

**Comment by AnnikaTjuka** [comment]
So, if we agree and no one else has a counterargument, I would suggest to close this issue.

**Comment by Schweikhard** [comment]
I might at some point change the definition of FIREPLACE around a bit to make it more clear that it's catch-all - but yes, can be closed.
