### ISSUE TITLE
Definition of "call by name"

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#505]
call by name https://concepticon.clld.org/parameters/180
includes "to utter the name of sb./sth.", "to be named x" and "to be given the name x".
A split may be in order, but this might warrant some further discussion first.

**Comment by AnnikaTjuka** [comment]
@Schweikhard Could you give a suggestions of what you'd like to change?

**Comment by Kristina-Pianykh** [comment]
Judging by the glosses mapped to CALL BY NAME, it could be divided further to refer to the act of calling someone by their name (CALL BY NAME itself) and the act of giving someone/something a name (GIVE A NAME).

E.g., the concept in Dellert-2017-1016-989 has a clearly different meaning from CALL BY NAME.  Same goes for Haspelmath-2009-1460-1177 and Borin-2015-1532-290.

**Comment by Schweikhard** [comment]
Huang's 叫(~名字) ("是") probably should be removed as it's *BE CALLED.

I think 叫 can mean CALL BY NAME, *BE CALLED and CALL, so the 叫s at CALL might be correct or might perhaps better fit a hyperonym.

**Comment by Schweikhard** [comment]
So we could make a new concept GIVE NAME for Borin, Dellert and Key/Haspelmath/List.
That would only leave Buck and Allen on CALL BY NAME.
Or does 称 (Allen) also rather mean GIVE NAME?

**Comment by Schweikhard** [comment]
@MacyL We might need some Chinese help here.

**Comment by MacyL** [comment]
I think the mapping of Chinese lists here is fine. 
Allen-2007-500 称 is CALL BY NAME
Huang-1992-1820 叫(~名字) (是) CALL BY NAME
Yang-2011-1014 叫 is also CALL BY NAME

Long answer: 
叫 could be call someone by their name or by kinship, or shout 
I checked the word forms in Huang's data and Yang's data. Both sources are recorded as /ku¹/ or alike to 叫. Shout in these two sources are /chɛ/ or similar words. 

命名 would be GIVE NAME
But I have not yet seen the Chinese glosses appear in the lists we have so far.

**Comment by LinguList** [comment]
#987 @chrzyki added `be called by name`, so we can link after this list has been added. But we can do this in 3.0.

**Comment by AnnikaTjuka** [comment]
As far as I can see, the mappings suggested by @MacyL were implemented. @LinguList Can I close this issue?

**Comment by AnnikaTjuka** [comment]
Since the suggestions were implemented, I'll close this issue now.
