### ISSUE TITLE
shout vs. shriek

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#506]
I defined SHOUT as "To utter in a loud voice." 
But it's actually not clear whether that's what's meant in all cases.
Some entries linked to SHOUT might mean instead SHRIEK, defined as "To make a very high, loud sound.", but there is no completely clear case.
And some of the entries linked to CALL might also rather fit one of the other two.

shout https://concepticon.clld.org/parameters/715
shriek https://concepticon.clld.org/parameters/298
call https://concepticon.clld.org/parameters/1084

**Comment by AnnikaTjuka** [comment]
Do you mean the ones with "cry out" should be mapped to SHRIEK ?

In case of CALL, I am not sure which could be mapped to either SHOUT or SHRIEK.

**Comment by Schweikhard** [comment]
Yes.

Of CALL, "call out" rather seems like either SHOUT or SHRIEK - or it means something different altogether.

**Comment by AnnikaTjuka** [comment]
For me, "call out" means something like "call out her name" to get somebody to the dinner table or similar. Therefore, I'd leave "call out" mapped to CALL although one might raise her voice for that purpose.

**Comment by Schweikhard** [comment]
To me, "call out" means "aufschreien" if it's used intransitively, but the elicitation glosses don't provide any information regarding that.

It seems transitively it can also mean "aufrufen" or "verlesen" (the latter being one of the two meanings Leo provides besides "herausrufen").

Cambridge has for call out (something):
"to speak loudly
to officially order that a military unit become ready for action"

And Merriam Webster provides for call out:
"1: to summon into action
call out troops
2 : to challenge to a duel
3 : to order on strike
call out the workers
4 : to publicly criticize or fault (someone) "

So, it seems really ambiguous and could be argued to fit any of the three (mostly SHOUT, though).

**Comment by AnnikaTjuka** [comment]
I get your point. But for me (from a user's perspective) it is a bit confusing if we map a gloss with a verb "call (out)" that we have as a concept CALL to another concept/verb SHOUT. 

Maybe there are conventions in Concepticon that I am not aware of and @LinguList could decide in this case.

**Comment by Schweikhard** [comment]
Therefore I would argue to unmap those two instances of "call out" as they are just too uncertain.

**Comment by AnnikaTjuka** [comment]
That would be a solution. I'd suggest you'll make a PR with the proposed changes so that the others can join the discussion.
