### ISSUE TITLE
Hays et al. 1974: Color term salience

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#510]
https://anthrosource.onlinelibrary.wiley.com/doi/full/10.1525/aa.1972.74.5.02a00050

They list a limited number of some 11 colors, so it seems easy enough to link them to Concepticon (different from the big collections with color chips).

**Comment by SimonGreenhill** [comment]
(what an interesting paper -- I was reading it so thought I'd add it!)
