### ISSUE TITLE
Dellert and Buch 2018: Metadata for concept list rankings

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#518]
* https://figshare.com/s/c9cf9057614928909d86

article

*  http://booksandjournals.brillonline.com/content/journals/10.1163/22105832-00802001

The link all of Northeuralex to concepticon, i fact, they provide a complete concepticon dump, but it's not clear which version. I suppose this is best used as metadata.

**Comment by LinguList** [comment]
A, it raises a new issue for @xrotwang: with metadata like this, we should remind ourselves that we need a reference system and a way to display metadatasets in a similar way to concept lists (also keeping our work on metadata with @chrzyki  in mind).

**Comment by LinguList** [comment]
Yes, exactly. The idea is: make them citable, but keep them distinct, as metadata is often automatically produced and larger, linking directly to concepticon concept sets, just like this dataset they publish there. @chrzyki has a large dump of potentially interesting resources, but we were too busy to work on other things to get this done, and @tresoldi is also involved. We could target this work for next year, I think, so no need to rush with it now.

**Comment by LinguList** [comment]
I just saw that there 100 best concepts qualify as well as a concept list proper.

**Comment by xrotwang** [comment]
Ah, yes that's a good addition - in particular with our "5 most-similar lists" functionality on the web site.

**Comment by AnnikaTjuka** [comment]
Not sure if we want to add this list to norare. We already have lists like the WOLD and Northeuralex linked to Concepticon. @LinguList Should I transfer it anyway?

**Comment by LinguList** [comment]
In fact, this list is easy, since it is already linked to Concepticon via Northeuralex, so one can just write a short script to link it. Even from within Norare, or we add it to concepticon and then add it to norare in the columns.

**Comment by LinguList** [comment]
[Dellert-2018-1016.tsv.zip](https://github.com/concepticon/concepticon-data/files/4785105/Dellert-2018-1016.tsv.zip)

**Comment by LinguList** [comment]
Please see the file above. I just mapped everything. If somebody else could make a PR (refining the concept mappings not needed, as they follow the Northeuralex we already have here). In the figshare, there is more information on the details of the scores.

**Comment by AnnikaTjuka** [comment]
Thanks! I'll make a PR later today.
