### ISSUE TITLE
frequency counts for different languages form Mahowald paper

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#519]
* https://osf.io/2t7v3/

Thanks to Kyle Mahowald, who shared the link (the paper doesn't list it): https://onlinelibrary.wiley.com/doi/full/10.1111/cogs.12689#

The data can be used (I hope) to assess frequency counts for different languages that we have as well in concepticon, so a meta-data search for our glossing languages.

**Comment by LinguList** [comment]
I add @tresoldi  and @chrzyki  here, as this is our idea on extending concepticon metadata.

**Comment by tresoldi** [comment]
Pinging @Schweikhard

**Comment by AnnikaTjuka** [comment]
@Schweikhard already tried to add this data set in the old norare version (see [issue](https://github.com/lingpy/norare/issues/27)) but the data doesn't list the frequencies for each language in individual columns. In addition, we couldn't figure out what s1, s2 etc. meant.
