### ISSUE TITLE
Brysbaert's norm data for the number of words a person knows and acquires during life time

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#521]
Appeared online (didn't check before): http://crr.ugent.be/archives/1915

**Comment by AnnikaTjuka** [comment]
This issue seems to be connected with #321.

**Comment by LinguList** [comment]
Yes, I closed the other issue. We may also close this one.

**Comment by LinguList** [comment]
But let us leave it open for now: with the new approach/policy of automatically adding big concept set meta datasets, as described in a first simple version [here](https://calc.hypotheses.org/2250), we could do them in a rush and also cross them off the list.

**Comment by AnnikaTjuka** [comment]
I think some of the data is already included in Brysbaert (2014). So if we map this list automatically and include it in concepticon data we will partially resolve this issue. I'll test the automated mapping procedure today to see if it works.
