### ISSUE TITLE
Repository of neurolinguistic works -- potential source for new concept lists

### ISSUE THREAD

**Issue by tresoldi** [concepticon/concepticon-data#542]
Neurosynth.org is an "official as it gets" directory of neurolinguistic works, also allowing some rudimentary and automatic meta-analysis. The list of works on lexical topics would be particularly interesting for us: http://neurosynth.org/analyses/terms/lexical/ 

It is worth checking and making sure that interesting concept lists are added as individual issues here (some are already in line). Of particular relevance is the work by Huth et al. (2012; 2016), whose concepts seem to be always linked to WordNet and whose brain atlases were featured on Nature:

- http://gallantlab.org/brainviewer/huthetal2012/
- http://gallantlab.org/huth2016/

**Comment by AnnikaTjuka** [comment]
@tresoldi I had a quick look at the websites. The studies in the category "lexical" seem to include sentence reading studies and lexical studies. I am not sure how we could link the activation profiles to specific concepts in Concepticon. From what I know, neurolinguistic studies group, for example, a bunch of words like {_tree_, _car_, _house_} into the category `concrete objects` and compare the activation with another category like `abstract objects` which comprises the words {_idea_, _decision_, _education_}.  The Huth studies, on the other hand, seem to use movies that include 'concepts' but in this case, they probably refer to 'concepts' as "nonlinguistic psychological representation of a class of entities in the world" Murphy (2002). 

I could give it a more thorough look if there is something specific you'd like to add and transfer the issue to norare.

**Comment by tresoldi** [comment]
The issue was opened because the repository was mentioned as great and much used source of neurolinguistic data for a work I was reviewing. I remember looking at it and considering it something potentially useful, also because at the time there was some discussion going on about looking into potential neurolinguistic bases for colexifications.

I was opened before norare was a thing in our group, if I recall (or, at least, it was not in my radar), but transferring it makes sense to me. It is unlikely that any unmapped concept would need to be included in Concepticon, I suppose, but I'd really delegate it to the core Concepticon team. :smiley:

**Comment by AnnikaTjuka** [comment]
Thanks for the explanation, @tresoldi ! I'm still a bit hesitant to simply transfer the issue because I have no idea how feasible it is to add the data in norare. And it might end up as a "sleeping" issue. Would you mind sending me the article where the resource is mentioned? Maybe they give examples of how it is used.

**Comment by tresoldi** [comment]
On how feasible, I guess it is up to @LinguList ... On the article, it hasn't been published yet and it was a blind review, sorry.
