### ISSUE TITLE
SPIRIT/GHOST/SOUL

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#551]
The concept SPIRIT contains several different meanings that should be rather linked to GHOST, SOUL or DEITY. In 2 cases, even two entries of the same concept list are linked to it.

Currently its definition is very close to that of SOUL. It could be instead used for disembodied beings that are not dead humans/ghosts but are also not deities, or for a more specific concept as in Buck's "spirit (guardian spirit)".

I don't know what concept Marrison refers to, though.
And I think Pallas refers to SOUL, but I'm not certain.

**Comment by LinguList** [comment]
What does marrison give as elicitation gloss?

**Comment by Schweikhard** [comment]
spirit.

**Comment by LinguList** [comment]
I think it's "ghost".

**Comment by Schweikhard** [comment]
I asked Yunfan, and he said in Marrison's Burmish data it seems to be used in the meaning of DEITY (albeit possibly rather spiritual entity less powerful than a deity).
So I suppose in the Ao Naga Marrison uses that elicitation for the same concept.

**Comment by Schweikhard** [comment]
Updated most linked to SPIRIT.
Дух can mean either SOUL or SPIRIT I suppose?
And is an ancestor spirit a GHOST or a SPIRIT, or neither?
I'm also struggling with the definition of SPIRIT - is a GHOST a kind of spirit or not?

Also, only one of the Marrison lists is in the folder, where do I find the other one?
