### ISSUE TITLE
COUNT

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#554]
By the current definition ("To enumerate the digits of one's numeral system."), COUNT only refers to 'enumerate', not to 'determine the number of'.
I would repurpose this entry as a hyperonym of the two meanings and move those lists which specify the meaning to new hyponyms COUNT (ENUMERATE) and COUNT (AMOUNT) and add another new hyperonym CALCULATE OR COUNT to account for Bulakh.

However, I am not certain about the Chinese lists linked to it. Their elicitation gloss is 数, or, for Sun1991, 数(东西).

**Comment by LinguList** [comment]
Just looked at this one: are there ANY cases where you think a list distinguishes both versions of COUNT you propose? If not: expand the definition. Chinese shǔ is as ambiguous as German "zählen", so I think we can live with this uncertainty by simply expanding the definition to include "determine the amount of"

**Comment by Schweikhard** [comment]
I don't think there is any that has both as separate concepts in one list.
Some lists have definitions or similar that point to one of the meanings (e.g. Haspelmath: 'count objects in a set in order to determine the total'), but for most we can't even tell which is intended, let alone which was actually elicited, considering that counting the amount may involve enumerating the numbers and vice versa.

So I agree that a change to the concept definition should suffice.
