### ISSUE TITLE
CHOP, BRING DOWN, FELL (A TREE)

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#555]
I've done some corrections to CHOP and related concepts.
Its definition is now "To chop wood, or to chop meat, vegetables etc. into small pieces."
Therefore it's a hyperonym to CUT (WITH AXE) and CHOP (INTO PIECES) as that fits best the Borin/Haspelmath/Key/List-cluster, and almost all other entries have been moved to existing concepts.

I don't know where to move Kraft's entry for chop, though, as its Hausa form seems to mean CUT (WITH AXE) or FELL (A TREE) but I'm reluctant to add a new concept based on a single list entry in a language I don't speak.
(You can see its range of meanings by typing sara into http://bargeryhausa.gotdns.com/frame.html)
Should I change it to unlinked? Or do we have someone here familiar with Hausa?

Also, the difference between BRING DOWN and FELL (A TREE) seems not entirely clear to me:
https://concepticon.clld.org/parameters/355
https://concepticon.clld.org/parameters/463

**Comment by LinguList** [comment]
then go for cut with axe for Kraft, ignore "fell a tree".

**Comment by LinguList** [comment]
Cut down could be identical with "fell a tree". I think "fell" is less common in English now. Marrison' has a merger here, this should also be checked. Don't we have Chinese entries for Marrison, @MacyL ?

**Comment by Schweikhard** [comment]
Is there a merger in Marrison? It's twice on FELL (A TREE) because those are different concept lists by Marrison (albeit only one of them is in concepticon-data), and it's not on CUT DOWN.

**Comment by tresoldi** [comment]
I am in favor of merging FEEL (A TREE) and BRING DOWN.

CUT (WITH AXE) could maybe be renamed CUT (HEW), in order to be less culture-specific (e.g., when the original glosses don't use "axe", but a word for some variety of axe) and to focus on the action and not the instrument.
