### ISSUE TITLE
RIVER

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#567]
There is a new concept FLOWING BODY OF WATER, which is a hyperonym to RIVER (large river) and STREAM (small river).
Some lists linked to RIVER may need to be moved to the hyperonym.
https://concepticon.clld.org/parameters/666

**Comment by AnnikaTjuka** [comment]
So for example, Buck-1949-1108-18 "brook; river; stream" would be mapped to FLOWING BODY OF WATER and all the others with only "river" stay mapped to RIVER. Sounds good to me.
