### ISSUE TITLE
HOW MUCH

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#569]
We have currently both HOW MANY and HOW MUCH.
https://concepticon.clld.org/parameters/822
https://concepticon.clld.org/parameters/531
The latter seems redundant. Most of what is linked to it better fits MUCH, the rest could be linked to HOW MANY, except for Haspelmath/Key/List which differentiate between the two. I would therefore unlink those 3 from HOW MUCH, move the others to the appropriate concepts, and mark HOW MUCH as discontinued.

**Comment by AnnikaTjuka** [comment]
So you would only link the ones with a question mark to HOW MANY ?
I'd suggest to map HOW MUCH lists to HOW MANY because there are already lists with "how much" or "how many/much" linked to this concept.

**Comment by Schweikhard** [comment]
(Note to self: I should close solved issues)
I changed my mind on that and fixed that a while ago by turning HOW MANY into the hyperonym and adding a hyponym HOW MANY PIECES for when it clearly does not mean HOW MUCH.
