### ISSUE TITLE
Issues with typos, IDs, and mapping in Pallas 1786 and 1789

### ISSUE THREAD

**Issue by natalia-morozova** [concepticon/concepticon-data#603]
There are some issues with the lists by Pallas. I have a few things to report.

1. Pallas 1786 441

- IDs in Pallas 1786 441 start with [Pallas-441-2](https://concepticon.clld.org/values/Pallas-1786-441-2) instead of **Pallas-441-1**, thus, the last ID is [Pallas-441-442](https://concepticon.clld.org/values/Pallas-1786-441-442) instead of 441.

- Some entries were mixed up in the process of digitalization in [Pallas 1786 441](https://concepticon.clld.org/contributions/Pallas-1786-441), thus one Russian gloss **Ѣшь** is missing. Here is how it looks like on Concepticon:

|  ID | FRENCH | LATIN |RUSSIAN | GERMAN|
| ------- | ------- | ------- |------- |------- |
| [Pallas-1786-441-111](https://concepticon.clld.org/values/Pallas-1786-441-111) | Tu mange | Edis | ѣмъ | Ißßeßt |
| [Pallas-1786-441-112](https://concepticon.clld.org/values/Pallas-1786-441-112) | Il mange | Edit | Ѣсть | Ißßet |

And this is how it is in the [source provided for the list](https://cdstar.shh.mpg.de/bitstreams/EAEA0-788B-3A7A-F5BD-0/Pallas1786.pdf) (page 4, towards the end of the left column):

| ID | FRENCH | LATIN |RUSSIAN | GERMAN|
| ------- | ------- | ------- | ------- |------- |
| Pallas-1786-441-111 | Je mange | Edo | ѣмъ | Eßßen |
| Pallas-1786-441-112 | Tu mange | Edis | Ѣшь | Ißßeßt |
| Pallas-1786-441-113(?) | Il mange | Edit | Ѣсть | Ißßet |

If the corrections are accepted, all following IDs should be changed correspondingly. 

- I have also noticed some mapping errors:

| ID | ENGLISH GLOSS | CONCEPT SET | CORRECTED |
| ------ | ------ | ------ | ------ |
| [Pallas-1786-441-38](https://concepticon.clld.org/values/Pallas-1786-441-38) | nail (noun) | [502 NAIL (TOOL)](https://concepticon.clld.org/parameters/502) | [1896 FINGERNAIL OR TOENAIL](https://concepticon.clld.org/parameters/1896) |
| [Pallas-1786-441-82](https://concepticon.clld.org/values/Pallas-1786-441-82) | sleep (noun) | [1585 SLEEP](https://concepticon.clld.org/parameters/1585) | [2972 SLEEP (STATE)](https://concepticon.clld.org/parameters/2972) |
| [Pallas-1786-441-196](https://concepticon.clld.org/values/Pallas-1786-441-196) | flash (noun) | [2377 FLASH (VERB)](https://concepticon.clld.org/parameters/2377) | [1654 LIGHTNING](https://concepticon.clld.org/parameters/1654) |
| [Pallas-1786-441-277](https://concepticon.clld.org/values/Pallas-1786-441-277) | to sow (verb) | [1351 SOW (FEMALE PIG)](https://concepticon.clld.org/parameters/1351) | [748 SOW SEEDS](https://concepticon.clld.org/parameters/748) |

- Finally, I checked the spelling in the [source](https://cdstar.shh.mpg.de/bitstreams/EAEA0-788B-3A7A-F5BD-0/Pallas1786.pdf) and found a few typos on Concepticon:

Russian typos:

| ID | RUSSIAN | IN SOURCE | ENGLISH GLOSS |
| ------------- | ------------- | ------------- | ------------- |
| [Pallas-1786-441-59](https://concepticon.clld.org/values/Pallas-1786-441-59) | Горовить | Говорить | to speak |
| [Pallas-1786-441-68](https://concepticon.clld.org/values/Pallas-1786-441-68) | Смѣаться | Смѣяться | to laugh (verb) |
| [Pallas-1786-441-106](https://concepticon.clld.org/values/Pallas-1786-441-106) | Есъми | Есми | we are (verb) |
| [Pallas-1786-441-109](https://concepticon.clld.org/values/Pallas-1786-441-109) | Былъ | Былъ, Бѣ | was (verb) |
| [Pallas-1786-441-150](https://concepticon.clld.org/values/Pallas-1786-441-150) | Зсравъ | Здравъ | healthy (adjective) |
| [Pallas-1786-441-151](https://concepticon.clld.org/values/Pallas-1786-441-151) | Хорошо | Хорошо, добро | good (adjective) |
| [Pallas-1786-441-185](https://concepticon.clld.org/values/Pallas-1786-441-185) | Лучь | Лучъ | beam (noun) |
| [Pallas-1786-441-188](https://concepticon.clld.org/values/Pallas-1786-441-188) | Вѣть | Вѣять | blow (of wind, noun) |
| [Pallas-1786-441-196](https://concepticon.clld.org/values/Pallas-1786-441-196) | Молнiя | Мольнïя | flash (noun) |
| [Pallas-1786-441-208](https://concepticon.clld.org/values/Pallas-1786-441-208) | Вечеръ | Вечерь | evening (noun) |
| [Pallas-1786-441-218](https://concepticon.clld.org/values/Pallas-1786-441-218) | Семдица | Седмица | week (noun) |
| [Pallas-1786-441-271](https://concepticon.clld.org/values/Pallas-1786-441-271) | Орѣьъ | Орѣхъ | nut (noun) |
| [Pallas-1786-441-279](https://concepticon.clld.org/values/Pallas-1786-441-279) | Жыто | Жито | crop (noun) |
| [Pallas-1786-441-341](https://concepticon.clld.org/values/Pallas-1786-441-341) | Дверъ | Дверь | door (noun) |
| [Pallas-1786-441-365](https://concepticon.clld.org/values/Pallas-1786-441-365) | Поясь | Поясъ | belt (noun) |
| [Pallas-1786-441-391](https://concepticon.clld.org/values/Pallas-1786-441-391) | Госпдинъ | Господинъ | sir (noun) |
| [Pallas-1786-441-440](https://concepticon.clld.org/values/Pallas-1786-441-440) | Трицать | Тритцать | thirty (numeral) |

Latin typos:

| ID | LATIN | IN SOURCE | ENGLISH GLOSS |
| ------------- | ------------- | ------------- | ------------- |
| [Pallas-1786-441-114](https://concepticon.clld.org/values/Pallas-1786-441-114) | Nutrure | Nutrire | to feed (verb) |
| [Pallas-1786-441-192](https://concepticon.clld.org/values/Pallas-1786-441-192) | Plubia | Pluvia | rain (noun) |
| [Pallas-1786-441-204](https://concepticon.clld.org/values/Pallas-1786-441-204) | Tenbrißus | Tenebroßus | dark (adjective) |
| [Pallas-1786-441-238](https://concepticon.clld.org/values/Pallas-1786-441-238) | Altitido | Altitudo | height, altitude (noun) |
| [Pallas-1786-441-333](https://concepticon.clld.org/values/Pallas-1786-441-333) | Aratum | Aratrum | plough (noun) |
| [Pallas-1786-441-334](https://concepticon.clld.org/values/Pallas-1786-441-334) | Aratum | Aratrum | plough (noun) |
| [Pallas-1786-441-352](https://concepticon.clld.org/values/Pallas-1786-441-352) | Dcadus | Cadus | barrel (noun) |
| [Pallas-1786-441-357](https://concepticon.clld.org/values/Pallas-1786-441-357) | vehi | Vehi | to drive (in a vehicle, verb) |
| [Pallas-1786-441-366](https://concepticon.clld.org/values/Pallas-1786-441-366) | Seridum | Sericum | silk (noun) |
| [Pallas-1786-441-373](https://concepticon.clld.org/values/Pallas-1786-441-373) | Cervißia | Cerevißia | beer (noun) |
| [Pallas-1786-441-390](https://concepticon.clld.org/values/Pallas-1786-441-390) | Inimucus | Inimicus | enemy (noun) |

French typos:

| ID | FRENCH | IN SOURCE | ENGLISH GLOSS |
| ------------- | ------------- | ------------- | ------------- |
| [Pallas-1786-441-161](https://concepticon.clld.org/values/Pallas-1786-441-161) | Coule | Boule | ball (noun) |
| [Pallas-1786-441-182](https://concepticon.clld.org/values/Pallas-1786-441-182) | Brouillar | Brouillard | fog (noun) |
| [Pallas-1786-441-231](https://concepticon.clld.org/values/Pallas-1786-441-231) | Pußière | Poußière | dust (noun) |
| [Pallas-1786-441-338](https://concepticon.clld.org/values/Pallas-1786-441-338) | Maison | Mai[f]on - shouldn't be Maißon? | house (noun) |
| [Pallas-1786-441-341](https://concepticon.clld.org/values/Pallas-1786-441-341) | Porter| Porta | door (noun) |
| [Pallas-1786-441-391](https://concepticon.clld.org/values/Pallas-1786-441-391) | Seigner | Seigneur | sir (noun) |
| [Pallas-1786-441-426](https://concepticon.clld.org/values/Pallas-1786-441-426) | Enemi | En | in (preposition) |
| [Pallas-1786-441-434](https://concepticon.clld.org/values/Pallas-1786-441-434) | Septentrion | Sept | seven (numeral) |

German typos:

| ID | GERMAN | IN SOURCE | ENGLISH GLOSS |
| ------------- | ------------- | ------------- | ------------- |
| [Pallas-1786-441-60](https://concepticon.clld.org/values/Pallas-1786-441-60) | Reden | Rede | talk (noun) |
| [Pallas-1786-441-82](https://concepticon.clld.org/values/Pallas-1786-441-82) | Schlafen | Schlaf | sleep (noun) |
| [Pallas-1786-441-213](https://concepticon.clld.org/values/Pallas-1786-441-213) | Somer | Sommer | summer (noun) |
| [Pallas-1786-441-326](https://concepticon.clld.org/values/Pallas-1786-441-326) | Serling | Sperling | sparrow (noun) |
| [Pallas-1786-441-404](https://concepticon.clld.org/values/Pallas-1786-441-404) | Ozt | Izt | now (adverb) |

2. [Pallas 1789 285](https://concepticon.clld.org/contributions/Pallas-1789-285)

- Here I noticed some typos, they mainly occurred in Russian (perhaps, due to copying the data from the first list) and one typo in Latin. The spelling of several words was changed in Pallas 1789 285:

| ID | RUSSIAN | IN SOURCE | ENGLISH GLOSS |
| ------------- | ------------- | ------------- |------------- |
| [Pallas-1789-285-16](https://concepticon.clld.org/values/Pallas-1789-285-16) | Глава | Голова | head (noun) |
| [Pallas-1789-285-20](https://concepticon.clld.org/values/Pallas-1789-285-20) | Око | Глазъ | eye (noun) |
| [Pallas-1789-285-27](https://concepticon.clld.org/values/Pallas-1789-285-27) | Кость | Ротъ | bone (noun) - should be mouth (noun), the same entry already exists [Pallas-1789-285-44](https://concepticon.clld.org/values/Pallas-1789-285-44) |
| [Pallas-1789-285-30](https://concepticon.clld.org/values/Pallas-1789-285-30) | ѣзыкъ | Языкъ | tongue (noun) |
| [Pallas-1789-285-31](https://concepticon.clld.org/values/Pallas-1789-285-31) | Брада | Борода | beard (noun) |
| [Pallas-1789-285-36](https://concepticon.clld.org/values/Pallas-1789-285-36) | Палцы | Пальцы | finger (noun) |
| [Pallas-1789-285-41](https://concepticon.clld.org/values/Pallas-1789-285-41) | Колено | Колѣно | knee (noun) |
| [Pallas-1789-285-62](https://concepticon.clld.org/values/Pallas-1789-285-62) | Труд | Трудъ | labor, work (noun) |
| [Pallas-1789-285-69](https://concepticon.clld.org/values/Pallas-1789-285-69) | Рость | Ростъ | height, size (noun) |
| [Pallas-1789-285-73](https://concepticon.clld.org/values/Pallas-1789-285-73) | Круг | Кругъ | circle (noun) |
| [Pallas-1789-285-79](https://concepticon.clld.org/values/Pallas-1789-285-79) | Вѣтрь | Вѣтръ | wind (noun) |
| [Pallas-1789-285-84](https://concepticon.clld.org/values/Pallas-1789-285-84) | Молнiя | Молнïя | flash (noun) |
| [Pallas-1789-285-85](https://concepticon.clld.org/values/Pallas-1789-285-85) | Снѣгъ | Снегъ | snow (noun) |
| [Pallas-1789-285-86](https://concepticon.clld.org/values/Pallas-1789-285-86) | Лед | Ледъ | ice (noun) |
| [Pallas-1789-285-95](https://concepticon.clld.org/values/Pallas-1789-285-95) | Гоъ | Годъ | year (noun) |
| [Pallas-1789-285-118](https://concepticon.clld.org/values/Pallas-1789-285-118) | Дира | Дыра | hole (noun) |
| [Pallas-1789-285-119](https://concepticon.clld.org/values/Pallas-1789-285-119) | ѣма | Яма | pit, large hole (noun) |
| [Pallas-1789-285-123](https://concepticon.clld.org/values/Pallas-1789-285-123) | Сребро | Серебро | silver (noun) |
| [Pallas-1789-285-128](https://concepticon.clld.org/values/Pallas-1789-285-128) | Древо | Дерево | tree (noun) |
| [Pallas-1789-285-134](https://concepticon.clld.org/values/Pallas-1789-285-134) | Плодъ | Плоды | fruit (noun) |
| [Pallas-1789-285-140](https://concepticon.clld.org/values/Pallas-1789-285-140) | Жыто | Жито | crop (noun) |
| [Pallas-1789-285-154](https://concepticon.clld.org/values/Pallas-1789-285-154) | Собака,Пѣсь | Собака | dog (noun) |
| [Pallas-1789-285-160](https://concepticon.clld.org/values/Pallas-1789-285-160) | ѣицо | Яицо | egg (noun) |
| [Pallas-1789-285-169](https://concepticon.clld.org/values/Pallas-1789-285-169) | Дверъ | Дверь | door (noun) |
| [Pallas-1789-285-175](https://concepticon.clld.org/values/Pallas-1789-285-175) | Топор | Топоръ | axe (noun) |
| [Pallas-1789-285-176](https://concepticon.clld.org/values/Pallas-1789-285-176) | Поясь | Поясъ | belt (noun) |
| [Pallas-1789-285-177](https://concepticon.clld.org/values/Pallas-1789-285-177) | Гвосдъ | Гвоздь | nail (tool, noun) |
| [Pallas-1789-285-178](https://concepticon.clld.org/values/Pallas-1789-285-178) | cectura (Latin) | vectura | vehicle (noun) |
| [Pallas-1789-285-181](https://concepticon.clld.org/values/Pallas-1789-285-181) | Ѣств | Яствы | food (noun) |
| [Pallas-1789-285-203](https://concepticon.clld.org/values/Pallas-1789-285-203) | Зсравъ | Здравъ | healthy (adjective) |
| [Pallas-1789-285-210](https://concepticon.clld.org/values/Pallas-1789-285-210) | Краско | Красно | red (adjective) |
| [Pallas-1789-285-215](https://concepticon.clld.org/values/Pallas-1789-285-215) | Толсто | Толстъ | fat (adjective) |
| [Pallas-1789-285-227](https://concepticon.clld.org/values/Pallas-1789-285-227) | ѣстй | Ясти | to eat (verb) |
| [Pallas-1789-285-230](https://concepticon.clld.org/values/Pallas-1789-285-230) | Битъ | Бить | to beat (verb) |
| [Pallas-1789-285-247](https://concepticon.clld.org/values/Pallas-1789-285-247) | ѣ | Я | I (p) |
| [Pallas-1789-285-254](https://concepticon.clld.org/values/Pallas-1789-285-254) | Им | Имъ | them (dative case, pronoun) |

- Same issue with the same glosses being mapped incorrectly:

| ID | ENGLISH GLOSS | CONCEPT SET | CORRECTED |
|------ |------ |------ |------ |
| [Pallas-1789-285-37](https://concepticon.clld.org/values/Pallas-1789-285-37) | nail (noun) | [502 NAIL (TOOL)](https://concepticon.clld.org/parameters/502) | [1896 FINGERNAIL OR TOENAIL](https://concepticon.clld.org/parameters/1896) |
| [Pallas-1789-285-59](https://concepticon.clld.org/values/Pallas-1789-285-59) | sleep (noun) | [1585 SLEEP](https://concepticon.clld.org/parameters/1585) | [2972 SLEEP (STATE)](https://concepticon.clld.org/parameters/2972) |
| [Pallas-1789-285-84](https://concepticon.clld.org/values/Pallas-1789-285-84) | flash (noun) | [2377 FLASH (VERB)](https://concepticon.clld.org/parameters/2377) | [1654 LIGHTNING](https://concepticon.clld.org/parameters/1654) |
| [Pallas-1789-285-238](https://concepticon.clld.org/values/Pallas-1789-285-238) |  to sow (verb) | [1351 SOW (FEMALE PIG)](https://concepticon.clld.org/parameters/1351) | [748 SOW SEEDS](https://concepticon.clld.org/parameters/748) |

**Comment by LinguList** [comment]
Nice catch. The data was typed by me in a rush, and it is possible I did not check it more thoroughly later. Can you make a PR correcting for these cases?

**Comment by natalia-morozova** [comment]
Sure, will be done soon!
