### ISSUE TITLE
MUSE norm data for bilingual dictionaries for 110 languages

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#606]
https://github.com/facebookresearch/MUSE#ground-truth-bilingual-dictionaries

These are potentially interesting, as we could try to expand our concepticon norm data, or use them for the norm data studies.

**Comment by AnnikaTjuka** [comment]
This is an interesting compilation of dictionaries. However, I'm not sure if it is beneficial for researchers using NoRaRe. We argue in the paper that the cross-linguistic comparison is made possible by the mapping to Concepticon. 
But maybe I'm missing something here, @LinguList ?

**Comment by LinguList** [comment]
You are right, now that I think about it. The data are interesting, but not specifically for Concepticon.
