### ISSUE TITLE
concept KNOW

### ISSUE THREAD

**Issue by Alexei-Kassian** [concepticon/concepticon-data#607]
Concepticon has three neighboring concepts:
- KNOW (SOMETHING) [https://concepticon.clld.org/parameters/1410
](https://concepticon.clld.org/parameters/1410)
- KNOW OR BE ABLE [https://concepticon.clld.org/parameters/2238](https://concepticon.clld.org/parameters/2238)
- KNOW (SOMEBODY) [https://concepticon.clld.org/parameters/2248](https://concepticon.clld.org/parameters/2248)

My personal and general GLD's experience, however, suggests that the most common lexical opposition in the world's languages is KNOW THAT (I know that he came) vs. KNOW OR BE ACQUAINTED WITH SOMETHING (I know this song). Particularly this is the case of some IE languages: German wissen / kennen, French savoir / connaître, Old Russian vedeti / znati.

Currently, both "my" KNOW-s are merged in Concepticon's KNOW (SOMETHING), whereas two residual Concepticon's entries reflect relatively marginal cases of lexical oppositions.

What do you think about this?

Best
Alexei

**Comment by LinguList** [comment]
Where do we find "your" knows? Is it one of the lists we already have in concepticon, or not?

**Comment by Alexei-Kassian** [comment]
This lexical opposition between KNOW THAT vs. KNOW OR BE ACQUAINTED WITH SOMETHING is mentioned as the most common one in [Kassian 2010 116](https://concepticon.clld.org/contributions/Kassian-2010-116). Specifications in Kassian 2010 116 require KNOW THAT as a Swadesh item, whereas KNOW OR BE ACQUAINTED WITH SOMETHING and other related KNOW-words are recommended to be noted in comments.
