### ISSUE TITLE
Uni Melbourne RUIL Australian '50 Words' project

### ISSUE THREAD

**Issue by DavidNash1** [concepticon/concepticon-data#608]
See http://50words.online/, under construction; as announced in April at http://www.paradisec.org.au/blog/2019/04/50-words-of-australian-languages-project/ There are 7 languages represented so far. The standard 'wordlist' (concept list) used is linked from https://go.coedl.net/50WordsProject

**Comment by xrotwang** [comment]
Just to note this somewhere: It's actually a list of 57 concepts.
