### ISSUE TITLE
HTML entity quotes

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#611]
We've got a lot of HTML entity like `&quot;` in the conceptlist master, e.g. https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists.tsv#L143. They appear to have been added (probably due to LibreOffice/Excel behaviour?) throughout a couple of PRs in the past. Do we keep them or do we clean that up?

**Comment by LinguList** [comment]
you can clean it up, but we had different problems, as this list was at times using " as a cell separator, so one had to actually unquote it, etc., so it is probably advisable to replace it by «» or similar, not directly ".

**Comment by chrzyki** [comment]
Thanks, will think about a good solution for this.
