### ISSUE TITLE
Special characters in Bowern-2011-204 glosses

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#614]
In https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Bowern-2011-204.tsv there are multiple glosses preceded with either `*` or `$` - does this have any special meaning?

Unlike for other lists (e.g. https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Gregersen-1976-217.tsv and https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Tryon-1983-200.tsv) I couldn't find any verbal description for what this might mean.

**Comment by natalia-morozova** [comment]
I just had a look at the source document. The asterisked entries are from Swadesh-1955-100, and the ones marked with $ are from Swadesh-1952-200.

**Comment by chrzyki** [comment]
Thanks! That should be added then to the description as well I think?

On 21 Jun 2019 14:53, natalia-morozova <notifications@github.com> wrote:

I just had a look at the source document. The asterisked entries are from Swadesh-1955-100, and the ones marked with $ are from Swadesh-1952-200.

**Comment by LinguList** [comment]
Yes, this could be done. I was probably too lazy to indicate it when preparing the document.

**Comment by natalia-morozova** [comment]
I can take care of it.
