### ISSUE TITLE
Overlapping between concepts

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#618]
This issue has already been touched upon in #501. Specifically, I found out that the definitions of [DECEIVE 3230](https://concepticon.clld.org/parameters/3230) and [BETRAY 1902](https://concepticon.clld.org/parameters/1902) are completely identical:

> To cause someone to believe an untruth; to practice trickery or fraud.

I would suggest we distinguish them since _betray_ is more associated with violation of trust (and thus has to do with relationships) whereas _deceive_ is related to misleading and disinforming.

Here I'd also like to note that the _deceive,cheat_ concept in [Allen 2007 500](https://concepticon.clld.org/contributions/Allen-2007-500) is mapped to BETRAY while DECEIVE is obviously better here.

**Comment by LinguList** [comment]
Yes, this seems correct. Could you suggest definitions for both? YOu may look at sources like collings dictionary online, which was recommended to us?

This will require to re-check all concept mappings involving the two. In cases where Chinese glosses are available, these should also be checked along. You could ask @MacyL for help here.

**Comment by Kristina-Pianykh** [comment]
My suggestion would be:

Betray – to harm someone or hurt their feelings by violating their trust or being disloyal to them

Deceive – to trick someone by making them believe something that is not true or by acting in a dishonest way, usually in order to take advantage of it
