### ISSUE TITLE
fix vs. repair

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#621]
fix and repair are badly resolved for now. We can follow the idea of distinguishing "fix (a cloth)" vs. fix (a bike), as some languages distinguish those. (German: flicken vs. reparieren)

**Comment by Schweikhard** [comment]
Would the "fix a bike" also contain patching a pot, as in Huang's 补(~锅)?

I'd propose to retire FIX (as it's not a prototypical way of expressing either meaning) and to add a new concept REPAIR CLOTH or similar.

Btw, I would use "flicken" for both cloth and bike - but in the latter case mainly for repairing the wheel.

**Comment by LinguList** [comment]
difficult, and language-specific, but if we say: we start from two basic concepts: flicken und reparieren, with their German definitions, we could just impose them on the data, and later, you would find interesting colexifications. FIX could be a meta-concept.

**Comment by Schweikhard** [comment]
Good idea, just, I took a closer look at it, and Huang differentiates between patching clothes and tinkering a pot. And Hale73 has both to mend and to patch in the food and clothing section, and therefore distinguishes repairing clothes with a patch and by other means.

Suggestion:
MEND for 补(衣) fixing clothes
REPAIR for fixing other stuff
FIX as (possibly empty) hyperonym.

Fixing pots unlinked for the time being.
Hale's patch unlinked for the time being.
