### ISSUE TITLE
Missing concept label in Bodt-2019-664

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#628]
There's a basically empty entry in this list:
https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Bodt-2019-664.tsv#L97

Do we want to keep it like this?

**Comment by LinguList** [comment]
Yes. Tim will have to figure out later what that was. And the list was published in this form, so we should stay true with that, right?

**Comment by xrotwang** [comment]
ok
