### ISSUE TITLE
New potential concept-relations

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#631]
As has recently been brought up, it might be worthwhile to discuss whether we want to include any new concept-relations, and which ones those would be.

The main benefits I see in these concept relations are
* making the database more easy to use as one then sees more clearly which similar concepts are there besides the concept one is looking at, facilitating the mapping of new concept lists and the correction of old mappings as well as working with the database in general, and
* having a semantic layer on top of it, which one could apply to the data that the concept lists linked include, to use for semantic studies. The concept relations would need to be checked thoroughly for reliability (and best also for completeness) for that purpose, though. 

I would propose the following 3 broad sub-categories for what is currently being handled mainly by 'narrower', and in a few cases instead by 'instanceof', 'haspart', and 'broader':

* hyperonym/hyponym
* synecdoche (part/whole)
* elicitation-specific relationships

The hyponym category could be further split into whether there is zero overlap between cohyponyms (as e.g. in the different species of animal - something is either one species or another), or whether there is (potential) overlap (e.g. the hyponyms of CHILD - someone can both be a minor and someone's child). But that might overcomplicate things, especially since one hyperonym could have hyponyms that relate to each other differently (e.g. the hyperonyms of https://concepticon.clld.org/parameters/962).

The synecdoche differs from the hyponymy by the following definition: If the narrower concept can also be referred to by terms of the broader concept, it is hyponymy, otherwise it is synecdoche. Example: A DOG is a WOLF-LIKE ANIMAL, but WOOD is not a TREE, and a HAND is not an ARM OR HAND.

The elicitation-specific relationships would include the following kinds of things:

* somehow semantically related concepts included in the same elicitation gloss, often of different parts of speech (DIE OR BE DEAD), or being both the whole and a part thereof (TREE OR WOOD) or presumably assumed by the list's author to be colexified in the investigated languages anyway (BREAST OR MILK, 'dragon, thunder, lightning')
* homophony where we cannot tell which of two meanings is meant and therefore make a category for both (e.g. BRAID (VERB) OR WEAVE (BASKET))

In both these cases it is often not entirely clear whether those are not actually cases of hyponymy as it is culture-specific what one considers to belong to the same category.
* as a special case of the previous e.g. HIDE with its reflexive and transitive hyponyms HIDE (CONCEAL) and HIDE (ONESELF))

Related to the last example we also have the concept relation 'transitiveof' (transitive, intransitive/reflexive).
Besides that, also 'passiveof' could possibly be added.

'oppositeof' might also be an idea to consider.

I would tend to argue for discontinuing 'requires', 'resultsin', and 'producedby'.

The only other kinds I think we have would be 'similar' (for almost-synonyms - should probably be checked for accuracy and some actual full synonyms be removed) and 'hasform' (for subject case vs. oblique case in pronouns).

In general these questions might be answerable by checking how well these kinds of categorizations work on concepts in the database (perhaps only those already in conceptrelations.tsv as a test-case) and base on that which concept relations make sense to include and which don't.

**Comment by LinguList** [comment]
Yes, this looks like it can be done. When adding parts, it is just important to leave the current broader-narrower thing inside. But you will also find in the concepticon-data package a list of relations, that we have pre-defined. I would suggsest that you start by adding them to our metadata json file, similar to our tags, with a definition for each. When adding them later, this should not really make a difference, the code should still pass, but it is not clear if the relations will be shown. But by fixing them now first in prose, it is already a first step. Look at the json file in `concepticon-data/concepticondata/concepticon.json`, where i suppose to add a key `"CONCEPTRELATIONS"` or `"RELATIONS"`, which should be similar to `"TAGS"`, i.e.: the tag, plus a short definition.

Or you even go by adding "inverseof":

```
{
  "RELATIONS": [
    "broader": {
      "definition": "Broader than x.",
      "inverseof": "narrower"
      },
    "narrower": {
    ....
```

Do the others agree? @xrotwang, @chrzyki ?

**Comment by Schweikhard** [comment]
I edited the json file accordingly and pushed it to my fork:
https://github.com/Schweikhard/concepticon-data-1/blob/master/concepticondata/concepticon.json
There seems to be some mistake, though, because Github marks it as wrong and because concepticon test says
"ERROR:conceptlists.tsv:1: Expecting ',' delimiter: line 245 column 5 (char 6581)" for all 251 rows.
Not sure what I'm overlooking.

**Comment by LinguList** [comment]
https://github.com/concepticon/concepticon-data/issues/631?email_source=notifications&email_token=AAWH64UOZGESJLN4EDC2LJ3QCBMNDA5CNFSM4IHTIJQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3ELAFQ#issuecomment-516468758

remove the final commas, in Python, you can do that, but this is not a valid json format.

so instead of
```

[ "list", "list", "list",]
```
write 
```
["list", "list"]
```

**Comment by SimonGreenhill** [comment]
(That one gets me every time too)

**Comment by Schweikhard** [comment]
I see, thanks! It seems like this wasn't the only problem, though.

**Comment by LinguList** [comment]
Please provide the error code, ideally run the tests locally, okay? I think you may also find a good program to check json files online, or you use a good text editor that highlights syntax. You ARE using one, right?

**Comment by Schweikhard** [comment]
Figured it out, needed to replace the square brackets with curlies even though I don't see why.
It was still the same error code I provided above. I use Notepad++.

**Comment by LinguList** [comment]
It's because you use key-value pairs, you see? Lists are only for items that are listed, but once you have a key, you need to provide it. So does it work now?

**Comment by Schweikhard** [comment]
Yes, all integrity tests passed.

**Comment by Schweikhard** [comment]
Before I'm adding more entries into conceptrelations.tsv I would like to ask whether there are any potential kinds of conceptrelations covered by narrower which are not simultaneous also handled by either instanceof or haspart.
Also, I am wondering about the difference between marking x as narrower than y, and y as broader than x.

**Comment by Schweikhard** [comment]
Closing this as the framework for it is created - it only needs to be applied.
