### ISSUE TITLE
Age of acquisition of 299 words in seven languages

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#639]
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220611

There's actually data for 32 languages in the [supplementary material](https://doi.org/10.1371/journal.pone.0220611.s001).

**Comment by chrzyki** [comment]
Very cool. Releated to https://concepticon.clld.org/contributions/Luniewska-2016-299.

**Comment by LinguList** [comment]
I think this is almost the same. Any takers for mapping this? The major part of the work is just checking with the predecessor, maybe it's even the same data, and they just expanded the list? I mean 299 words is just the same number, and last time, they had 25 languages.

**Comment by chrzyki** [comment]
As far as I can tell it is basically the 2016 list expanded with 7 languages (American English, Czech, Gaelic, Lebanese Arabic, Malay, Persian, and Western Armenian).

**Comment by LinguList** [comment]
Excellent, even easier to map then.

**Comment by chrzyki** [comment]
I will take care of this tomorrow.

**Comment by xrotwang** [comment]
@LinguList how should we handle this? Add a new list, I guess, but only with the new languages - or the whole thing?

**Comment by LinguList** [comment]
They may have changed the data also. I'd say: add new list with all, just to be sure, as we cannot be sure they just expanded it and never corrected things in between.

**Comment by xrotwang** [comment]
I agree. If going only for the new languages, I would have recommended to check the remainder of the data for identity.

**Comment by chrzyki** [comment]
Questions: Since [this list](https://doi.org/10.1371/journal.pone.0220611.s002) is an official supplement as well (and it only contains the 'new' languages and lexemes and AoA data), couldn't this be used instead of having all the 2016 data doubled + 7 new languages?

**Comment by LinguList** [comment]
I prefer to have them doubled, unless you can show that they are 100% identical.

It's also more convenient: you take the new list, and have them all. No merging for users needed, etc.

**Comment by chrzyki** [comment]
Okay, I'll add it as it is then, i.e. the whole list with all 32 languages. The AOA data are *basically* identical. Why basically? Well, for the old 2016 publication [precision was two decimals](https://static-content.springer.com/esm/art%3A10.3758%2Fs13428-015-0636-6/MediaObjects/13428_2015_636_MOESM1_ESM.pdf), after comma. In the supplementary table precision seems to be higher (e.g. Swedish _to slip_ (_rutschkana_) 2016: 3.48 vs. 2019: 3.47826086956522 etc.). The 2016 table seems to be explicitly rounded. The 2019 table seems to have entries with higher precision, but also typical repeating patterns like 7.35135135135135.

For all intents and purposes this leads to almost identical sums and averages for the each respective AOA column. Do I simply keep the non-rounded versions for the 2019 list?

**Comment by LinguList** [comment]
I'd say: be as literal as possible here. Given that it's already given in electronic form...

**Comment by chrzyki** [comment]
Done in #641.
