### ISSUE TITLE
Identical concept sets

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#649]
There are a few instances of similar, if not identical, concept sets:

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|140|PADDY FIELD| A flooded field where rice is grown.| Agriculture and vegetation| Person/Thing|17|
|283|PADDY| Wet land in which rice is grown.|Agriculture and vegetation| Person/Thing|0|

_________________________________________________________________________________________

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|217|BETELNUT|The seed of the areca palm (Areca catechu).|Agriculture and vegetation| Person/Thing|15|
|2369|BETEL NUT|The seed of the areca palm (Mama'an in Meranau common version).| Food and drink| Person/Thing|0|

_________

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|732|YOUR (SINGULAR)| belonging to the second person that is addressed by the first person.|Possession | Other|10|
|2091|YOUR|belonging to the second person that is addressed by the first person|Possession| Other|0|

____________
Here, if one of the concepts is to be cut out, all the corresponding links should be moved accordingly.

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|241|TREE STUMP|A small remaining portion of the trunk of a tree with the roots still in the ground.| Agriculture and vegetation|Person/Thing |8|
|1023|STUMP OF TREE|The short piece left over after cutting off the most part.| Agriculture and vegetation|Person/Thing |3|

___________________
I'm not sure if these concept sets differ to the extent they should both be kept but then, in this case, this difference should be reflected in their definitions. On the other hand, there's just one entry _to live_, mapped to BE ALIVE, which makes LIVE irrelevant.

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|1422|BE ALIVE|To be alive; to have a life.|The body|Action/Process|94|
|2309|LIVE|To be alive; to have a life.|The body|Action/Process|0|

_____
The specification FRESHWATER in the concept's name is redundant.

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|467|CRAYFISH|A freshwater crustacean resembling small lobster.|Animals|Person/Thing|1|
|2813|CRAYFISH (FRESHWATER)| freshwater crustaceans resembling small lobsters| Animals|Person/Thing|1|

___________
Another issue relates to the distinction between BRAISE and STEAM which seems rather vague. Moreover, their definitions don't reflect the concepts' POSs.

|ID|Name|Definition|Semantic field|Ontological category|Representation
|---|---|---|---|---|---|
|2068|BRAISE (VERB)|A method of cooking using steam that avoids overcooking or burning food.| Food and drink|Action/Process|3|
|2067|STEAM (VERB)|A method of cooking using steam.|Food and drink|Action/Process|4|

I'd suggest the following definition of BRAISE (VERB): to cook meat or vegetables at a low temperature in a covered pan with a small amount of liquid.
STEAM (VERB) - to cook food, using steam.

**Comment by chrzyki** [comment]
I agree with all of the changes/proposals! If you don't mind, you can go ahead and prepare a PR (I'll show you how to do the replacement).

**Comment by Schweikhard** [comment]
The majority of these are already marked as duplicates in the rightmost column of concepticon.tsv.
The tree stumps and crayfishes can be merged.
Also braise and steam can likely be merged - @MacyL told me that everything on braise should be moved to steam, and that the first one on steam (by Allen) actually just means to cook in general.

**Comment by Kristina-Pianykh** [comment]
@Schweikhard should then the duplicate concepts be kept in concepticon.tsv? Wouldn't it be somewhat confusing?

P.S.: I will then link the entry in [Allen](https://concepticon.clld.org/values/Allen-2007-500-310) to STEAM and eliminate BRAISE, right? Because if Chinese 蒸 means to cook, then all the identical glosses in other lists (Castro-2010, Chen-2012) should be moved to COOK, shouldn't they?

**Comment by LinguList** [comment]
Linking for Chinese characters should be consistent, but there are other words for cook, so this needs to be double-checked.

As to the old entires: we decided long time ago to leave them IN. The practice is: if you have accidentally introduced a duplicate, add the ID of the correct concepticon entry to the last column, and use the lowest ID as basis. In this way, one can also capture direct aliases, e.g., betel nut vs. betelnut. Officially, the ones with larger IDs do not exist as valid concept sets and will be given an error if you link to them.

**Comment by LinguList** [comment]
And 蒸 is "dünsten", i.e., not the same as cooking something (cooking is broad sense of preparing food, as in German "kochen"). Maybe ask @laiyunfan or @MacyL to clarify, but the dictionaries clearly indicate that 蒸 is rather braise, and another word is usually used if you talk of cooking in general.

**Comment by Kristina-Pianykh** [comment]
I've just consulted @MacyL (thank you for help!), and 蒸 denotes the action of steaming food ('to steam'), which is to place food over steam to heat it up. In this case, should the entries with 蒸 be moved from BRAISE (VERB) to STEAM (VERB)?

**Comment by LinguList** [comment]
I thought BRAISE would mean more or less exactly this? Namely, "dünsten" or "dämpfen" in German?

**Comment by LinguList** [comment]
If this is not the correct term, translate as STEAM (SOMETHING) or STEAM (VERB)

**Comment by chrzyki** [comment]
BRAISE (https://en.wikipedia.org/wiki/Braising/ & https://de.wikipedia.org/wiki/Schmoren) vs STEAM (https://en.wikipedia.org/wiki/Steaming & https://de.wikipedia.org/wiki/D%C3%A4mpfen_(Kochen)).
