### ISSUE TITLE
Numeral Systems of the World's Languages

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#651]
* **https://mpi-lingweb.shh.mpg.de/numeral/**

Essentially, this is a questionnaire study culminating in lots of number lexeme tables, e.g.:

* https://mpi-lingweb.shh.mpg.de/numeral/Khowar.htm
* https://mpi-lingweb.shh.mpg.de/numeral/Bahinemo.htm
* https://mpi-lingweb.shh.mpg.de/numeral/Izon.htm

A *rough* total number of concepts can be found here:

* https://gist.github.com/chrzyki/09408370c0c1a3c493bf8df6bdae7d3b

This (automatically extracted) list might change a little bit with more edge cases (i.e. rarer number concepts) being added.

Having all the number concepts in Concepticon would help with mapping & preparing the Numeralbank releases.

**Comment by Kristina-Pianykh** [comment]
@chrzyki shall I add new concept sets even for those numerals that are listed only once / for one language?

**Comment by LinguList** [comment]
beware that we also need to add the concept-sets-meta, which is in the metadata folder, and consists of a simple number reflecting the numeral, if it can be displayed in a number.

**Comment by chrzyki** [comment]
Yes please! And as @LinguList said, also make sure to add the metadata like it was done for the other numerals.

**Comment by chrzyki** [comment]
Done
