### ISSUE TITLE
Pot, clay pot, kettle, pan, wok, jug, earthen jug

### ISSUE THREAD

**Issue by Schweikhard** [concepticon/concepticon-data#655]
POT https://concepticon.clld.org/parameters/1462
CLAY POT https://concepticon.clld.org/parameters/2055
KETTLE https://concepticon.clld.org/parameters/854
PAN https://concepticon.clld.org/parameters/31
WOK https://concepticon.clld.org/parameters/2056
JUG https://concepticon.clld.org/parameters/270
EARTHEN JUG https://concepticon.clld.org/parameters/3409

I think currently the English glosses are mostly where they should be (except for the ceramic pots at POT - but see below), but I'm not sure about some of the Chinese ones (e.g. there is something looking like a WOK linked to PAN).
The Hausa large water pot/ràndā likely should move to EARTHEN JUG but I don't know for sure.

Also, there may be some POTs which are actually not used for cooking but for storage (but there are no clear cases from what I see).
The unambiguous cooking pots could be moved to a new concept.
And CLAY POT is only for storage pots (if the definition is reliable - only thing linked is 土罐), but we also have some clay cooking pots, so those would need their own concept in that case.

**Comment by MacyL** [comment]
In Huang-1992-1820 罐子 pot/jar/tin should be linked to CAN [1051] (the same gloss in Chen-2012-888)

**Comment by Schweikhard** [comment]
Thanks for fixing the wok, @MacyL - could you check the Chinese glosses of the other concepts to see whether they are correct now?

In general, as _pot_ does not necessarily imply a cooking vessel but just about any vessel, I would suggest to add a new concept COOKING POT and map all pots that are specified to be used for cooking to that.
We could also add a new concept for WATER POT (for Kraft and Othaniel).

**Comment by MacyL** [comment]
My current principle is that "鍋" or "鍋子" will not be mapped to any concept. Because the image in my mind is like this ---> https://images.app.goo.gl/F1r8BGXqCeppdsjL9
罐子 is linked to CAN 
炒菜鍋 or 鍋(炒菜鍋）is linked to WOK ----> https://images.app.goo.gl/sJqUik8voTproU2w6
luckily, we don't have the concept  "鍋" or "鍋子" yet, but it's good to have a new concept "COOKING POT" for the future.

**Comment by Schweikhard** [comment]
To summarize: I'll move  "鍋" or "鍋子" to COOKING VESSEL, 炒菜鍋 or 鍋(炒菜鍋) to WOK, and 罐子 to POT?

**Comment by MacyL** [comment]
> 罐子 to POT?
罐子 to CAN, because POT is for cooking, but 罐子 is not for cooking.

**Comment by Schweikhard** [comment]
But 罐子 isn't made of metal, it's an Einmachglas - so I guess we should just unmap it or make a new concept JAR.

**Comment by Schweikhard** [comment]
Is 锅(炒菜的) and 炒菜的 also wok?

**Comment by MacyL** [comment]
> Is 锅(炒菜的) and 炒菜的 also wok?

To my understanding and my mapping principle, yes :D

**Comment by Schweikhard** [comment]
I would consider this solved by yesterday's PR.
