### ISSUE TITLE
Huber-1992-374 missing concepts/wrong numbers?

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#664]
https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Huber-1992-374.tsv

I'm a little bit confused with respect to this list (just noticed while working on the Lexibank data):

- it says 374 concepts in the title, but there is only 366 concepts in the list
- the number column is wrong in that it skips numbers and counts all the way to 374
- the original list (https://cdstar.shh.mpg.de/bitstreams/EAEA0-78F1-75A6-501A-0/Huber1992.pdf) seems to even have 375 concepts instead of 374

**Comment by LinguList** [comment]
There's a serious problem then. It needs to be checked with the original source then, also to see if the concepts add up, etc.

**Comment by LinguList** [comment]
In my opinion, it is wortwhile to:

1. type the list off again, and this time, truthfully to the source (we used it from the digitized version in lexibank by then, I myself was not primarily involved)
2. check with the glosses that are used in lexibank_hubercolumbian, and add them, with concept mappings, next to it
3. update concepticon, 

I think the digitized version of huber and reed was compromised, or (if this is not the case), the Huber-List was based on a bad intermediate version, in any case, this should be fixed soon, ideally before resubmitting the paper.

**Comment by chrzyki** [comment]
@Kristina-Pianykh and I checked it, there are another couple of issues. @Kristina-Pianykh will work on the list. Thanks!
