### ISSUE TITLE
Update on Polyglotta Africana/RefLex African List

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#665]
I recall this being discussed via mail and @Kristina-Pianykh waiting for input (if I remember correctly). Could we quickly discuss the status here? (Also to have it properly associated with the repository.

**Comment by tresoldi** [comment]
We also need to check if it is the same concept list for `tls`, and how much overlap there is with the mapping I did in the past: https://github.com/lexibank/tls/blob/master/etc/concepts.csv

**Comment by tresoldi** [comment]
This issue might be related to Nurse-1975 as well: https://github.com/concepticon/concepticon-data/issues/272

**Comment by Kristina-Pianykh** [comment]
All the lists could be found [here](https://docs.google.com/spreadsheets/d/10VrKzLbB65kSm7JYT4S7uJLqNR1jJZ6sESGECApMECg/edit#gid=554505756). Polyglotta Africana (see Polyglotta retyped), the lists by Donzo (see Donzo Appendices B-C, Donzo Appendices 1-4), Marchese (see Marchese Kru updated) and Smeltzer (see Smeltzer Bozo updated) were all retyped. I tried my best linking the French glosses but I'm afraid my A0 language level in French requires the assistance of someone more proficient.

Check also Snider's list, @chrzyki kindly looked through my mappings and left some comments. I resolved some of the issues but others still need to be discussed.

**Comment by Kristina-Pianykh** [comment]
The data from Snider's list was taken from [concepticon-dev](https://github.com/concepticon/concepticon-dev/blob/master/concepticondata/conceptlists/Snider-2004-1700.tsv), the source is on [comparalex](http://comparalex.org/?page=stdlist&id=13).

**Comment by LinguList** [comment]
Do you also have the official PDF? It's called "SIL COMPARATIVE AFRICAN WORDLIST", and this should be easy to find online. The problem is: it is PDF, and comparalex did some work of themselves to get the list into their format, so it is not clear how regular the lists match (but we may also say we take it from comparalex and check, etc.).

**Comment by Kristina-Pianykh** [comment]
Here the official publication [announced](https://www.sil.org/resources/publications/entry/7882) and here's the [PDF](https://www.sil.org/system/files/reapdata/88/54/65/88546558467011236880873045745569794523/silewp2006_005.pdf).

**Comment by tresoldi** [comment]
I was asked to help here, so we can integrate the list to Concepticon and properly link from the Lexibank `polyglottaafricana` dataset. What can I do to help? The sheet on Google already has all the information from the hand-coded `concepts.tsv` in the dataset, correct?

**Comment by chrzyki** [comment]
Here is the PR for the subset of concepts added to the list. @tresoldi the concepts were not taken from the sheet but mapped individually.
