### ISSUE TITLE
[Important for 2.3] Manually check retired.json for links from Huber-1992-374 to Huber-1992-375

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#676]
The ids are out of sync now, so the retired will most likely wrongly relink entries. We deliberately ignore this for 2.2, but it has to be done (although it's boring) for 2.3. That means: somebody (volunteers welcome) has to compare Huber-1992-374 with Huber-1992-375 and make new links for retired.json.

**Comment by xrotwang** [comment]
I think I'll fix this tonight - i.e. before 2.2.

**Comment by LinguList** [comment]
Okay, sorry for the mess. I guess we all learned a lesson for future lexibank-concepticon-interactions.
