### ISSUE TITLE
FLEE and RUN AWAY

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#680]
Is there a difference between [956 FLEE](https://concepticon.clld.org/parameters/956) and [2142 RUN AWAY](https://concepticon.clld.org/parameters/2142)? The Chinese 逃跑 is mapped to FLEE  in some lists and RUN AWAY in the others, introducing inconsistency. Would it be better to merge the two concepts?

**Comment by LinguList** [comment]
well, one is abstractt according to definition, one is not.

**Comment by LinguList** [comment]
And you are right: the Chinese 逃跑 or 逃跑 are probably better linked to run away, as this involves a movement, it's not like you flee an interview. I think, Chinese would express that differently.

**Comment by Kristina-Pianykh** [comment]
Thanks, now I got it!
I'll move the Chinese glosses to RUN AWAY then.
