### ISSUE TITLE
Lexical Questionnaires by Paperno and Ryzhova

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#683]
online at: https://sites.google.com/site/denispaperno/papers/questionnaires.zip

I did not yet fully understand the idea, but they use adjectives and word vectors to check for context that is useful to elicit a certain meaning.

Link to full text is here: https://scholarspace.manoa.hawaii.edu/handle/10125/24857

The list is not long. Probably interesting in the context of semantic norm data.

**Comment by Schweikhard** [comment]
Sounds interesting, I'll take a look.

**Comment by Schweikhard** [comment]
They also include semantic field tags, so this would also be nice for Speech Norms.
