### ISSUE TITLE
Typo in concept: SNAPP (OF STICK) 459

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#687]
The concept SNAPP (OF STICK) 459 has one "p" too much.

Only in inflected forms, the verb "to snap" has a two "pp", e.g, "snapping", "snapped". I think that is why nobody recognized it.

@tresoldi pointed out that the concept is also linked to CLICS, so I don't know whether it can be changed easily.

**Comment by LinguList** [comment]
Well, we have a file `concepticondata/retired.json`, where we can in fact make sure that something is re-linked to something, but I do not know, @xrotwang can tell us, if this would also be possible for an updated concept gloss.

**Comment by xrotwang** [comment]
@AnnikaTjuka you'd only want to fix the concept gloss, right? This would be easy. Retiring would only be necessary, if "SNAP (OF STICK)" is already available, so we'd remove a conceptset ID.

**Comment by AnnikaTjuka** [comment]
Yes, that's right. I'd only like to delete on "p" in SNAPP.

**Comment by xrotwang** [comment]
So you'd just edit it in [concepticon.tsv](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/concepticon.tsv#L460) - then run `concepticon test` to get notified about all linked concepts, which would need an update, too.

**Comment by xrotwang** [comment]
It's only linked in two lists anyway:
```
$ grep -r SNAPP concepticondata/
concepticondata/conceptlists/Chen-2012-888.tsv:Chen-2012-888-682	682	（扁担）断	break (stick)	794	459	SNAPP (OF STICK)		1292	动词
concepticondata/conceptlists/Nagano-2013-1256.tsv:Nagano-2013-1256-618	618	1118snap (vi)	459	SNAPP (OF STICK)	
concepticondata/conceptlists/Kraft-1981-434.tsv:Kraft-1981-434-432	459	SNAPP (OF STICK)	432	yā karyḕ	(stick) snapped
concepticondata/concepticon.tsv:459	SNAPP (OF STICK)	Basic actions and technology	Quick breaking or cracking sound or the action of producing such a sound.	Action/Process	
```

**Comment by LinguList** [comment]
yes, and this explains also why it is "snapp": the first list that actually mapped this was Kraft, I think, which we did back then in Marburg in 2013 or so...

**Comment by xrotwang** [comment]
A quick check turns up two more lists which are candidates for linking:
```
$ grep -r snap concepticondata/ | grep stick
concepticondata/conceptlists/Huang-1992-1820.tsv:Huang-1992-1820-1292	1292	break / snap (stick)	断(棍子~)			v.	break / snap (stick)
concepticondata/conceptlists/Huang-1992-1820.tsv:Huang-1992-1820-1293	1293	snap / break (a stick)	弄断(~棍子)	2558	BREAK (CLEAVE)	v.	snap / break (a stick)
```

**Comment by LinguList** [comment]
The first only, as the Chinese concepts indicate that the first is intransitive and the second is transitive, and it means more "to break something".

**Comment by AnnikaTjuka** [comment]
There is another list (Winter-2016) which we just added that also needs to be updated.

So I edit the lists manually with the correct spelling, right?

**Comment by LinguList** [comment]
Yes.
