### ISSUE TITLE
ULD-1600 "Universal language dictionary" resource with 1600 concept in different languages

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#69]
this is an interesting resource I was just pointed to by @kaleissin (from the CALS project):
- http://www.uld3.org/uld27/index.html

They have a strange licence, though, but I think we should be allowed to provide links to their concepts, and since they provide an email of the copyright holder, we could directly contact him.

**Comment by xrotwang** [comment]
URL doesn't resolve as expected anymore.
