### ISSUE TITLE
Zettersten-2019-12: Color terms used for a cognition naming game

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#690]
This is not a strict norm data set, but some experiment with 12 colors, defined in rgb, that may in fact also be useful to be included.

https://doi.org/10.1016/j.cognition.2019.104135

I imagine a situation like this: scholars who work on color terms are interested who investigates them, and they could easily find them, if the studies that use them are linked. 

That is not to say we should link the whole palette they use for their color experiments in the 70s, but one could even add parts of those palettes to the color terms in concepticon, or add a dataset-meta in which color terms that we have are named accordingly (similar to our dataset-meta for numbers).

**Comment by AnnikaTjuka** [comment]
I can't access the article nor the supplementary material. @LinguList Do you have access and would send me the list?
