### ISSUE TITLE
WILD ANIMAL = ZEBRA ? and SCARF = CLOTH ?

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#694]
In the concept set WILD ANIMAL (958), the data from Luniewska-2016-299-158 and Luniewska-2019-299-158 are mapped to the word _zebra_. Although a zebra is a wild animal, should we use a new concept ZEBRA or delete the mapping?

**Comment by AnnikaTjuka** [comment]
In the concept set CLOTH (1616), the data from Luniewska-2016-299-115 and Luniewska-2019-299-115 are mapped to the word _scarf_. Although a scarf is a woven fabric, should we use a new concept SCARF or delete the mapping?

**Comment by AnnikaTjuka** [comment]
In the concept set CLOTHES (1895), the data from Luniewska-2016-299-134, Luniewska-2019-299-134 (Pullover) & Luniewska-2016-299-152, Luniewska-2019-299-152 (Weste) are mapped to the word _clothes_. Although a pullover and a vest are clothes, should we use new concepts or delete the mapping?

**Comment by Schweikhard** [comment]
Those look like mismappings to me, so they should be changed to the more appropriate concepts, or left unmapped.
Also _sweater_ in 2 Luniewska-lists is mismapped to CLOTHES.

**Comment by chrzyki** [comment]
Should all be updated with more specific concepts I think. Mapped to specific terms to too general terms, my mistake back then. :)

**Comment by Kristina-Pianykh** [comment]
The concept ZEBRA is already proposed in one of the pending PRs. Just mentioned it to avoid redundancy :)

**Comment by LinguList** [comment]
Yes, clear mismappings. We should add the list by @Kristina-Pianykh first, so the Zebra can be mapped then...

**Comment by AnnikaTjuka** [comment]
Okay, I'll go through the list again to check for other mismatches.

**Comment by chrzyki** [comment]
Found some more problems, see #696. Feel free to add to this PR.
