### ISSUE TITLE
Differentiate meanings of KNOW

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#700]
We'd need to re-link all know instances, with at least three meanings: 
    - know (be knowledgeable of something): "I know that X"
    - know (be acquainted with something): "I know a book"
    - know (a person): "I know her"
    - know (how to): "I know how to swim"
    - maybe more meaning shades I missed here?

_Originally posted by @LinguList in https://github.com/concepticon/concepticon-data/pull/699_

This would also solve issue #607.

**Comment by AnnikaTjuka** [comment]
@Schweikhard and @LinguList Please see below my suggestions for remapping and introducing a new concept (KNOW (AN OBJECT)).

ID | concept | definition | mappings | proposed mappings
-- | -- | -- | -- | --
1410 | KNOW (SOMETHING) | To be certain or sure about something. | know, be knowledgeable, know fact, wissen | be knowledgeable, know fact, wissen (move all single "know" to KNOW)
2238 | KNOW OR BE ABLE | To be able to do something which requires or could require that one would learn it before. | to know how, know/can/be able, know something | to know how, know/can/be able
2248 | KNOW (SOMEBODY) | To have met and recognize somebody. | recognize, know s.o. | (no changes)
3626 | KNOW | To have met and recognize somebody or to be certain or sure about something. | know (something or someone), Conocer to know, know | all "know" that are ambiguous
3764 | KNOW (AN OBJECT) |  |  | know (as in ‘I know this’), 熟悉 [chinese]; familiar with, be/know sthg. o [english], Conocer to know

**Comment by LinguList** [comment]
I am not sure. For me, the "something" in know (something) already covers the knowledge of an object. The shuxi in Chinese has a specific use case, I'd rather translate it as "familiar with", and the conocer from Spanish does not seem to fit this category, as it rather means "to know somebody or something".

**Comment by Schweikhard** [comment]
I would rename KNOW OR BE ABLE to KNOW HOW TO (or similar) as it's not a hyperonym of KNOW and BE ABLE.

The definition of KNOW should likely also include KNOW (AN OBJECT).

Besides that, this seems to include all the relevant cases (unless there are any elicitation glosses that mix up those cases in unexpected ways).

**Comment by AnnikaTjuka** [comment]
Thanks for the input! I updated the table accordingly:

ID | concept | definition | mappings | proposed mappings
-- | -- | -- | -- | --
1410 | KNOW (SOMETHING) | To be sure about something or be acquainted with something. | know, be knowledgeable, know fact, wissen | know (as in ‘I know this’), 熟悉 [chinese]; familiar with, be/know sthg. o [english], be knowledgeable, know fact, wissen (move all single "know" to KNOW)
2238 | KNOW HOW | To be able to do something which requires or could require that one would learn it before. | to know how, know/can/be able, know something | to know how, know/can/be able
2248 | KNOW (SOMEBODY) | To have met and recognize somebody. | recognize, know s.o. | (no changes)
3626 | KNOW | To have met and recognize somebody or to be certain or sure about something. | know (something or someone), Conocer to know, know | know (something or someone), Conocer, all "know" that are ambiguous

**Comment by AnnikaTjuka** [comment]
Next steps: Change concept name (KNOW OR BE ABLE to KNOW HOW) and update the mappings on the basis of those four concepts.

**Comment by Schweikhard** [comment]
Good! One suggestion, in the definition of KNOW: "to be certain or sure about something" -> "to be sure about or acquainted with something".
