### ISSUE TITLE
Serva-2012-200 was published in 2011

### ISSUE THREAD

**Issue by SimonGreenhill** [concepticon/concepticon-data#701]
Even though some places show it as 2012 (e.g. [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3223632/), the journal has it at 1st june 2011: https://royalsocietypublishing.org/doi/10.1098/rsif.2011.0228

**Comment by LinguList** [comment]
Sorry, I just checked the journal again, it is NOT 2011: J. R. Soc. Interface (2012) 9, 54–67

The 2011 is the date of publication online, but the issue it was assigned to I find is 2012. So no need to change here.

**Comment by SimonGreenhill** [comment]
This is so weird -- the DOI resolver says 2011, the PDF says 2012, the website says 15 June 2011 ?!? I guess the PDF is the item of record, so 2012 it is!
