### ISSUE TITLE
Duplicate kinship concepts

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#708]
MOTHER'S SISTER and MATERNAL AUNT (MOTHER'S SISTER) appear to be completely identical (semantic field, definitions, ontological category). Yet the former has more metadata (LEGO ID and OMEGAWIKI ID) while the latter - detailed concept relations.

Same goes for FATHER'S SISTER and PATERNAL AUNT (FATHER'S SISTER) (except neither has concept relations), as well as MOTHER'S BROTHER and MATERNAL UNCLE (MOTHER'S BROTHER).

Interestingly, the paternal uncle has just one representation in Concepticon (FATHER'S BROTHER) which has both metadata and concept relations.

The question is: should the duplicates be merged and the corresponding lists moved? Would the more detailed naming be preferred?

**Comment by LinguList** [comment]
Yes, they should be moved. I'd suggest to use "* AUNT" as the base. Thus, yes: the more detailed naming is preferred, as we have some patterns here, also with more complex kinship terms.

**Comment by Kristina-Pianykh** [comment]
Shall I then delete the concepts sets after I move all the lists to those with "* AUNT" base? Or leave them with zero links and indicate the reference concepts in the most right column in concepticon.tsv?

**Comment by LinguList** [comment]
No deletion, just add the "alias", as you suggest.
