### ISSUE TITLE
Replace Heggarty-2017-200 with the now published Heggarty-2020-200 as referenced in Scarborough2020

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#710]
finally published at least somewhere.

```bibtex
@InCollection{Scarborough2020,
  author    = {Scarborough, Matthew},
  title     = {Cognacy and computational cladistics: Issues in determining lexical cognacy for Indo-European cladistic research},
  booktitle = {Dispersals and diversification: Linguistic and archaeological perspectives on the early stages of Indo-European},
  year      = {2020},
  editor    = {Matilde Serangeli and Thomas Olander},
  publisher = {Brill},
  pages     = {179-208},
  address   = {Leiden},
}
```

**Comment by LinguList** [comment]
![Scarborough2020](https://user-images.githubusercontent.com/2916210/72222598-de419e00-3566-11ea-94cc-619b56f0b6f8.png)
![Scarborough2020-1](https://user-images.githubusercontent.com/2916210/72222601-e00b6180-3566-11ea-8a39-b8c988600e51.png)

**Comment by LinguList** [comment]
I suppose, whoever adds this list, should convert the two PNG files to pdf. Contact me if you need the article, I have it in PDF from the library.

**Comment by PaulHeggarty** [comment]
This list is already in Concepticon:  https://concepticon.clld.org/contributions/Heggarty-2017-200

**Comment by LinguList** [comment]
Then we should rename Heggarty-2017-200 to Scarborough-2017-200, since there is no real citation available for Heggarty-2017-200. Since Scarborough is citable, this one should be preferred (and Scarborough, unfortunately, made no reference to the Heggarty-list). The alternative is to check if they are really the same (no spelling differences, capitalization, etc.) and change the source in Heggarty-2017-200. 

The letter solution is the preferred one, as Heggarty is listed as main author (which is probably correct, and Anderson and Scarborough can be listed as the three main authors), and would otherwise not be mentioned. Then, following the procedure in the list of [Yakhontov-1991-100](https://concepticon.clld.org/contributions/Yakhontov-1991-100), we attribute the list to another author (team) than the source that mentions the list. 

We can even leave the date.

**Comment by xrotwang** [comment]
There are differences:
- different order. "ant" is number 146 in Heggarty-2017-200, and first here
- different capitalization: Heggarty-2017-200 is all lowercase, this is all uppercase
- different wording of gloss: Heggarty-2017-200 has "bark", this has "(TREE) BARK"

**Comment by PaulHeggarty** [comment]
The lists are fundamentally the same in that they refer to the same concepts, and therefore would have identical Concepticon mappings.  There are superficial differences in how Matthew chose to 'name' the concept to disambiguate in his paper, e.g. "(tree) bark".

**Comment by PaulHeggarty** [comment]
Within the IE-CoR project, this 200 list was an intermediate stage in the iterative process of honing down to our definitive list that will be published as the IE-CoR 170 list.  Matthew's paper was written on the basis of that intermediate stage list, and is about the process and criteria for honing down.  Section 3.6 already announces the next stage, the reduction to 180, and the final stage thereafter got us down to 170, which is the data-set that will be published.

**Comment by PaulHeggarty** [comment]
Preferably the Heggarty-2017-200 list should be ordered alphabetically.

**Comment by xrotwang** [comment]
Maybe we should replace Heggarty-2017-200 with this list after all? It was added under the assumption that it was going to be the final list for IE-COR, and only has an outdated source, giving `cobl.clld.org` as URL?
So considering that there won't be actual lexical data published with reference to this list, the only reason to keep it in Concepticon is Matthew's paper.

**Comment by PaulHeggarty** [comment]
The 200-item list was never seen as the likely definitive list for which the data-set would be published.  We were in the middle of an iterative process of refining the list, informed by and dependent on the realities of the data-gathering and cognacy coding in practice.  That is why I felt it was maybe premature to put it on Concepticon.  
But it depends on what you want the lists for.  Concepticon is useful to illustrate differences between related lists, and if you want the different stages of the honing-down process to be on Concepticon as different lists, subsets of each other, then that would be possible.
Matthew's paper is a demonstration and explanation of some of the criteria for the process of honing down a concept list (particularly criteria on cognacy assignment vis à vis Proto-Indo-European).  It's also explained in the supplement to the results paper we submitted.

**Comment by PaulHeggarty** [comment]
To put it another way:  I consider the 200-item list now deprecated for IE-CoR purposes, although it was a relevant part of the list-refining process.

**Comment by LinguList** [comment]
> Maybe we should replace Heggarty-2017-200 with this list after all? It was added under the assumption that it was going to be the final list for IE-COR, and only has an outdated source, giving cobl.clld.org as URL?

@xrotwang, yes I agree. We delete the obsolete Heggarty-list, and we use Scarborough's list, but to be fair to the authors involved there, we can list Paul, Cormac, and Matthew as the chief designers.

**Comment by Kristina-Pianykh** [comment]
Should the DESCRIPTION and EXAMPLE_CONTEXT columns be kept? They help to disambiguate some concepts. But on the other hand, I don't really understand where they come from. I checked against [the IE-CoR public wiki on GitHub](https://github.com/lingdb/CoBL-public/wiki/Meaning:-fruit) but each concept there lists quite a few meanings and the wording of the very first meaning does not always coincide with that in old Heggarty-2017-200. Moreover, this page lists the meaning for 171 concepts only.

**Comment by PaulHeggarty** [comment]
Yes, these fields are out of date, and the public wiki also reflects an earlier, now superseded stage.  The basic problem is that this list was put up when it was only an intermediate stage in a process.  I'm not sure why it is up there.  There is no published data-set that uses this list.  When we get the Indo-European paper published, and the corresponding data set, then yes, there will be a data-set using our definitive list, and on publication obviously we will publish that definitive concept list, with all finalised fields.

**Comment by xrotwang** [comment]
@Kristina-Pianykh so I guess we drop the DESCRIPTION and EXAMPLE_CONTEXT columns and limit the then Scarborough-2020 list to only things available from the source paper.
