### ISSUE TITLE
CLICS as norm data

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#714]
As discussed with @LinguList, we should add the new CLICS 3 data from Rzymski et al. (2020) as norm data. @chrzyki would you help me with this?

**Comment by chrzyki** [comment]
Sure, let's talk about this later today if you have time?

**Comment by AnnikaTjuka** [comment]
Sounds good! I don't have any meetings today so you can come by when it works for you.

**Comment by LinguList** [comment]
Update, the norm data should not be added in norm data form, but in form of a concept list, which we call "Rzymski-2020-XXXX". The data can be calculated as we did the last time. One needs the GML graph and can then compute various statistics. 

A quick possibility to do so, would be to just take the GML file, compute the statistics in a run, and then add them as a concept list. 

If needed, I could just do that and introduce the code in a blogpost, that I'd publish on Wednesday. @chrzyki @AnnikaTjuka, would you be fine with this? I am also not against leaving this to either of you, but it may be faster if I quickly introduce this, so you can then build on it in the future?

**Comment by LinguList** [comment]
Update, I just made a script that computes the data. but I do not have the infomap-3-families file that we used for the clics paper (this has never been submitted anywhere, but should be so, ideally on zenodo, or as update to clics3, for the sake of reproducibility.

So my script used an older file, but it does the same job.

**Comment by LinguList** [comment]
@chrzyki, could you maybe update the file infomap-3-families.gml.zip to the clics3 repository? Or you send it to me or put it as is on zenodo. Ideally, I think, an update would be best, so we have an update for the clics3 on github and zenodo, with this file.

**Comment by LinguList** [comment]
I can then re-run the script.

**Comment by chrzyki** [comment]
Should be here: https://codeocean.com/capsule/7201165/tree/v2

Download option is in the file browser on the right hand side -> graphs -> infomap*.gml -> download.

**Comment by chrzyki** [comment]
I'll also add these versions to the CLICS repository.
