### ISSUE TITLE
Add links to wikidata

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#72]
I didn't know of [wikidata](https://www.wikidata.org/) before, but now that I checked it, it seems it could give us valuable information in many respects, not for all concept sets, of course, but probably for quite a few. Here's, for example, the wikidata for hand:
- [https://www.wikidata.org/wiki/Q33767](https://www.wikidata.org/wiki/Q33767)

They also seem to have a good API, so one may be able to search more or less automatically for good matches...

**Comment by xrotwang** [comment]
Yes, for our purposes wikidata may become more important than Wikipedia.
Am 16.01.2016 15:03 schrieb "Johann-Mattis List" <notifications@github.com>:
