### ISSUE TITLE
BE DEAD OR DIED as a catch-all category

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#722]
That would be one option. Then BE DEAD OR DIED would be a catch-all category for "to die, dead", "died" and "having died".

_Originally posted by @Schweikhard in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0MzYzNTc3NzUx/timeline/more_items_

We had a discussion on whether we can map "gestorben" to DEAD. 

Because it is similar to the meaning of "died" and BE DEAD we would propose the following solution:

Map all glosses with "die, dead", "died", "having died" and "deceased" to BE DEAD OR DIE.

As of yet, most "died" are mapped to DIE. Therefore, we would need to remap them to BE DEAD OR DIE.

**Comment by Schweikhard** [comment]
Hm, with Backstrom clarified, the "he died" cases are excluded, but aren't there other relevant cases? E.g. https://concepticon.clld.org/values/Bromley-1967-111-17

**Comment by LinguList** [comment]
I am not sure, as this is again a list specific for a region, where
elicitation seems to be better for this purpose. Compare e.g.,
McElhanon's list, where consequently only the third person is elicited,
etc. I think, the only clear-cut case would be "die/be dead", and this
is something one can indeed find in some concept lists, right?

**Comment by Schweikhard** [comment]
Yes, and those cases are already mapped correctly to DIE OR BE DEAD.

This discussion was sparked by a new concept list containing the term "gestorben".
