### ISSUE TITLE
List with two meanings per word

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#723]
I found a cool list with relative meaning frequencies for 100 homonyms in English. For most words we have only one of the meanings in Concepticon. But for 8 words we have both meanings/concepts. 

@chrzyki or @xrotwang Is it possible to add the list so that one entry occurs for both concepts? 

I have inserted additional ID and GLOSS columns for the double-concepts and uploaded the list here: [Maciejewski-2016-100.txt](https://github.com/concepticon/concepticon-data/files/4147818/Maciejewski-2016-100.txt)

**Comment by LinguList** [comment]
You should just double the list, so you have one row for fly, link it to fly (move through air) and one for the other fly (insect). So one row for each meaning, and then, this is a perfectly linkable list, since nobody says we cannot have the same value two rows.

**Comment by AnnikaTjuka** [comment]
Great, thanks! I will double the rows for the 8 words.

**Comment by Schweikhard** [comment]
Why not duplicate every row? We might want to map more homonyms later if the concepts in question are added to Concepticon, so it's better to have them included.
Or am I misunderstanding you?

**Comment by LinguList** [comment]
Yes, @Schweikhard, that's what I meant in fact: duplicate all rows, as the information is more clearly outlined then (even for the original dataset, it would be better, I think..., but that's the authors of the original dataset...).

**Comment by AnnikaTjuka** [comment]
Ah ok, I wasn't sure what "double the list" meant. Thanks for the clarification! I will duplicate each row.
