### ISSUE TITLE
[Question] Multiple glosses in the source are mapped to the same concepts

### ISSUE THREAD

**Issue by MacyL** [concepticon/concepticon-data#724]
I am cleaning up my Clark-2008-757 concept list (temporary file name). Lexibank reports 757 concepts, but I actually have 789 concepts in my source. The author used different terms to describe the same lexical item. For example, I link both "good" and "to be good" to GOOD [1035]. Many similar cases can be found in the dataset. My question is that which concept list name and ID tag suits this dataset better, Clark-2008-789 or Clark-2008-757?

**Comment by LinguList** [comment]
The number of concepts is the number of concepts mentioned in the source. If they list 789 and number them, or put them in a sheet with 789 rows, this is the number you should use.
