### ISSUE TITLE
Duplicate STRIKE and STRIKE (SOMETHING)

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#726]
These seem to be duplicates:

353 | STRIKE | To intentionally hit with a sharp blow or to impel, usually with a hand or weapon.

3309 | STRIKE (SOMETHING) | To intentionally hit something with a sharp blow or to impel, usually with a hand.

**Comment by AnnikaTjuka** [comment]
Can I just add "353" in the REPLACEMENT_ID for STRIKE (SOMETHING) 3309?

**Comment by Schweikhard** [comment]
There seemed to have been the intention to distinguish between striking an object (STRIKE SOMETHING) and striking a person (STRIKE SOMEONE), and the one thing mapped to the latter and one of the two things mapped to the former do specify that in their annotation. STRIKE on the other hand are those which don't specify the kind of target.
So, if we trust those annotations, we should keep that distinction, even if it's only for one list for each hyponym.

The other thing mapped to STRIKE SOMETHING, Sun's 打(人), looks to me like it's rather STRIKE SOMEONE.

**Comment by Schweikhard** [comment]
There are some more things on STRIKE that could be moved to the hyponyms.

**Comment by AnnikaTjuka** [comment]
I see your point. But then we would need to make the descriptions more distinct. 
We also have two other concepts with regard to hit/strike:

1433 HIT To hit against with a sharp blow or to impel, usually with a hand or weapon or to be forcefully or suddenly contacting, e.g. a tree falling down and hitting the ground.

3307 HIT (A TARGET) To hit something that someone has aimed for.

Maybe some of the "hit" mappings belong to those two?

**Comment by LinguList** [comment]
打(人) means "beat somebody", so it should be compared against other chinese lists being mapped. I guess the concept is rather clear, although of course one can specify it: beat with legs, with fists, etc., but the major idea is to beat somebody out of agression etc.

**Comment by Schweikhard** [comment]
HIT (A TARGET) is _treffen_, so it's quite distinct from HIT.

The difference between HIT, STRIKE, BEAT and POUND (and KNOCK) isn't really clear to me.

KNOCK might be _anklopfen_, but the rest seems very vague.
POUND contains _pound rice_ (or _grain_ or _sago_), which is quite specific.
BEAT contains _beat (heart)_, which is something else entirely.

But for the other things mapped to these I don't see a clear distinction.

**Comment by AnnikaTjuka** [comment]
This issue is tricky so I put everything into a table to make it clearer (hopefully). I relied only on the English glosses. In a second step, the Chinese mappings might need to be reorganized as well.

ID | concept | definition | current mappings | suggested mappings
-- | -- | -- | -- | --
353 | STRIKE | To intentionally hit with a sharp blow or to impel, usually with a hand or weapon. | hit with hand/fist, hit with stick, strike | strike
2133 | STRIKE OR BEAT | To hit or strike, either repeatedly or a single time. | hit table, beat, pound/beat, beat/hit/strike, strike table, hit/beat, schlagen, strike with open palm | beat/hit/strike, beat/hit,  hit/beat
3308 | STRIKE (SOMEONE) |To intentionally hit someone with a sharp blow or to impel, usually with a hand or weapon. | beat;schlagen | (no changes)
3309 | STRIKE (SOMETHING) | To intentionally hit something with a sharp blow or to impel, usually with a hand. | hit;hauen, hit/beat | hit;hauen
1433 | HIT | To hit against with a sharp blow or to impel, usually with a hand or weapon or to be forcefully or suddenly contacting, e.g. a tree falling down and hitting the ground. | hit with hand, beat/hit, hit | hit, hit with hand/fist, hit with stick
3307 | HIT (A TARGET) |  To hit something that someone has aimed for. | hit a target, hit (打中) | hit a target, hit (打中), hit table 
1665 | BEAT |  To strike or pound repeatedly, usually in some sort of rhythm. | beat, strike/hit/beat, beat/hit, beat drum, beat heart | beat, beat drum, beat heart
354 | POUND | To strike hard, usually repeatedly. | pound/beat rice/sago/grain, pound with force, pound with fist, pound | (no changes)

**Comment by AnnikaTjuka** [comment]
@Schweikhard and @LinguList Please have a careful look at my suggestions for re-mappings. I would also suggest to extend the concept  STRIKE OR BEAT with OR HIT.

**Comment by Schweikhard** [comment]
I would add a new concept for BEAT (HEART) (or unmap it from BEAT).
BEAT could be continued to be used for the beating of a drum or similar.
The remaining things mapped to BEAT could be remapped to POUND then as they likely fit the definition of that.

I'd also add new concepts for the pounding of food (or at least unmap those from POUND).

HIT would by your definition be a hyperonym of STRIKE, to unspecify the intentionality.
Therefore, the hyperonym STRIKE OR BEAT could by that solution I propose be renamed to HIT OR POUND (or to STRIKE OR POUND if we assume that in all relevant cases it's about intentional hits).

**Comment by AnnikaTjuka** [comment]
> I would add a new concept for BEAT (HEART) (or unmap it from BEAT).
> BEAT could be continued to be used for the beating of a drum or similar.
> The remaining things mapped to BEAT could be remapped to POUND then as they likely fit the definition of that.
>
There is only one list for _beat heart_ and another for _beat drum_. Is it worth creating a more fine grained concept to differentiate the two? Also I am not sure, if the concepts in Backstrom _(you) beat!_ / _beat_! should be mapped to POUND.

> I'd also add new concepts for the pounding of food (or at least unmap those from POUND).
> 
I could imagine that the food is only an example of what is being pounded. But if they are really **only** used for food, I can map them to a different concept.

> HIT would by your definition be a hyperonym of STRIKE, to unspecify the intentionality.
> Therefore, the hyperonym STRIKE OR BEAT could by that solution I propose be renamed to HIT OR POUND (or to STRIKE OR POUND if we assume that in all relevant cases it's about intentional hits).

Based on the glosses, I'd rather change the concept to HIT OR BEAT. As for the definitions, I used the ones given in Concepticon. Maybe they also need to be adapted to the glosses.

**Comment by Schweikhard** [comment]
> There is only one list for beat heart and another for beat drum. Is it worth creating a more fine grained concept to differentiate the two? Also I am not sure, if the concepts in Backstrom (you) beat! / beat! should be mapped to POUND.

Hm, if you do want to continue the differentiation between POUND and BEAT, then my suggestion would be for those:

- unmapping the beating heart (and perhaps the beating of drums, as that's also quite specific)
- BEAT: To strike or pound repeatedly.
- POUND: To strike hard. (if it's "To strike hard, usually repeatedly.", then it would be basically a hyponym of BEAT)

> I could imagine that the food is only an example of what is being pounded. But if they are really only used for food, I can map them to a different concept.

Glosses like "to pound, beat (as rice or prepared food)" don't sound like it's just an example, and in general it seems like a very different notion.
