### ISSUE TITLE
Sadowsky-2020-XXX: Concept list of Mapudungun data from Sound Comparisons

### ISSUE THREAD

**Issue by PaulHeggarty** [concepticon/concepticon-data#748]
In exporting the Sound Comparisons: Mapudungun data-set to lexibank, we will also export a ‘concept set’ derived from Sound Comparisons: Mapudungun.  For each of the entries in our Mapudungun lexeme list, our database already includes the Concepticon ID that corresponds, except for 27 lexemes that don’t have straightforward equivalents in Concepticon.  This issue is about these outstanding 27 cases.

I’ll separate them into two types (17 + 10), so that the Concepticon team can decide how you want to handle these.

1.	Entries that are basic enough that you may want to have them in Concepticon, and which are more or less close to existing Concepticon concepts, but that make additional or different **distinctions** that would require separate concepts.  

2.	Entries that are probably too specific to Mapudungun to bother adding to Concepticon, but which I list for reference, and to clarify why.

**Comment by PaulHeggarty** [comment]
1. MEANINGS THAT WOULD NEED DIFFERENT DISTINCTIONS
- [ ] WE (DUAL) vs. WE (PLURAL).  This is not an inclusive/exclusive distinction (i.e. not Concepticon [1131](https://concepticon.clld.org/parameters/1131) vs. [1130](https://concepticon.clld.org/parameters/1130)), but just a ‘dual’ vs. ‘more than two’ distinction, irrespective of clusivity.  (So the dual we can be either 1st + 2nd person, or 1st + 3rd person.)  This distinction is also present in other languages with a dual, and is included in Sound Comparisons: Vanuatu too, so would be needed for that list too.  I would add we (dual) and we (plural) as separate concepts, narrower concepts within the broader WE [1212](https://concepticon.clld.org/parameters/1212).
- [ ] DAUGHTER (OF A MAN).    Mapudungun distinguishes words for ‘daughter’ dependent on whether seen from the perspective of the father or the mother.  Referring to the same daughter, the father would use the lexeme _ñawe_, the mother _püñeñ_.  Similarly for others to refer to ‘his daughter’ one would use _ñawe_, for ‘her daughter’ _püñeñ_.  See Catrileo (2005: 18-20).  This distinction is also present in other languages, e.g. in Cuzco Quechua (_ususi_ vs. _warmi wawa_ respectively).  The Sound Comparisons: Mapudungun data are specifically _ñawe_, so to specify the meaning correctly would require this as a separate concept, a hyponym of the current DAUGHTER [1357](https://concepticon.clld.org/parameters/1357).  See for example (here)[http://kmm.cl/zungu/Renhma.png], or the kinship component of [parabank](https://glottobank.org/#parabank).
- [ ] HOT (OF WEATHER).    Concepticon differentiates COLD [1287](https://concepticon.clld.org/parameters/1287) from specifically COLD (OF WEATHER) [2483](https://concepticon.clld.org/parameters/2483), but there doesn’t seem to be a parallel distinction for HOT.  The meaning in Sound Comparisons: Mapudungun is specifically HOT (OF WEATHER), so it would require this as a separate concept.
- [ ] COB OF CORN.  This is not the concept MAIZE [506](https://concepticon.clld.org/parameters/506) as the crop in general.  Mapudungun has a separate, unrelated lexeme for the COB, seen as a quite separate concept (as do other languages, e.g. Cuzco Quechua _sara_ vs. _chuqllu_).   
- [ ] FRUIT WINE  (but of other fruit, not grapes).   Concepticon [1524 ](https://concepticon.clld.org/parameters/1524 ) is WINE, but defined as made from grapes.  The term in Sound Comparisons: Mapudungun is usually simply translated ‘vino’/‘wine’, but this is traditional ‘wine’ made of other fruit, not grapes.   This would require a separate concept, perhaps termed FRUIT WINE or something?
- [ ] LAND, EARTH.  This Mapudungun term _mapu_ is translationally equivalent to (some senses of) both ‘land’ and ‘earth’ in English.  It is broader than just LAND [626](https://concepticon.clld.org/parameters/626), and is not specifically ‘soil’, so not an exact match with EARTH/SOIL [1228](https://concepticon.clld.org/parameters/1228).  Could LAND OR EARTH be a distinct new concept for such cases? 
- [ ] LAKE, SEA.  The Mapuche world is full of freshwater lakes, but also runs along the Pacific Ocean.  This basic term in Mapudungun can refer to either, so does not match either LAKE [624](https://concepticon.clld.org/parameters/624) (defined as ‘from which the sea is excluded’) or SEA [1474](https://concepticon.clld.org/parameters/1474) (defined as “a body of salt water”).  Concepticon does include SEA OR OCEAN [2282](https://concepticon.clld.org/parameters/2282).  Most appropriate here would be an equivalent LAKE OR SEA concept. 
- [ ] SPREAD OUT FLAT.  This Mapudungun lexeme is not so far removed from [38](https://concepticon.clld.org/parameters/38) SPREAD OUT, but that is the verb form, whereas Sound Comparisons: Mapudungun is specifically an adjective root in its own right, and not derived from a verb. 
- [ ] SHATTER, i.e. break into many small pieces.  Concepticon [3191](https://concepticon.clld.org/parameters/3191) is BROKEN (SHATTERED) an adjective (past participle in English), but Sound Comparisons: Mapudungun uses the verb.
- [ ] SMASH.  The closest may be Concepticon [1520](https://concepticon.clld.org/parameters/1520) CRUSH, but semantically this is not a good match, so a separate SMASH concept would be needed.  
- [ ] TOO MUCH.  This is present in Concepticon as [Hale-1973-1798-1112](https://concepticon.clld.org/values/Hale-1973-1798-1112), but is not assigned a concept ID.
- [ ] STEP ON  
- [ ] WRING
- [ ] VISITOR
- [ ] ELSEWHERE

If any of these are accepted for addition into Concepticon, then we would obviously update our Sound Comparisons database with the new Concepticon codes (e.g. if they could be entered in this list).
* WE (DUAL)
* WE (PLURAL)
* DAUGHTER (OF A MAN)
* FRUIT WINE  
* HOT (OF WEATHER)
* LAND, EARTH
* LAKE, SEA
* SPREAD OUT FLAT
* SHATTER
* SMASH 
* TOO MUCH
* COB OF CORN  
* STEP ON  
* WRING
* VISITOR
* ELSEWHERE

**Comment by PaulHeggarty** [comment]
2. MEANINGS TOO SPECIFIC TO MAPUDUNGUN?
Sound Comparisons: Mapudungun targets particular (cognate) lexemes in Mapudungun, and therefore includes lexemes that have senses specific to Mapuche culture and contexts.  They are not universal and may be too narrow to be useful to add as concepts in Concepticon.  Some of the English translations can sound fairly general, but these are just shorthand for the more precise full English definitions, which are narrower in sense.  For example: 
* Concepticon does have unassigned SEAWEED in [Bowern-2012-644-447](https://concepticon.clld.org/values/Bowern-2012-644-447), but the term in Sound Comparisons: Mapudungun is not a general term for seaweed, but for a specific species, southern bull kelp or ‘cochayuyo’.
* Concepticon has JEWEL [1029](https://concepticon.clld.org/parameters/1029), but the Sound Comparisons: Mapudungun term is not for a precious stone, but a specific type of (women’s) jewellery in Mapuche culture.
Below is the list of Mapudungun lexemes for which I suspect it’s not worth adding a concept to Concepticon. For all of these, the Concepticon ID in Sound Comparisons: Mapudungun is left blank.

- [ ] Mapuche healing ceremony: ‘machitun’
- [ ] Mapuche ‘invocation’ ceremony: ‘ngillatun’
- [ ] Mapuche dish from animal blood
- [ ] bull kelp seaweed, ‘cochayuyo’
- [ ] toasted flour
- [ ] house-owner	
- [ ] landowner	
- [ ] get (sth.) right	
- [ ] thundery sky	
- [ ] (women’s) jewellery

**Comment by LinguList** [comment]
Thanks a lot! 

Can we turn this around, please? It should not be the way that we change concepticon and you change it on your side, as this is too inefficient, but rather that by adding a conceptlist TO concepticon that has a bibtex report and how to cite, you can propose concepts along with it?

The practice has been [recently described](https://calc.hypotheses.org/2225), and we have a good team of many reviewers. So if you propose a first conceptlist, call it "Sadowsky-2020-200" (or whoever is first author/editor), and this list is backed up by a reference so it can be identified with a resource, you can leave fields that don't have good links empty but also propose new definitions directly.

**Comment by LinguList** [comment]
So we await this as a PR, where you can also comment, and we can have discussions.

**Comment by AnnikaTjuka** [comment]
@PaulHeggarty @LinguList @chrzyki Would it be helpful, if I prepare a short presentation in a department meeting where I illustrate the process of adding concept lists? That might also be relevant for our colleagues who work in the field and want to add their data.

**Comment by LinguList** [comment]
@PaulHeggarty, @bibiko what is the status on this? Can you prepare a PR?

**Comment by PaulHeggarty** [comment]
We're working on a general finalisation of the whole Mapudungun database, which may have some minor implications for the export and Concepticon links.  We'd rather wait for this than do an export which might then have to be amended and updated.  So this is very close to being ready, but Scott is ill right now and we await some final details from him.   
In fact, from our perspective it would actually be more efficient to have as complete a list of Concepticon links as possible first time around, but I appreciate that your process works differently, so we'll add them as they become available, and then update.

**Comment by LinguList** [comment]
I am not sure, @PaulHeggarty, but I repeat the procedure, as it should work, since this is our normal workflow, to avoid misunderstandings: you have to publish your database, and along with this, we publish a concept list in concepticon, which you prepare, along with a pull request, in which you propose changes to concepticon. Then we discuss changes during our review process, then we modify or revise your PR (in fact: you revise it according to our review). Then we merge it. 

This is how it works. @SimonGreenhill and @xrotwang, I guess you agree that it should be done in this way, right?

**Comment by xrotwang** [comment]
License does not allow for annotation.
