### ISSUE TITLE
Update policy for modifications and changes to Concepticon

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#782]
We have large and small changes, and we should identify, before applying a change, to which category it belongs. My proposal is: For large changes, we should have approvals from more than half of the Concepticon's editors, and they need to wait until all editors had the chance to look at them. For small changes, three editors will be enough. Large changes are certain re-mappings that modify many lists, specifically also, since they impact on datasets that USE concepticon, such as CLICS, of which we will have to make a new version 3.1 now, after all the modifications have been applied. An example is the modification of the glosses in #332. Those who propose a PR should assess if it is "large" or "small" and choose reviewers accordingly.

**Comment by LinguList** [comment]
If we agree on this or a similar policy, we should update the information on the CONTRIBUTING etc.

**Comment by chrzyki** [comment]
Good idea. This can also partially be implemented with GitHub's branch protection rules (the `master` branch is protected now, etc.), where reviews for certain changes can be made mandatory before merging is allowed.

**Comment by LinguList** [comment]
Another practice, we should fix in our CONTRIBUTING rules for the
upcoming version is to collect important issues in the milestone
"upcoming".

So in general, we should work towards more rules for the next release
(after 2.3), since we are having a larger team now, and we need to make
sure to fix our contribution guidelines, as otherwise, it will be hard
to manage.

**Comment by chrzyki** [comment]
Talked with @AnnikaTjuka briefly as well about updating CONTRIBUTING. She'll do some refinements and I've got more in the pipeline for the guidelines as well. Should I ping you after we're done with that?

**Comment by LinguList** [comment]
Yes, please do so.

**Comment by chrzyki** [comment]
See also the discussion in https://github.com/concepticon/concepticon-data/pull/784 for a helpful list by @LinguList and paraphrases by @Kristina-Pianykh to refine policies.
