### ISSUE TITLE
Missing PDF for Walker2011

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#790]
[Walker-2011-100](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists.tsv#L284) lists `Walker2011` as `PDF` - but no such document has been added to `concepticondata/sources`. Can we add the doc - or just leave the PDF column empty?

**Comment by SimonGreenhill** [comment]
@chrzyki was looking into this one -- we can add the doc but it's all of the supplementary material. Will email it to you now.
