### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#793]
- [ ] Update info on how to add source PDF files (see #792)

**Comment by chrzyki** [comment]
PDF files still are and will be tricky due to the interaction with CDSTAR. It's not straightforward for contributors to add to that. Will think about this.

**Comment by chrzyki** [comment]
Ah, just saw the discussion in the PR. Will update the guidelines accordingly.
