### ISSUE TITLE
HELP (1897) and HELP (ASSISTANCE) (3467)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#796]
Do we need them both? 1897 seems favoured.

**Comment by LinguList** [comment]
Please do not delete new concepts, if you find them superfluous, rather link one to be the alias of another.

**Comment by AnnikaTjuka** [comment]
I thought the difference is:
HELP = e.g., _she helped him_ (action/process)
HELP (ASSISTANCE) = e.g., _with the help of the government_ (person/thing)

But maybe @Schweikhard could help here ;-)

**Comment by Schweikhard** [comment]
Yes, HELP is the action, HELP (ASSISTENCE) is the abstract object.

**Comment by Schweikhard** [comment]
The information on part of speech (i.e. action/process, person/other, property,...) is not displayed on the website version, is it?

**Comment by LinguList** [comment]
It is displayed. There's a drop-down, where you can even filter.

**Comment by chrzyki** [comment]
Thanks for clarifying! No action needed here I'd say.
