### ISSUE TITLE
LIVE (2309) and BE ALIVE (1422)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#797]
Both have the same definition. Might benefit from refinements?

**Comment by AnnikaTjuka** [comment]
This looks like a duplicate.

**Comment by AnnikaTjuka** [comment]
The mappings for LIVE are: 
Rzymski-2020-1624-1589 LIVE [english]  (But also: Rzymski-2020-1624-219 BE ALIVE [english])
Not sure why Savelyev-2020-254-122 live (v.) [english] is mapped to LIVE.

**Comment by Schweikhard** [comment]
LIVE is already marked as a duplicate of BE ALIVE.

Perhaps concepticon test could also test for whether anything is mapped to a retired concept?

**Comment by LinguList** [comment]
I think, this is accounted for in tests!
