### ISSUE TITLE
Fixing Hartmann-2013-162

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#799]
Sorry for not raising these issues earlier, but we'd need to
- rename the column `MANDARIN` to `CHINESE` (see https://github.com/concepticon/concepticon-data/pull/798#issuecomment-602007524)
- replace the values of the `RUSSIAN` column with counterparts in cyrillic; see attached
[russian.txt](https://github.com/concepticon/concepticon-data/files/4362586/russian.txt)

**Comment by xrotwang** [comment]
Probably, the effect of these changes should be controlled by checking the results of `concepticon make_linkdata`.

**Comment by chrzyki** [comment]
Oki, will prepare a PR for this!
