### ISSUE TITLE
How to add quotes?

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#804]
How should we add quotes in the descriptions of concepts (and lists) see https://github.com/concepticon/concepticon-data/pull/761#discussion_r384954814?

Some descriptions have quotations marks (""), e.g., 2348 CRAB. 
Others use (&quot;), e.g., 2976 VIOLENCE.

**Comment by chrzyki** [comment]
See also this issue https://github.com/concepticon/concepticon-data/issues/611 and this commit https://github.com/concepticon/concepticon-data/commit/40839aea734025f0e920e2deff7c91d5c99c8f1e, particularly @xrotwang's comments there.

**Comment by AnnikaTjuka** [comment]
Thanks @chrzyki !
So I'll add the "" back to the description of CRAB in #803 and I'll change the &quot; in the same way, right?

**Comment by chrzyki** [comment]
Yep, I think that's our best option. Particularly if in the long run this is done consistently everywhere.
