### ISSUE TITLE
Add Luangthongkum-2019-340

### ISSUE THREAD

**Issue by tresoldi** [concepticon/concepticon-data#814]
We need a concept list from Luangthongkum (2019) ("A View on Proto-Karen Phonology and Lexicon", [here](https://evols.library.manoa.hawaii.edu/bitstream/10524/52441/D01Luangthongkum2019view.pdf)) for the Lexibank `luangthongkumkaren` dataset.

I did a quick initial mapping at https://github.com/lexibank/luangthongkumkaren/blob/master/etc/concepts.csv

**Comment by LinguList** [comment]
Could you also add a NUMBER, @tresoldi? This is anyway required by
concepticon if you do the automated mapping.

**Comment by LinguList** [comment]
Ah, and once you do it, it'll also be easier if you stick to TSV. More
information, to make it easier for those who map, is the bibtex file
(where is it?) etc.

**Comment by tresoldi** [comment]
Done with https://github.com/lexibank/luangthongkumkaren/commit/6e1dc8b9059949847527c2c2abef7f6bb771b698 , file is now https://github.com/lexibank/luangthongkumkaren/blob/master/etc/concepts.tsv

As for the bibtex file, you mean the `sources.bib`? It's in `raw`, should I place it somewhere else? https://github.com/lexibank/luangthongkumkaren/blob/master/raw/sources.bib

**Comment by Kristina-Pianykh** [comment]
I'm brushing up the concept list now and it occurred to me that there are 340 items while the source claims the list contains 341 entries. Is it a mishap from the author's side or is there a missing concept in the tsv file?

**Comment by LinguList** [comment]
@tresoldi can answer this, I hope.
