### ISSUE TITLE
Consider collapsing "woods" and "forest"

### ISSUE THREAD

**Issue by SimonGreenhill** [concepticon/concepticon-data#818]
Most lists seem to use these interchangeably, and the definitions are the same but some lists are mapped to FOREST, and some to WOODS.

```
2311	WOODS	The physical world	A vegetation community dominated by trees and other woody shrubs, growing close enough together that the tree tops touch or overlap, creating various degrees of shade on the forest floor.
420	FOREST	The physical world	A vegetation community dominated by trees and other woody shrubs, growing close enough together that the tree tops touch or overlap, creating various degrees of shade on the forest floor.
```

**Comment by Schweikhard** [comment]
WOODS is already retired - strange it wasn't caught by #810

**Comment by LinguList** [comment]
I think because it is constantly handled correctly (#810 onnly has inconsistencies). It is just that we leave it in concepticon for mapping purposes and to remember that we already HAVE a synonym here.
