### ISSUE TITLE
Unconformed remappings for "to know" in Bodt-2019-664 and Lieberherr-2017-100

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#820]
Those two lists are both made by colleagues, representing languges they know very well, so the entries should have never been changed from "know (something)" to "KNOW", without consulting Tim directly, as he could just tell us.

I am raising this issue to emphasize, that:

1. we need to be extremely careful with bulk-edits, that involve the remapping of many different concept lists, as often, one may think one knows what is going on, but the lists have their specific history, and there are even almost "perfect" solutions here

2. always inform on the given lexibank repository about a bulk edit that affects a given list

In the future, I will further restrict these edits much more radically. An edit should only involve one remapping of a concept, and it should be agreed upon by three senior editors to whom this is brought up. Otherwise, we run danger of losing control.

This issue can be closed when:

- [ ] we have a definite answer from Tim on the meaning of "know" in both datasets (as it is the same languages, and he can tell us)
- [ ] the mapping is updated (unless Tim confirms the unspecific version of KNOW)

I have assigned this issue to almost everybody to bring this to your attention. I think it was very good we had all these discussions and also refinements of the data, don't understand me wrongly. But with the PRs on concepticon growing at such a paste, I have less chances to check what is being done, and sometimes, I (and other senior editors) still have the better overview, especially when the data comes from colleagues, so we must make the review process stricter, but this means I will need more time to also check everything thoroughly myself. 

If there are volunteers to ask Tim, I'll be glad, but I'll write to him as well, otherwise.

**Comment by MacyL** [comment]
I can write him a message to confirm

**Comment by LinguList** [comment]
Yes, thanks.

**Comment by tresoldi** [comment]
CC or ping me later, @MacyL , so I'll fix it there if necessary or prepare a PR.

**Comment by MacyL** [comment]
short answer : the author suggests to map "know" (Bodt-2019-664) and "to know" (Lieberherr-2017-100) to KNOW (SOMETHING) [1410].

long answer : the words **dɛn** or **dan** in Kho-Bwa languages means "know something". When it is referring as "know how", the word is in a specific descriptive compounds or loans.

**Comment by MacyL** [comment]
I will make a PR as soon as possible.

**Comment by CarolinHu** [comment]
Closing this since the KNOW issue was addressed and probably everyone had a chance to read the note by now.
