### ISSUE TITLE
New tags for NoRaRe datasets in Concepticon

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#823]
@LinguList It might be useful to add the tags `norms`, `ratings` and `relations` in Concepticon. As of yet, lists like [Desrochers-2010-330.tsv](https://concepticon.clld.org/contributions/Desrochers-2010-330) or [Verheyen-2019-1000.tsv](https://concepticon.clld.org/contributions/Verheyen-2019-1000) received the tag `ranked` in the absence of a fitting label.

**Comment by LinguList** [comment]
Yes, good idea. To start, one must add them to our metadata file on
concepticon, where tags and descriptions are stored. This should be
unintrusive, you could add them and make a PR, it should not destroy
anything, just open the possibility to add the tags later?

**Comment by AnnikaTjuka** [comment]
Ok, great! I'll make the PR at the beginning of next week.
