### ISSUE TITLE
General concept for BLOW

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#836]
Just saw that we have other Spanish glosses mapped to either BLOW (OF MOUTH) or BLOW (OF WIND). We should consider opening a general BLOW concept. 

_Originally posted by @AnnikaTjuka in https://github.com/concepticon/concepticon-data/pull/834/review_comment/create_

**Comment by AnnikaTjuka** [comment]
We have 102 lists mapped to BLOW (OF WIND) of which most have the gloss 'blow'. In my view, it does not make sense to open a new general BLOW concept now. This would mean that we'd have to transfer too many lists (of which probably some are rightfully mapped to BLOW (OF WIND)).

However, there are some glosses of other languages which do not seem to differentiate between [BLOW (OF WIND)](https://concepticon.clld.org/parameters/175) or [BLOW (WITH MOUTH)](https://concepticon.clld.org/parameters/176): _soplar_, 吹 and дуть

I guess we have the following options:
- Indicate a relation between the two concepts @Schweikhard 
- try to map the three glosses (Spanish, Chinese, Russian) consistently to either one of the concepts @LinguList @MacyL 
- leave it as is

**Comment by LinguList** [comment]
/soplar/, 吹 and дуть are all ambiguous, I'd say, pusten or wehen.

**Comment by Schweikhard** [comment]
I would nevertheless argue for a general concept - it could receive the current definition, and we would move anything there that is not clearly the wind blowing (in a lot of cases it is clear).

We _could_ also treat the current concept as the hyperonym as we seem to be doing currently, but it kinda has the wrong name for that.

**Comment by AnnikaTjuka** [comment]
True, having  BLOW (OF WIND) as a hyperonym is not the most elegant way. But I fear if we make a huge remapping (probably 50 lists) to a new BLOW concept we lose hand-curated instances where a list with 'blow' is rightfully mapped to BLOW (OF WIND).

**Comment by LinguList** [comment]
we could say: blow prototypically means "blow (of wind)", but where we
know, we link it to other concepts. We can also say: the three terms
mean the prototypical wind-blow (in most concept lists, I think this is
what they mean). Having a meta-concept is probably useful, but
re-linking all concepts may be less useful, yes.

**Comment by AnnikaTjuka** [comment]
I think we agree that there is no perfect solution here. Thus, I'd argue to leave the mappings as they are. And after a short discussion with @Schweikhard , we'd suggest to add a relation BLOW (OF WIND) narrower BLOW (WITH MOUTH).
