### ISSUE TITLE
Fix Holman-2008-100

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#843]
Trying to match the list [Holman-2008-100](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Holman-2008-100.tsv) to actual ASJP data is harder than it should be, because the `NUMBER` column contains the **stability rank** reported in the paper, **not** the number of the concept in the ASJP wordlists. This number is reported in the paper, too, as `# In list`. I'd propose to change `NUMBER` to this and add a column `RANK` with the current contents of `NUMBER`.

Trying to match concepts based on `ENGLISH` labels turned up another inconsistency (alas not on our side): The concept with number `51` appears sometimes as `breast` sometimes as `breasts` throughout the wordlists of ASJP. While this is not something we are responsible for, we might want to note this in the concept list.

**Comment by xrotwang** [comment]
@LinguList thoughts?

**Comment by xrotwang** [comment]
Just realized that - at least historically - the variation of glosses in ASJP wordlists is far greater. Here's the whole variation over ASJP versions 12-18:
```
1 {'yo', 'je', 'I', 'ego'}
2 {'tu', 'thou', 'you', 'we', 'tu, vos', 'tú'}
3 {'we two', 'we (incl.)', 'nous', 'we', 'nosotros', 'water', 'nos'}
10 {'name', 'many'}
11 {'un', 'unus', 'one', 'uno'}
12 {'deux', 'tree', 'dos', 'two', 'duo'}
18 {'person', 'road', 'homo, quidam', 'personne', 'persona'}
19 {'poisson', 'fisx', 'pez', 'fish', 'piscis'}
21 {'chien', 'perro', 'canis', 'dog'}
22 {'louse', 'pediculus', 'pou', 'piojo'}
23 {'arbor', 'árbol', 'arbre', 'arbol', 'tree'}
25 {'leaf', 'hoja', 'feuille', 'folium'}
28 {'peau', 'skin', 'piel', 'peaux', 'cutis, pellis'}
30 {'sanguis', 'sang', 'blood', 'sangre'}
31 {'%bone', 'bone', 'hueso', 'os'}
34 {'corne', 'cuerno', 'horn'}
39 {'auris', 'ear', 'oreille', 'oreja'}
40 {'oculus', 'eye', 'ojo', 'oeil'}
41 {'nasus, nares', 'nariz', 'nez', 'nose'}
42 {'tooth', 'mouth'}
43 {'dens', 'diente', 'tooth', 'dent', 'tongue'}
44 {'lingua', 'langue', 'thou', 'lengua', 'tongue'}
47 {'knee', 'genou', 'genu', 'rodilla'}
48 {'manus', 'mano', 'main', 'hand'}
51 {'breasts', 'sein', 'seno', 'breast', 'mamma'}
53 {'hígado', 'higado', 'el higado', 'liverp', 'foie', 'liver'}
54 {'drink', 'dring', 'beber', 'boire', 'drinK', 'bibere, potare'}
57 {'see', 'voir', 'ver'}
58 {'to hear', 'oir', 'oír', 'hear', 'audire, exaudire', 'entendre'}
61 {'mori, obire', 'die', 'mourir', 'morir'}
66 {'venire', 'come', 'venir'}
72 {'soleil', 'sun', 'sol'}
74 {'estrella', 'stella, sidus', 'star', 'etoile'}
75 {'water', 'aqua', 'agua', 'two', 'eau'}
77 {'piedra', 'pierre', 'lapis, saxum', 'stone'}
82 {'firek', 'feu', 'fire', 'fuego', 'ignis'}
85 {'semitas, trames, via', 'sendero', 'camino', 'person', 'road', 'path', 'route'}
86 {'mons', 'moundain', 'mountain', 'cerro', 'montagne', 'montaña'}
92 {'noche', 'nuit', 'night'}
95 {'lleno', 'plenus', 'full(ness)', 'lleno/a', 'full', 'plein'}
96 {'nouveaux', 'new', 'nuevo'}
100 {'nombre', 'name', 'name (noun)', 'nom'}
```

I guess we might want to add the non-english labels; `SPANISH`, `FRENCH` and `LATIN` could probably be sorted relatively easily.

And then there's a some worrying stuff (at least for the validity of ASJP):
- `3 {'we two', 'we (incl.)', 'nous', 'we', 'nosotros', 'water', 'nos'}`: Why is `water` in here?
- `10 {'name', 'many'}`
- `18 {'person', 'road', 'homo, quidam', 'personne', 'persona'}`: `road`?
- `75 {'water', 'aqua', 'agua', 'two', 'eau'}`: Ah, so I guess nw we know how `water` ended up in `3`.
- `85 {'semitas, trames, via', 'sendero', 'camino', 'person', 'road', 'path', 'route'}` ah, and the analog explanation for `road` above ...

**Comment by LinguList** [comment]
Oh, interesting.

**Comment by LinguList** [comment]
First: yes, the number is the number not the rank, I think this was originally an error.

**Comment by LinguList** [comment]
As to adding in different languages: if they don't have full coverage, it is probably less interesting, and they have also a lot of spelling errors, right? But we could add a column and call it "Glosses_in_Lists" or similar, with the glosses?

**Comment by LinguList** [comment]
And for todays ASJP, what about adding a new ASJP list to concepticon, dating it to 2020, where we include these cases? Numbers should still be added for the older list. But since the data has evolved, this information on the variation in glosses is new, and not related to the older paper, where they officially published their list.

**Comment by LinguList** [comment]
And yes, three languages, English, French, Spanish, should be possible for the Glosses in the new list. Would also be nice for asjp.clld.org, since they could provide concepts in three versions, etc.

**Comment by xrotwang** [comment]
@LinguList It's the other way round, unfortunately: The latest version removes all the variation. So if we'd want to include it in Cocepticon, it would only make sense for the older lists.

**Comment by xrotwang** [comment]
It sems a bit disingenuous if what may have been used as elicitation gloss is replaced with the English label in the final version of a wordlist. But then, not too much is known about the coding process in ASJP anyway.

**Comment by LinguList** [comment]
A pity. But as far as I know, the data curation process in ASJP was always bound to the numbers, the glosses were not paid much attention to, and right so, given that people would modify glosses, etc. It is like in STARLING and the ToB database, where each item has its number out of their list of 110 items.

**Comment by LinguList** [comment]
So Holman-2008-100 is a list true to its source. Concepticon has not conformed to this source completely, but misunderstanding ranks and numbers. But ASJP as a database may offer more gloss variation internally, yet the source Holman-2008-100 only gives the English gloss. So I'd say, before we do more work than we'll be thanked for, we fix the ranks and leave it at this?

**Comment by Kristina-Pianykh** [comment]
I would really appreciate if you could confirm the changes that need to be introduced to the list before I open a PR:

1. the current contents of `NUMBER` is the rank scores so I'll simply change the name of the column
2. the actual numbering of the items in the list can be found in `# In list` in the source so I'll put this data into a new column `NUMBER`.

**Comment by LinguList** [comment]
Yes, that's it.
