### ISSUE TITLE
New plant & animal concepts

### ISSUE THREAD

**Issue by CarolinHu** [concepticon/concepticon-data#850]
While working on the Steinthal list and browsing the NA section, I found some concepts from the natural domain that could be added to Concepticon.

- [ ] albatross
- [ ] ostrich
- [ ] stinger
- [ ] fishbone
- [ ] ivory
- [ ] date (tree or fruit)
- [ ] fern
- [ ] raspberry

For every concept above, at least (but mostly not more than) two concept lists exist which include it. The mappings and descriptions should of course be discussed in more detail in the respective PRs. But in general, are those concepts we would want to add?

**Comment by LinguList** [comment]
Nice. I'd welcome this a lot.
