### ISSUE TITLE
[New Conceptlist] Jackson-2019-26

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#852]
For completeness, we could also add this list from the Science paper:

```
ID	Concept
1	ANGER
2	ANXIETY
4	ENVY
5	FEAR (FRIGHT)
6	GLOOMY
7	GRIEF
8	HAPPY
9	HATE
10	HOPE
11	JOY
12	LOVE
13	PITY
14	PROUD
15	REGRET
16	SAD
17	SHAME
18	SURPRISED
19	WORRY
20	MERRY
21	DESIRE
22	GOOD
23	LIKE
24	BAD
25	WANT
26	HAPPINESS
```

**Comment by Kristina-Pianykh** [comment]
Is there a link to the source of the list? The title and the authors of the paper would do, too.

**Comment by LinguList** [comment]
sorry, all coming now ....

**Comment by LinguList** [comment]
Most bibtex's I mention are [here](http://digling.org/evobib/?bibtex=Jackson2019), simple rule: AuthorYear as key. 

```
@article{Jackson2019,
    author = {Joshua Conrad Jackson and Joseph Watts and Teague R. Henry and List, Johann-Mattis and Peter J. Mucha and Robert Forkel and Simon J. Greenhill and Kristen Lindquist},
    doi = {https://doi.org/10.1126/science.aaw8160},
    howpublished = {Draft article under review},
    journal = {Science},
    number = {6472},
    pages = {1517-1522},
    title = {Emotion semantics show both cultural variation and universal structure},
    url = {https://science.sciencemag.org/content/366/6472/1517},
    volume = {366},
    year = {2019}
}
```

The  study is based on emotion concepts. I have however also seen that the data has additional ratings for the concepts, which I now asked Joshua (first author) to supply. So ideally, we wait until we have them.

**Comment by LinguList** [comment]
[aggregated_emotions.csv.txt](https://github.com/concepticon/concepticon-data/files/4823381/aggregated_emotions.csv.txt)

I just received the aggregated emotions from Joshua C. Jackson, first author of the study. They have ratings for 20 out of the 26 concepts (since the study was done before the data were extended). So the remaining 6 can be left empty. 

When submitting this concept list, one should also add Joshua to the people to thank for providing data in our CONTRIBUTIONS.md for the next version (2.4) or concepticon.

**Comment by Kristina-Pianykh** [comment]
Thank you for providing the data! I'll add the list then and Joshua as a contributor in the same PR.

**Comment by Kristina-Pianykh** [comment]
@LinguList The paper mentiones  24 and not 26 emotion terms. I was looking for a table or listing of concepts to reflect the original ordering when I found this supplement: https://science.sciencemag.org/content/sci/suppl/2019/12/18/366.6472.1517.DC1/aaw8160_Table_S4.pdf.
Can I overtake the concepts from here (with the additional rating data you provided above)?

**Comment by LinguList** [comment]
Yes, this is a good idea. And yes: 24, not 26!
