### ISSUE TITLE
Johansson-2020-XX: New list of color terms in a phonetic study

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#859]
The article is here: https://www.cambridge.org/core/journals/language-and-cognition/article/color-sound-symbolism-in-natural-languages/537E325E594CFC227056D4FEA6BCD8E3

Supplement is here: https://osf.io/cu3bk/download

But it is difficult to read. I think it is best to just add this list with the color terms. But one should before this add the list by the same first author in #786, which is also interesting for lexibank and will show overlap with the lists by Carling.

**Comment by Kristina-Pianykh** [comment]
@LinguList there is a csv file with the 11 colors plus 11 columns with information on saturation, hue, munsell value, etc. but also the columns with the name "a" and "b", which seem difficult to interpret and are not discussed in the paper. Should I add then only the color concepts or some of the meta data, too?

**Comment by LinguList** [comment]
I think the data that we have in the paper (the RGB, color chip information, etc.) should be sufficient. If there's no explanation, we ignore it.
