### ISSUE TITLE
Concepticon 2.4.0 release

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#862]
Dear all,

we've accumulated a number of [fixes and corrections as well as additional lists](https://github.com/concepticon/concepticon-data/compare/v2.3.0...master) (18 as of right now, for a total of 328) in this cycle and since the [last milestone](https://github.com/concepticon/concepticon-data/milestone/10) and [last release](https://github.com/concepticon/concepticon-data/issues/743). Given that a number of these corrections are important for Lexibank datasets and in the spirit of pushing this project forward, releasing a Concepticon 2.4.0 in the 'near future' would be good.

If all of you, whenever your time allows, could have a look at

* [the 2.4.0 milestone](https://github.com/concepticon/concepticon-data/milestone/11)
* and [open issues](https://github.com/concepticon/concepticon-data/issues)

this would be good. Open issues can still be assigned to the 2.4.0 milestone should need be, so feel free to do so or let me know!

I've set July 10th as a deadline for this milestone which is of course by no means binding. However, sometime during 'the next couple of weeks' would be good I think.

**Comment by LinguList** [comment]
Yes, this sounds very good. We have a couple of lexibank datasets with almost completed concept lists that just need to be linked. So they are linked inside lexibank, but not to concepticon. And we have some borderline cases, such as, for example gerarditup in lexibank, which has a concept list that we could link, but the article won't appear before 2021, since it is accepted for Diachronica. If we knew it appears in the last 2020 issue, we could date it as 2020, but I tend to try to avoid now to re-name concept lists again and again (e.g., also joophonosemantic, where the concept list is 2020 now instead of 2019, etc.).

Concrete lists, that could be done immediately: 

* [pharaochoracolaztecan](https://github.com/lexibank/pharaocoracholaztecan/blob/master/etc/concepts.tsv). 
* [ratliffhmongmien](https://github.com/lexibank/ratliffhmongmien), may need some refinement
* [bdpa](https://github.com/lexibank/bdpa/blob/master/etc/concepts.tsv), additional concepts can be added
* [simsrma](https://github.com/lexibank/simsrma/blob/master/etc/concepts.tsv), needs a bit of work, but basically easy to do
* [luangthongkumkaren](https://github.com/lexibank/luangthongkumkaren/blob/master/etc/concepts.tsv)

I'll also move lists to our milestones.

**Comment by Kristina-Pianykh** [comment]
The concept list for simsrma is already in the Concepticon (see #833).

I'd prefer to begin with the lists now, starting with luangthongkumkaren.

**Comment by LinguList** [comment]
Nice, thanks for clarifying, @Kristina-Pianykh, and yes: starting to add
the lists now is a good idea!

**Comment by chrzyki** [comment]
@xrotwang a new Concepticon release in the near future might be good (I dropped the ball on pushing v2.4.0 earlier, apologies). Do you think a v2.4.0 would still be reasonable? I think the directory & pyconcepticon refactorings are still a little bit further down the road.

**Comment by chrzyki** [comment]
If we aim for v2.4.0 soon™ I'd say we focus on smaller outstanding issues (gloss refinements, small issues).

**Comment by xrotwang** [comment]
So in terms of new concept lists we are all good?

Christoph Rzymski <notifications@github.com> schrieb am Di., 20. Okt. 2020,
18:22:

**Comment by chrzyki** [comment]
I'd say so, yeah, but that's maybe where the others would like to chime in.

**Comment by LinguList** [comment]
We sure have enough. We also have our precedence for cases like
Fabrício's Tupían data: they are first published as CLDF in a
pre-release, and then adjusted with full concepticon mapping, once the
paper appeared. I think that this is solid.

We should only wait to close few of the 2.4 milestone issues and also
the last PRs (including the translated list of German glosses in IDS,
which I consider important).

**Comment by chrzyki** [comment]
Okay, thanks, I'll revisit the milestones and then I think we should go for a release by end of next week.

**Comment by chrzyki** [comment]
Dear all,

we're aiming for a release tomorrow. Could you please check the [2.4 milestone](https://github.com/concepticon/concepticon-data/milestone/11) and check what you would like to see tackled before the release? Feel free to move non-urgent things to the 3.0 milestone.

**Comment by LinguList** [comment]
I just fixed the ones, so we have only some 6 milestones left, with the PR of #976, the #970 could also be tackled, and one more milestone as well (the issue on call by name and be called).

**Comment by chrzyki** [comment]
Very nice, thanks! I'll have a look at the remaining issues first thing in the morning.

**Comment by chrzyki** [comment]
Okay, release this afternoon if all goes well? Please everyone who has time check the open PRs (https://github.com/concepticon/concepticon-data/pulls) and the [2.4 milestones](https://github.com/concepticon/concepticon-data/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4). The updated WALL mapping (see discussion [here](https://github.com/concepticon/concepticon-data/pull/992)) should also go into 2.4, imo.

**Comment by LinguList** [comment]
We have to adjust the list of editors as well.

This time, I suggest to:

1. include Tiago,
2. include Carolin

This means, description in .zenodo.json should be adjusted:

```
"description": "<p>List, Johann Mattis &amp; Rzymski, Christoph &amp;
Greenhill, Simon &amp; Schweikhard, Nathanael &amp; Pianykh, Kristina
&amp; Tjuka, Annika &amp; Wu, Mei-Shin &amp; Hundt, Carolin &amp;
Tresoldi, Tiago &amp; Forkel, Robert (eds.) 2020. Concepticon. A
Resource for the Linking of Concept Lists. Version 2.4.0. Jena: Max
Planck Institute for the Science of Human History. Available online at
https://concepticon.clld.org</p>",
```

**Comment by xrotwang** [comment]
`.zenodo.json` is created running `concepticon citation`. So this will be taken care off automatically.

**Comment by LinguList** [comment]
Ah, okay, so concepticon citation, the command should be adjusted then.

**Comment by xrotwang** [comment]
What do you mean by "adjusted"? It is documented in `RELEASING.md`.

**Comment by LinguList** [comment]
Bad wording: releasing does not document WHO should be included, so
including Tiago and Carolin is something we should not forget.

**Comment by LinguList** [comment]
I just saw the citation.py, very cool, so we only need to modify the
markdown with contributors... sorry, had not really paid attention to
the code before...

**Comment by chrzyki** [comment]
https://github.com/concepticon/concepticon-data/releases/tag/v2.4.0

Thanks everyone and thanks @xrotwang for releasing!
