### ISSUE TITLE
RIPE OR COOKED

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#865]
I would suggest that we consider introducing the umbrella concept of RIPE OR COOKED based on the following glosses:

|ID|GLOSS|CURRENT MAPPING|
|--|--|--|
|Krisadawan-2000-210-176|ripe/well-cooked|RIPE|
|Matisoff-1978-200-167|ripe/well-cooked|RIPE|
|Sidwell-2015-200-105|ripe/cooked|RIPE|
|Luangthongkum-2019-340|ripe, cooked|not in the Concepticon yet|

**Comment by AnnikaTjuka** [comment]
Yes, that would make sense from my perspective.
