### ISSUE TITLE
Mountain-1978-375: On the origin of the Huber list

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#866]
This publication lists a concept list of 375 items, which made it into the Huber list:

https://www.sil.org/system/files/reapdata/13/59/19/135919534926889679134861463713901175353/24689.pdf

I have not read it completely yet, but it seems the list is a combination of Swadesh and Rowe (whom I don't know). So ideally, finding Rowe is important and adding the list, and then also adding this list as the "mother" of the Huber list.

**Comment by LinguList** [comment]
@chrzyki, @Kristina-Pianykh, @CarolinHu, this concept list may be important to be added for 2.4, but it will require some digging in the actual literature, since it seems that this mixed list of Swadesh and one more list later turned into the Huber and Reed list (Huber-1992-375). I'd very much like to add this list for Concepticon 2.4, or otherwise give it some higher priority, so that this is not forgotten, since the Huber-list plays an important role in South American language documentation. 

@thiagochacon, you pointed me indirectly to this list: do you have a good account on the origin of the Huber and Reed list?

If need be, I'll read the text myself (I think it is all in Spanish) and try to dig out the sources (especially the Rowe list).

**Comment by thiagochacon** [comment]
All I know is what is what is said in the preface of the three attached publications (I am seding two + the one from this thread). 

The Swadesh and Rowe list is said to have been developed from Curt Nimuedaju's 1927 concept list (another South American important resource we should try to get into concepeticon), Swadesh (?300) list andd John Rowe list (which was a specialist in Peru and the Andes). 

It seems, though, that the credit for putting together of the Swadesh-Rowe list is of SIL linguists.

Here is a reference to the work of John Howland Rowe
https://www.lib.berkeley.edu/ANTH/emeritus/rowe/pub/index.html

He is also on wikipedia
https://en.wikipedia.org/wiki/John_Howland_Rowe

[huber-reed_palabras-colombia1992_o.pdf](https://github.com/concepticon/concepticon-data/files/4884521/huber-reed_palabras-colombia1992_o.pdf)

[lista de palabras 10 idiomas del ecuador.pdf](https://github.com/concepticon/concepticon-data/files/4884516/lista.de.palabras.10.idiomas.del.ecuador.pdf)

**Comment by LinguList** [comment]
thanks for the update, @thiagochacon, much appreciated!

**Comment by CarolinHu** [comment]
I can add the Mountain list, perhaps adding a column indicating the original number in Swadesh-Rowe, which the linked document follows?

A preliminary search on Rowe did not reveal much, there seems to be no (easily findable) master list of Swadesh-Rowe items used by SIL. Neither Swadesh nor Rowe are quoted in the few documents I've seen so far (often field notes), including the Mountain list, and documents sometimes report using a "modified" Swadesh-Rowe list. I don't know whether this is THE Rowe list that is so often referred to, but we could link the list from #346 for the time being.

**Comment by CarolinHu** [comment]
Closing this now since we have a separate issue on Rowe.
