### ISSUE TITLE
Duong-2020-100: new Swadesh list used for documentation of La Chí languages in Vietnam

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#869]
This is a small wordlist, but interesting and a typical use-case for Swadesh lists. 

I attach the PDF here.

[Duong2020.pdf](https://github.com/concepticon/concepticon-data/files/4841864/Duong2020.pdf)

The article itself is:

```
@incollection{Duong2020,
  author = {Duong, Thu Hang and Nguyen, Thu Quynh  Nguyen, Van Loi},
  title = {The language of the La Chí people in Bàn Díu commune, Xín Mần district, Hà Giang province, Vietnam},
  booktitle = {Studies in the anthropology of language in Mainland Southeast Asia},
  year = {2020},
  editor = {Enfield, N. J. and Jack Sidnell and Charles H. P. Zuckerman},
  pages = {132-146},
  publisher = {University of Hawaii Press},
  address = {Honolulu}, 

}
```

**Comment by agricolamz** [comment]
Double dash for pages.

**Comment by LinguList** [comment]
not in our version, double dash is if you want to write a pdf document in latex, compare how we do it normally in concepticon.

**Comment by agricolamz** [comment]
Oh, I didn't know, thanks

**Comment by LinguList** [comment]
no deal (I tend to always write my bibtex with one "-" and normalize
automatically when needed, given the inconsistencies that people write
bibtex: https://digling.org/evobib/, luckily, this is very easy nowadays )
