### ISSUE TITLE
BRAN vs. CHAFF (HUSK) definitions

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#870]
BRAN and CHAFF (HUSK) appear identical in their meanings as they are defined in the Concepticon. Compare:

|Concept|Concepticon definition|
|---|---|
|CHAFF (HUSK)|The outer shell or coating of a seed.|
|BRAN|The hard outer layers of cereal grain. It consists of the combined aleurone and pericarp.|

A closer look, however, reveals that 'bran' is the 'the broken **coat of the seed**' while 'chaff' - 'the inedible parts of a grain-producing **plant**, including husks and leaves'. The CHAFF is therefore more likely to be a hypernym for BRAN but the specification (HUSK) narrows the meaning down again to the outer covering of the seed.

You can see the confusion by the glosses mapped to these concepts. E.g., Chinese 糠 is mapped to both.

Or I may be overthinking and these concepts are simply duplicates and one of them should be retired.

**Comment by LinguList** [comment]
In German, one is clearly "Spreu" (i.e., chaff), and the other "Hülse", i.e. bran.

And they seem to be mixed and should be remapped. 

The definition for chaff is better in Wikipedia German: https://de.wikipedia.org/wiki/Spreu

Chinese 糠 is Chaff.

**Comment by Kristina-Pianykh** [comment]
So CHAFF is more general, compared to BRAN. I can modify the definition to make the distinction more clear but the name of CHAFF (HUSK) is confusing by itself because HUSK seems to be the same as BRAN.

**Comment by LinguList** [comment]
Not sure: chaff is what you get when you go for the seeds of wheat and
the like, so it is leftovers, that are then fed to the animals,
something rather concrete. Husk is the hull (Hülle) of some vegetables,
like maize, etc., as far as I understand.

**Comment by Schweikhard** [comment]
The chaff surrounds the bran and the bran is the peel of the grain (and is part of the grain).
So it's different parts of the same plant, no broader/narrower or hyperonymic relation.
The definitions we have are actually accurate, but easily misunderstood.

I think all our elicitations glosses make it clear which of the two is meant (at least as long as the English translations from Chinese are ignored).
Is 粗糠 mapped correctly to RICE HUSK? And is 谷壳 the same as 糠?
In that case, the only difference the mapped glosses seem to make that we don't yet make is between bran in general (麩子) and wheat bran (麦麸) or fine bran (细糠).
And we also have fine chaff and coarse chaff (both unmapped).

**Comment by LinguList** [comment]
Is this solved now? @Schweikhard and the others, do we have consistent mappings?

**Comment by Schweikhard** [comment]
Νο, https://concepticon.clld.org/values/Huang-1992-1820-457 still needs to be remapped to CHAFF (HUSK) and https://concepticon.clld.org/values/Huang-1992-1820-458 to BRAN.
Perhaps someone fluent in Chinese could look at the rest again (also, see my questions in my previous comment), but I think everything else is mapped to the correct option.
