### ISSUE TITLE
Citation erata

### ISSUE THREAD

**Issue by HughP** [concepticon/concepticon-data#873]
Greetings, 
Quite randomly I was looking through your citations and noticed that the list at https://concepticon.clld.org/sources/savelyev2020

has a missing year when referencing the publication, an no link. I think the article described is https://doi.org/10.1093/jole/lzz010

**Comment by LinguList** [comment]
Year also missing in evobib: http://digling.org/evobib/?bibtex=Savelyev2020 will change this as well, thanks!

**Comment by SimonGreenhill** [comment]
fixed in #973

**Comment by chrzyki** [comment]
Done and merged, thanks.
