### ISSUE TITLE
citation erata 2

### ISSUE THREAD

**Issue by HughP** [concepticon/concepticon-data#874]
Very very randomly,

I was looking at another list and it's source iis cited as https://concepticon.clld.org/sources/matisoff1978. This item is available online at: https://stedt.berkeley.edu/pubs_and_prods/Matisoff_1978_Variational-Semantics-TB.pdf

which could be added to your citation, along with the book's series (Occasional papers of the Wolfenden Society on Tibeto-Burman Linguistics vol.VI), and the book's location of publisher (Philadelphia, USA), and the book even has an ISBN: 0-915980-85-1

**Comment by LinguList** [comment]
ISBN is not needed, we don't have it, but address should usually be mentioned. I do not insist on URL links, who knows how stable they are, so DOI, if available. I just saw that Matisoff is also missing the location in [EvoBib](http://digling.org/evobib/?bibtex=Matisoff1978), which mirrors most of Concepticon's references, so I'll also change it there, thanks!
