### ISSUE TITLE
RDF download without link to concepts

### ISSUE THREAD

**Issue by HughP** [concepticon/concepticon-data#875]
Greetings,

I am reading the RDF files that are made available for download.

by way of example I am looking at the resource description for item one on Matisoff 1978 https://concepticon.clld.org/contributions/Matisoff-1978-200.

```
    <rdf:Description rdf:about="https://concepticon.clld.org/values/Matisoff-1978-200-1">
        <rdfs:label xml:lang="en">belly (exterior) [english]</rdfs:label>
        <dcterms:identifier>Matisoff-1978-200-1</dcterms:identifier>
    </rdf:Description>
```
I would have expected there to be some sort of link (described data) connecting the ID, the English, and the Concept set.

The Concept set seems to be missing from the RDF completely. Or am I missing something? Note: the `.xls` file does include the concept set.

**Comment by xrotwang** [comment]
The RDF data isn't really complete. Also, we are moving away from regarding
the web app as the standard place to retrieve the data, and instead
encourage users to interact with the raw data in
https://github.com/concepticon/concepticon-data

HughP <notifications@github.com> schrieb am Mi., 1. Juli 2020, 13:08:

**Comment by LinguList** [comment]
BTW: we published some examples on how to use our tools at [calc.hypotheses.org](https://calc.hypotheses.org). You can find quite a few articles on Concepticon there: https://calc.hypotheses.org/tag/concepticon
