### ISSUE TITLE
Add Williamson-1973-134

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#878]
See past discussion of this in https://github.com/concepticon/concepticon-data/issues/278 and related Lexibank dataset in https://github.com/lexibank/blenchbenuecongo and the relevant concept list in https://github.com/lexibank/blenchbenuecongo/blob/master/etc/concepts.csv.

Ideally, the existing mappings are double-checked again and updated where necessary (due to new concepts in Concepticon etc.) and a couple of mappings can be refined I think (language: tongue is mapped to TONGUE etc.).

**Comment by CarolinHu** [comment]
I can link this list to Concepticon. Since the English glosses are sometimes much broader and often duplicated, the mappings should rather be based on the French glosses, is that correct?

**Comment by chrzyki** [comment]
I would think so, yes, but I don't have access to the source data (i.e. the two publications ComparaLex based this on). @LinguList probably knows more.

**Comment by LinguList** [comment]
I am afraid I do not know more. Is the concept list from comparalex? Then we should look into the original, right? Comparalex usually gives sources, or is the website dead now?

**Comment by chrzyki** [comment]
* Williamson, Kay and Kiyoshi Shimizu (eds.). 1968. Benue-Congo Comparative Wordlist Volume I. Ibadan, Nigeria: West African Linguistic Society.
* Williamson, Kay (ed.). 1973. Benue-Congo Comparative Wordlist, Volume II. Ibadan, Nigeria: West African Linguistic Society.

And just as I was writing this I rememberd to look this up in our library. Seems like the books are here. I'll get them and report back.

**Comment by chrzyki** [comment]
Hm, while the French glosses are provided in the source material, at least after a first glance, it seems to me that this was only done 'in addition' to the English glosses. It is also noteworthy that there are only 117 glosses (i.e. the list IDs on ComparaLex), and not 134 (row numbers on ComparaLex), in the two volumes. The additional 17 come from 'doubles' where ComparaLex expanded on complex glosses in the source material it seems.

**Comment by LinguList** [comment]
Yes, comparalex is doing its own thing out of the data, so the best strategy is to go with the real source.

And then: we already discussed, if we have a digital version of a dataset, but it is not true to the source, we can have concept lists with an extra column defining an alias. Now, I think we should use the formula LANGUAGE_ALIAS, like ENGLISH_ALIAS, although this is even not that important.

**Comment by chrzyki** [comment]
So @CarolinHu I'd suggest you go for the 117 glosses and I'll add the ALIAS wherever applicable.

**Comment by CarolinHu** [comment]
Okay! I will prepare the list and create a PR when Mountain is merged. Or do you want the file beforehand, add the aliases and then I'll make a PR?

**Comment by chrzyki** [comment]
Thanks! Feel free to prepare the PR, we can discuss & add the aliases in the PR.
