### ISSUE TITLE
tree trunk and trunk of tree in concepticon

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#880]
I think, we have already retired one of them, but we need to check for 2.4, that trunk of tree is really not represented any more and marked as an alias of tree trunk. In CLICS, they both still occur, which is not useful.

**Comment by Kristina-Pianykh** [comment]
The only list mapped to the retired TREE OF TRUNK is Xiao-2012-213-43. I'll move it to TREE TRUNK after my PR is merged. Quite strangly, as I've just noticed, the definition of TREE OF TRUNK refers to the torso.

**Comment by chrzyki** [comment]
`776` Has been remapped in Xiao and is not in use any more.
