### ISSUE TITLE
Duplicate concept SPECTACLES and GLASSES

### ISSUE THREAD

**Issue by CarolinHu** [concepticon/concepticon-data#881]
Based on the comments in PR #879.
Judging from their definitions, it seems that 1898 SPECTACLES and 2292 GLASSES could be collapsed by retiring one of them.

**Comment by AnnikaTjuka** [comment]
Based on our convention to retire the "younger" concept: 2292 would be added to the REPLACEMENT_ID column of 1898 SPECTACLES.

**Comment by AnnikaTjuka** [comment]
If the latter added concept should be retired then we need to add 1898 to the REPLACEMENT_ID column of 2292 GLASSES: 


ID | GLOSS | SEMANTICFIELD | DEFINITION | ONTOLOGICAL_CATEGORY | REPLACEMENT_ID
-- | -- | -- | -- | -- | --
2292 | GLASSES | Basic actions and technology | Frames bearing lenses worn in front of the   eyes used for vision correction. | Person/Thing |  1898

(I deleted the other comment where I had it the other way around.)

**Comment by Schweikhard** [comment]
Based on the current replacement IDs, either way round should work.
If only one direction works, several replacement IDs need to be corrected.
