### ISSUE TITLE
please add what's required for 2.4b1

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#886]

**Comment by LinguList** [comment]
The good thing is: we have this already. And we have all authors, editors, etc. I might only want to have a check on the .zenodo.json (or add it if it is not there yet).

**Comment by LinguList** [comment]
So the most important part were the new datasets added by @AnnikaTjuka in the past.

**Comment by AnnikaTjuka** [comment]
I have pushed all the necessary changes with regard to NoRaRe data sets in the last weeks. So now more open issues from my side.
