### ISSUE TITLE
Update Chan's Numerals concept list to 133 items

### ISSUE THREAD

**Issue by Bibiko** [concepticon/concepticon-data#888]
Update Chan-2019-128 to Chan-2019-133 - attached is the new tsv
[Chan-2019-133.tsv.txt](https://github.com/concepticon/concepticon-data/files/4953057/Chan-2019-133.tsv.txt)

**Comment by LinguList** [comment]
Okay, so you can prepare a nice PR, with a retraction list, that retires numerals in the [oldest version on concepticon](https://concepticon.clld.org/contributions/Chan-2019-95). Old IDs go into retired.json (should be clear enough the file structure), and we'd also need a formal PR.

**Comment by chrzyki** [comment]
See https://github.com/concepticon/concepticon-data/pull/889.
