### ISSUE TITLE
Updated list from Loukotka-1968-45

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#894]
I just found a book by Loukotka from 1968: https://archive.org/details/classificationof0007louk

There, the introduction by another person has the list. I could not find another source but archive.org for a digital version of the book. 

But ideally, the list should be checked against our Rowe-Loukotka. 

One can "rent" the book for one hour from Archive org. Ideally, we would also order it via Fernleihe and make a scan from the first chapter, or see if we have the book in our library already (!).

**Comment by LinguList** [comment]
![Screenshot_2020-07-30 Classification of South American Indian languages Loukotka, Čestmír, 1895-1966 Free Download, Borro (1)](https://user-images.githubusercontent.com/2916210/88887742-48890a00-d23d-11ea-9fbd-5fc3b273d6dc.png)

**Comment by Kristina-Pianykh** [comment]
[loukotka_c_classification_of_south_american_indian_languages (1).pdf](https://github.com/concepticon/concepticon-data/files/5001682/loukotka_c_classification_of_south_american_indian_languages.1.pdf)

I've found the source. Here are the relevant pages with the total of 45 words.

**Comment by Kristina-Pianykh** [comment]
This is rather a comparative list combining both Loukotka's lsit and the one by Brinton 1891 (21 words).

Hmm, Loukotka's list is exactly the same as the one we've just added ([Loukotka-1954-45](https://github.com/concepticon/concepticon-data/pull/893)). Apparently it dates back to "Klassifikation der südamerikanischen Sprachen" (1944) where the list wasn't published at first. Interestingly, the footnote says the list was retrieved from Rowe 1954 (p. 24).
