### ISSUE TITLE
QUIVER (995) incorrectly replaced by SHIVER (52)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#898]
`QUIVER` (995) (container to store arrows) is [incorrectly replaced](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/concepticon.tsv#L996) by the verb 'to shiver'. This also has lead to a number of (potential? feedback appreciated) problematic mappings:

- purely based on the context, I suspect that [Swadesh-1950-165-157](https://concepticon.clld.org/values/Swadesh-1950-165-157) is not the verb but the actual `QUIVER`
- likewise, the Hausa (kwari) and context in [Kraft-1981-434-236](https://concepticon.clld.org/values/Kraft-1981-434-236) refer to the `QUIVER`
- more info needed for [Dunn-2011-146-81](https://concepticon.clld.org/values/Dunn-2011-146-81) (I think it's the verb)
- more info needed for [Bodt-2019-664-382](https://concepticon.clld.org/values/Bodt-2019-664-382) (I think it's the verb)

**Comment by LinguList** [comment]
For Swadesh, the source should be consulted, for Bodt and Dunn, we should contact the authors.

**Comment by chrzyki** [comment]
I've checked the Swadesh article but, as far as I can tell, it doesn't give any information on the intended meaning.

**Comment by chrzyki** [comment]
@AnnikaTjuka and @Schweikhard, could I ask for your help/input/opinion on this?

**Comment by AnnikaTjuka** [comment]
The mapping of Swadesh-1950-165-157 indeed seems to refer to QUIVER, not SHIVER.

In the case of Kraft-1981-434-236, I found a [translation](https://glosbe.com/ha/en/kw%C3%A0r%C4%AB) that indicates that the mapping to SHIVER is correct.

**Comment by chrzyki** [comment]
> The mapping of Swadesh-1950-165-157 indeed seems to refer to QUIVER, not SHIVER.
> 
> In the case of Kraft-1981-434-236, I found a [translation](https://glosbe.com/ha/en/kw%C3%A0r%C4%AB) that indicates that the mapping to SHIVER is correct.

Curious, I checked `kwari` here:

https://hausadictionary.com/kwari -> quiver for arrows.

**Comment by chrzyki** [comment]
> The mapping of Swadesh-1950-165-157 indeed seems to refer to QUIVER, not SHIVER.
> 
> In the case of Kraft-1981-434-236, I found a [translation](https://glosbe.com/ha/en/kw%C3%A0r%C4%AB) that indicates that the mapping to SHIVER is correct.

Ah, heh, the translation on Glosbe is pulled *from* Concepticon, taking the (presumably) wrong mapping to SHIVER.

**Comment by AnnikaTjuka** [comment]
Ah ok, so `kwàrī` is not necessarily the correct translation? I found that there seem to be more than one `kwari`, but written differently: kwàrī, kwari, kwárìi

**Comment by chrzyki** [comment]
This one also matches the diacritics/intonation:

![kwari](https://user-images.githubusercontent.com/4689035/97155329-7ff04f80-1775-11eb-93ec-8a077b959cf2.png)

**Comment by AnnikaTjuka** [comment]
I see. Then it should be remapped.
Regarding the Dunn data, I just found a statement that the list is based on Swadesh. 
Regarding the Bodt data, I asked @MacyL for her help.

**Comment by chrzyki** [comment]
Thank you!

**Comment by AnnikaTjuka** [comment]
Bodt-2019-664-382 _quiver_ can be mapped to QUIVER.

**Comment by chrzyki** [comment]
Thank you for clarifying!
