### ISSUE TITLE
WASH (CLOTHES) (3434) and LAUNDER (2503)

### ISSUE THREAD

**Issue by chrzyki** [concepticon/concepticon-data#902]
Can those two be merged/one be replaced?

**Comment by AnnikaTjuka** [comment]
Yes, I think they are duplicates. 洗(衣服) is mapped to WASH (CLOTHES) in Castro-2010-511-188 and to LAUNDER in Castro-2015-608-349.  And the translation for _laver (linge)_ is also 'do laundry/wash clothes'.
