### ISSUE TITLE
Missing column in Carling-2019-100

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#905]
The data in Concepticon seem to lack the column 'Classification' found in the [source list](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0223588). I would vote to add it if it wouldn't have drastic consequences on other data in case the list is used somewhere else.

**Comment by LinguList** [comment]
It doesn't have many consequences, so I think it is nice, if this can be done.

**Comment by chrzyki** [comment]
Done in https://github.com/concepticon/concepticon-data/pull/906.
