### ISSUE TITLE
Add Gerardi-2020-245

### ISSUE THREAD

**Issue by xrotwang** [concepticon/concepticon-data#912]
Based on
https://github.com/lexibank/gerarditupi/blob/master/etc/concepts.tsv
after
https://github.com/lexibank/gerarditupi/issues/15 is resolved.

Note that there are concepts mapped to multiple Concept sets currently.

**Comment by xrotwang** [comment]
Citation:

> Ferraz Gerardi, Fabrício and Reichert, Stanislav (2020) The Tupí-Guaraní Language Family: A Phylogenetic Classification. To appear in Diachronica.

**Comment by LinguList** [comment]
> Note that there are concepts mapped to multiple Concept sets currently.

Yes, the automated mapping should be resolved by Fabricio...

**Comment by LinguList** [comment]
but we can also do it, otherwise.

**Comment by LinguList** [comment]
I see now, so the concept list needs to be updated in any case. @CarolinHu or @Kristina-Pianykh, I do not know to which degree you are firm with how to use pyconcepticon in Python scripting now, but if you ARE interested in learning, I could write a script that uses the concept list of Fabricio, it will add the missing concepticon glosses to verify, and you could then submit the data (and also correct potentially wrong mappings or add ones, e.g., "urinate" is empty, but we sure have the concept, etc.). If you do not have time, do not worry.

**Comment by Kristina-Pianykh** [comment]
My laptop just crashed (great timing), I’ll get back to you as soon as I‘ve got it fixed.

**Comment by Kristina-Pianykh** [comment]
So what needs to be done, as far as I understood, is to update the list in found at https://github.com/lexibank/gerarditupi/blob/master/etc/concepts.tsv based on https://github.com/lexibank/gerarditupi/blob/master/raw/Aligned_matrix_lexical.csv, is this correct? 

I would also appreciate if someone could send me the source.

**Comment by LinguList** [comment]
It is a bit more complicated. First, we have to wait for the authors to
update the concept list or the original data, as there is one issue.
I'll get in touch with the authors and ask them to look into this, so we
can start updating their mappings.
