### ISSUE TITLE
Gauchat-1925-480: updates

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#916]
Hans Geisler just provided updates for the Gauchat list. 

There are general instructions, like to delete all cases of "some" (as it is no true partitive). And there are suggestions for modifications.

I paste them below.

**Comment by LinguList** [comment]
Chart | French 			gloss | English 			gloss | Add & 			Corr | Explanation 			(HG)
-- | -- | -- | -- | --
11 | chaque | each | every | ‘It 			rains every day’ (see EVERY (EACH))
13 | hier | yesterday | Hier | Beginning 			of a sentence in upper case
13 | hier | yesterday | Yesterday | Beginning 			of a sentence in upper case
36 | du 			tonnerre | from the 			thunder | of the 			thunder | (?) ‘fear 			from the thunder’
42 | Il fait | It is (2) | It is | (?) Why ‘(2)’ in En 			gloss
70 | du 			village | of the 			village | to the 			village | (?) 			‘close of the village’
76 | est | is | is of | (?) ‘the 			wall is (made) of stone’
80 | large | broad | wide | (?) see: 			BROAD
82 | est 			commencé | has 			started | is 			begun | (?) close 			gloss
84 | (est) 			commencée | (has) 			started | (is) 			begun | (?) close 			gloss
86 | (sont) 			commencées | have 			started | (is) 			begun | (?) close 			gloss, parenthesis
90 | est 			dressé | is leaned | is set | (?)
92 | le faîte | the top | the 			ridge | (?)
101 | On a | We have | One 			has | (?) close 			gloss
115 | (un) 			fléau | (a) 			plague | (a) 			flail | Wrong 			metaphorical meaning chosen
119 | (une) 			cuve | (a) tank | (a) 			tub | (?) see 			BARREL
120 | (un) 			pétrin | (a) 			trouble | (a) 			chest | Wrong 			metaphorical meaning chosen
133 | “des” 			pantalons |   | « des 			» pantalons | French 			quotation marks
133 | “des” 			pantalons | some 			pants | trousers | English 			gloss preferable
135 | (de la) 			toile | (some) 			linen | linen | (?) Why 			‘(some)’, see also following ch.
142 | Il a une | it has 			one | it has 			a | (?) Why a 			numeral ‘one’
147 | Le char | The 			vehicle | The 			cart | (?) 			VEHICLE is the generic term
158 | Il faudra | one must | one 			will have to | Future 			form of ‘il faut’
160 | tondre | mow | shear | ‘to 			shear a sheep’; (?) MOW
161 | les 			brebis | the ewes | the 			sheap | (?) 			depends on who has been sheared
162 | racérer | sharpen 			(?) | scrape | Metonymic 			shift: action to result
164 | battre en 			grange | beat in 			the barn | thresh 			in the barn | Special 			meaning of ‘battre le blé’
170 | la terre | the earth | the 			soil | (?) ‘turn 			the earth’; see EARTH (SOIL)
177 | (est) 			vendue | (is) sold 			(feminine) | is 			sold | Delete 			morph. feature (feminine)
180 | Il est 			cher | It is 			expensive | He is 			expensive | See 181
181 | (Elle 			est) chère | (she is) 			expensive | (She 			is) expensive | Beginning 			of a sentence in upper case
182 | (elles 			sont) chères |   | (Elles 			sont) chères | Beginning 			of a sentence in upper case
182 |   | (they 			are) expensive | (They 			are) expensive | Beginning 			of a sentence in upper case
183 | Le porc | The pig | The 			boar | (?) See 			contrast 184 ‘porc’ vs. 185 ‘truie’
184 | est gros | is fat | is big | Metonymic 			shift from measure > consistence
190 | (est) 			sèche | (is) dry 			(feminine) | (is) 			dry | Delete 			morph. feature (feminine)
193 | du sel | some salt | salt | (?) ‘some 			salt’ would be ‘un peu de sel’
194 | du poivre | some 			pepper | pepper | (?) ‘some 			pepper’ would be ‘un peu de poivre’
195 | une 			fueille | one leaf | a leaf | (?) Why a 			numeral
196 | de chou | some 			cabbage | of 			cabbage | Meaning 			is ‘I want a cabbage leaf’
197 | une gerbe | a wreath | a 			sheaf | (?) 			WREATH
198 | de paille | some 			straw | of 			straw | Meaning 			is ‘I want a sheaf of straw’
199 | un sac | a bag | a sack | Meaning 			is ‘I want a sack of oats’; (?) BAG
200 | d’avoine | some oat | of oat | Meaning 			is ‘I want a sack of oat’
201 | de farine | some 			flour | of 			flower | Meaning 			is ‘I want a bag of flour’
203 | (des) 			brassées) | some 			armfuls | armfuls |  
206 | (des) 			pelletées | (some) 			shovels | shovels |  
209 | (des) 			poignées | (some) 			handfuls | handfuls |  
215 | du pain | some 			bread | bread |  
216 | (du) miel | (some) 			honey | honey |  
219 | (de la) 			viande | (some) 			meat | meat |  
221 | (du) 			fromage | (some) 			cheese | cheeese |  
222 | (du) 			‘serac’ | (some) 			‘serac’ | ‘serac’ |  
223 | la moitié | half | the 			half |  
231 | du lait | some milk | milk |  
232 | du 			petit-lait | some whey | whey |  
243 | Il a bu | He drank | He has 			drunken | Past 			participle is focused
244 | (une) 			cuillerée, (des) cuillerées | (a) 			spoonful, (of) spoonfuls | (a) 			spoonful, spoonfuls |  
267 | de nœuds | of knots | knots | Art. 			part.!
273 | On vient | Someone 			comes | One 			comes | (?) Unify 			On-constructions
277 | chasser | to hunt | to 			chase | contextual 			meaning is to 			chase; 			(?) 			HUNT
319 | rien | nothing | anything | (?) ‘It 			does not prove anything’
320 | On défend | One keeps 			from | One 			defends | (?) ‘One 			defends children to play’
337 | vous 			voudriez |   | Vous 			voudriez |  
337 | vous 			voudriez | you would 			like | You 			would like |  
339 | sache pas | know (not 			a bit) | know 			it |  
341 | doucement | slowly | softly | ? SLOWLY
342 | pour 			qu’on n’entende pas | so that 			we don’t hear | so 			that one don’t hear |  
344 | un peu | some | a 			little | ? SOME
344 | Je ne le dis | I say 			that to nobody | I say 			it |  
345 | qu`à eux | than to 			them | only 			to them |  
355 | est 			arrivé | arrived | has 			arrived | Past 			participle is focused
367 | de 			monnaie | of money | money | Partitive 			article!
370 | J’en ai | I do not 			have | I have | “en” 			is an adverbial pronoun: I 			have enough of them
373 | Ayez | You have | Have | Imperatif: 			Have 			pity!
374 | pitié | pity | mercy | (?) PITY 			vs. MERCY
377 | Quelle | What kind 			of | What |  
381 | de metier | the 			profession | profession |  
383 | passée | past | last | (?) No 			difference in French
384 | je me 			suis fait | I made 			myself | I have 			made myself | Past 			participle is focussed
391 | Il m’a 			donné | He gave 			me | He has 			given me | Past 			participle is focused
397 | J’ai 			pris | I took | I have 			taken | Past 			participle is focused
400 | (Cela 			m’a) aidé | (This) 			helped (me) | (This 			has) helped (me) | Past 			participle is focused
401 | à me 			gérir | to cure | to 			cure myself | (?) CURE 			vs. HEAL
405 | (Elles 			sont) guéries | (They 			are) healed | (They 			are) cured | (?) CURE 			vs. HEAL
406 | Il a mal | he has 			pain | He has 			pain |  
424 | Il est 			tombé | He fell | He has 			fallen | Past 			participle is focused
425 | (elle 			est) tombé | (she) 			fell | (she) 			has fallen | Past 			participle is focused
439 | Il est 			droit | He is 			right | He is 			straight |  
461 | des 			plumes | of 			feathers | feathers | Partitive 			article

**Comment by LinguList** [comment]
If any of our concepticon people can take this and modify the glosses according to the suggestions, this would be nice. But please inform me before, so that I can provide some information first.

**Comment by CarolinHu** [comment]
I'll modify the glosses. What else do I need to know about this list?
