### ISSUE TITLE
 Typo in BeijingDaxue-1964-905

### ISSUE THREAD

**Issue by MacyL** [concepticon/concepticon-data#918]
please change 閑淡 to 闲谈, and I would suggest the concept mapping changes to CHAT (WITH SOMEBODY) [2903]

**Comment by LinguList** [comment]
Okay, can you make a PR on this?

**Comment by MacyL** [comment]
sure, I will make a PR on Monday :)

**Comment by chrzyki** [comment]
This is done, thanks.
