### ISSUE TITLE
The mappings of LIFT and RAISE in Chinese concept lists 

### ISSUE THREAD

**Issue by MacyL** [concepticon/concepticon-data#921]
apologize if this issue has been brought up or had been solved before (I found this mapping on concepticon website, version 2.3.0) 
Please see : https://concepticon.clld.org/parameters/501 
I suggest all the concept lists which have "提" or "揭(~盖子) " map to LIFT, and the rest should be changed (if it's already changed, then we can skip that item) 

|Dataset |   Chinese concept |New mapping|
|---------| ------------------|--------------|
|Castro-2015-608-295| 养（养鸡） [chinese]; to raise [english]|RAISE (BRING UP) [2134]|
|Castro-2010-540-412| 举起 [chinese]; to lift (over head) [english]| RAISE [1317]|
|Yang-2011-1014-564|举起 [chinese]|RAISE [1317]|
|Sun-1991-1004-592| 抬 [chinese]; carry on a pole (two people) [english]|unmap|

抬 the original meaning is "multiple people lift something up together", but it also has the meaning of "舉起". Like 抬頭(head raised)挺胸(chest straight) is to stand tall. The movement of 抬 is complex, I would suggest to unmap it, or map it to CARRY (WITH POLE ON SHOULDER) [3438]

**Comment by MacyL** [comment]
The changes have been made in the new PR, please have a look. Thanks.

**Comment by chrzyki** [comment]
What's the status on this? The Casto/Yang/Sun changes have been reverted?

**Comment by LinguList** [comment]
@macyl, has this now been done?

**Comment by MacyL** [comment]
no agreement on what I proposed, and there was no further discussion on this issue. Maybe this is not an urgent issue. Should I close this one?

**Comment by LinguList** [comment]
If you have time to address it, I suggest you make a PR, if not, please modify the milestone to 3.0 ;)

**Comment by MacyL** [comment]
Make it a milestone to 3.0 is a good idea. Thanks for suggesting.
