### ISSUE TITLE
471 UPPER LEG and 800 THIGH

### ISSUE THREAD

**Issue by CarolinHu** [concepticon/concepticon-data#924]
Based on the concept descriptions of those two sets and the fact that UPPER LEG only has two mappings which may be subsumed under THIGH even though their forms are different, I think one could be retired?

**Comment by LinguList** [comment]
I would think so, what do the others think, @Schweikhard, @AnnikaTjuka and @MacyL and @Kristina-Pianykh ?

**Comment by AnnikaTjuka** [comment]
@CarolinHu Thanks for pointing this out! I'm in the process of setting up a list of body parts in Concepticon. I'll put it on my list of possible changes.

**Comment by Kristina-Pianykh** [comment]
I'm pretty sure they are duplicates. It looks like 'upper leg' is not a scientific term but rather just a common name. See also some elaborations [here ](https://www.healthline.com/health/human-body-maps/leg#knee)and [here](https://www.medicinenet.com/script/main/art.asp?articlekey=8456).

**Comment by MacyL** [comment]
> Yes that very much looks like a duplicate to me.

agree.

**Comment by AnnikaTjuka** [comment]
Looking at the mappings, we have 2 lists mapped to UPPER LEG and 49 lists mapped to THIGH. UPPER LEG (471) is the older concept so that THIGH (800) will be retired. 

I'm going to remap the 49 lists with THIGH to UPPER LEG.

@LinguList Is it ok, if I change the CONCEPTICON_GLOSS to UPPER LEG (THIGH) to prevent any further confusion.

**Comment by LinguList** [comment]
But I think it is a good idea.

**Comment by AnnikaTjuka** [comment]
Based on similar PRs (e.g., #923), retiring and renaming of concepts does not seem to involve the retire.json. I'd rename the concept gloss and remap the lists to the refined concept 471 UPPER LEG (THIGH). I'll get to work and will open a PR soonish.
