### ISSUE TITLE
3715 BELLYBUTTON and 1838 NAVEL

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#927]
Only one item (Ombligo [spanish]) is mapped to 3715 BELLYBUTTON. I guess the two concepts are duplicates. If @Schweikhard, @Kristina-Pianykh, @CarolinHu, and @LinguList agree, I'll retire 3715 BELLYBUTTON.

**Comment by Schweikhard** [comment]
I agree.

**Comment by CarolinHu** [comment]
Me too, they very much look like duplicates.

**Comment by Kristina-Pianykh** [comment]
I would definitely retire BELLYBUTTON.
