### ISSUE TITLE
Modality Exclusivity norms for different languages

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#935]
Dutch: https://link.springer.com/article/10.3758/s13428-017-0852-3

Russian: https://link.springer.com/article/10.1007/s10936-017-9548-1

Italian: https://www.journalofcognition.org/articles/10.5334/joc.88/

Chinese: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0211336#sec019

Most of the data sets are less than 1,000 words, so I'll add them with the usual Concepticon workflow.

**Comment by LinguList** [comment]
Very nice!
