### ISSUE TITLE
Goddard-2002-59

### ISSUE THREAD

**Issue by Kristina-Pianykh** [concepticon/concepticon-data#937]
A list of (provisional) semantic primes organized in semantic categories. After the list is added, the notes on Johansson-2020-344 and Johansson-2017-56 should be updated.
[Goddard 2002 page 14.pdf](https://github.com/concepticon/concepticon-data/files/5268214/Goddard.2002.page.14.pdf)

**Comment by AnnikaTjuka** [comment]
@Kristina-Pianykh Are you working on that list? If not, I would prepare it so that we can add it to version 2.5.

**Comment by Kristina-Pianykh** [comment]
No, I’m working on another list now.

**Comment by AnnikaTjuka** [comment]
Ok, great! Then I'll prepare this one.
