### ISSUE TITLE
Making a multilingual concept list for the purpose of data aggregation?

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#943]
The IDS data was translated into some major languages, and we have also already quite a few concept lists that are in different languages, such as Chinese, etc., but we lack a couple of resources for which one could say that we have data in fact. I am thinking here specifically of IDS as a resource that could provide us with quite reliable information on some 5-10 more frequently used languages, which we could then in turn use to enhance our mapping algorithms. 

My proposal would be rather simple: Add a new concept list, which takes major data points from IDS, but makes them concepticon-compatible, just in other languages. Example [polish](https://ids.clld.org/contributions/203): "cousin" is given two entries, namely "kuzyn" and "kuzynka", so we cannot use this directly, since we have no unique gloss for "cousin". So we would merge the two, e.g. writing "kuzyn, kuzynka", as we'd also do in German. The concept list which would show IDS glosses in some 10 more languages which one might expect in questionnaires or linguistic studies, could proceed in this way and one could also make them open, so that people willing could help enhancing them. But the starting point would be a small blogpost (similar to @AnnikaTjuka's list of body parts submitted today), where this new and "specific" kind of concept list is introduced.

Alternatives would be:

- integrate ids data in the mapping process (or generally lexical data)
- use automatic translations in the mapping process

But the idea of having additional hand-curated concept lists with the purpose of eliciting concepts seems to be more useful to me, to be honest.

**Comment by LinguList** [comment]
@AnnikaTjuka, see issue #976 as an example for the procedure that we should use here: who adds new elicitation glosses, presents them IN a blog post.

**Comment by AnnikaTjuka** [comment]
I see. So we could create such lists, e.g., for Chinese, Spanish, etc. with the help of our native speakers.

**Comment by LinguList** [comment]
Yes, luckily, however, we have large lists for Chinese, Spanish,
already, as IDS has been translated and we have linked large Chinese
lists. So the only thing left would be Italian (and @tresoldi told me he
started to look into this).

**Comment by tresoldi** [comment]
So, this would be doing an Italian list, starting from IDS, following the German example in the blog post, correct?

**Comment by LinguList** [comment]
Yes, exactly. But this takes some time (I needed several hours), so I
recommend to only do it in bits in regular intervals...

**Comment by AnnikaTjuka** [comment]
It would also be useful to have more mappings for Dutch if @CarolinHu is interested ;)
