### ISSUE TITLE
SQUEAK 'Action/Process' instead of 'Person/Thing'

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#947]
Even through SQUEAK is marked as belonging to the 'Person/Thing' category, its definition clearly refers to a verb. The lists mapped there confirm it, too.

_Originally posted by @Kristina-Pianykh in https://github.com/concepticon/concepticon-data/pull/945#r498544428_

**Comment by Schweikhard** [comment]
Yes, and both things already mapped to it also refer to verbs:
squeak (as a hinge) [english]
squeak (wheel) (v) [english]; grincer, crier [french]
