### ISSUE TITLE
New concept MALE HORSE

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#948]
Then there are two ways to go about this issue: either to leave "kon'" unmapped and map "loshad" to HORSE or map "kon'" to a new concept set that would be called roughly MALE HORSE (not distinguishing between castrated and uncastrated horses). But maybe we could look into this in a separate issue if we have to review the concepts already mapped to STALLION?

_Originally posted by @Kristina-Pianykh in https://github.com/concepticon/concepticon-data/pull/945#discussion_r498771942_

**Comment by AnnikaTjuka** [comment]
I'm not sure if we should add a new concept for MALE HORSE. There are only two mappings that would be worth considering, but one of them is ambiguous.
- List-2016-180-178 (公馬 [chinese]; the stallion (male horse) [english])
- Grierson-1928-168-80 (Horse (male) [english])

**Comment by LinguList** [comment]
Chinese cases in fact have all the same word as 公馬. If we leave it as this, assuming that a STALLION is the prototypical male horse, we can see if the discussion becomes relevant later.

**Comment by LinguList** [comment]
This means we can also close it for now.
