### ISSUE TITLE
Chinese 薄 mapped to multiple concepts

### ISSUE THREAD

**Issue by AnnikaTjuka** [concepticon/concepticon-data#950]
The Chinese character 薄 is mapped to three concepts that relate to 'thin':

- THIN (OF LEAF AND CLOTH)
- THIN (OF SHAPE OF OBJECT)
- THIN

See overview [here](https://concepticon.clld.org/values).

@MacyL @LinguList Should we unify the mapping or is each case different?

**Comment by LinguList** [comment]
The word refers to "thin" of shape of object, but the English
translation is also important. I can review the cases later.

**Comment by LinguList** [comment]
correction: 薄 should be mapped to "thin of leaf and cloth", the idea is: thin of two-dimensional objects or of objects perceived as two-dimensional. So those items mapped to other cases should be remapped.

**Comment by MacyL** [comment]
According to the definition of THIN, and THIN (OF SHAPE OF OBJECT)
I suggest, when there is not much information in the wordlist : 
THIN = 瘦
THIN (OF SHAPE OF OBJECT)  = 薄

**Comment by LinguList** [comment]
I added the new concept THIN (OF CLOTH AND LEAF) to account specifically for 薄, since it seemed that the word is not used to talk about something that is small along three dimensions (compare a thin pencil vs. a thin leaf). So for consistency, this seems to be easiest...

**Comment by MacyL** [comment]
So the consistency would be : 
THIN = 瘦
THIN (OF CLOTH AND LEAF) = 薄

**Comment by LinguList** [comment]
No, we have a more specific concept set for 瘦: [THIN (SLIM)](https://concepticon.clld.org/parameters/1400)

**Comment by MacyL** [comment]
THIN (SLIM) : Carrying little fat (of people). <----- This is 瘦 I agree full heartily. 
THIN : Being narrow or **carrying a small amount of fat**.  <----- However, This bold font part leads me to propose the conclusion that the THIN = 瘦 statement. 
Is there any guideline that we can follow to map Chinese words to these two Concepticon sets? So that we can avoid the incorrect mapping in the future. 
For example, 
THIN (SLIM) = 瘦
THIN (OF CLOTH AND LEAF) = 薄
THIN = "do not map Chinese word to this concept"
THIN (OF SHAPE OF OBJECT) = "do not map Chinese word to this concept"

**Comment by LinguList** [comment]
Please check the relations of the concepts, @macyl, this is essential. No discussion here, please. In our relations THIN includes THIN (SLIM) and THIN (OF SHAPE OF OBJECT). Then THIN (OF CLOTH AND LEAF) is narrower than THIN (OF SHAPE AND OBJECT). No need to discuss this in more detail, I think it is well-reflected now, only those cases where báo is NOT linked to THIN (OF CLOTH AND LEAF) should be relinked.

**Comment by LinguList** [comment]
Just to explain this, @MacyL: this discussion was made three years ago. I just failed to check that people would adhere to it (including myself) when doiing more lists...

**Comment by LinguList** [comment]
Has this now been taken care of? If not, it would be good to have this done for 2.4

**Comment by AnnikaTjuka** [comment]
I'll take care of it. I'll remap all glosses with 薄 to THIN (OF LEAF AND CLOTH).
This includes 
- [BeijingDaxue-1964-905-703](https://concepticon.clld.org/values/BeijingDaxue-1964-905-703)
- [Castro-2015-608-557](https://concepticon.clld.org/values/Castro-2015-608-557)
- [He-2010-207-19](https://concepticon.clld.org/values/He-2010-207-19)
- [Huang-1992-1820-981](https://concepticon.clld.org/values/Huang-1992-1820-981)
- [List-2016-180-147](https://concepticon.clld.org/values/List-2016-180-147)
- [Liu-2007-201-6](https://concepticon.clld.org/values/Liu-2007-201-6)
- [Sun-1991-1004-814](https://concepticon.clld.org/values/Sun-1991-1004-814)
- [Wang-2004-200-183](https://concepticon.clld.org/values/Wang-2004-200-183)
- [Yang-2011-1014-926](https://concepticon.clld.org/values/Yang-2011-1014-926)
