### ISSUE TITLE
Improvements to Galucio-2015-90

### ISSUE THREAD

**Issue by tresoldi** [concepticon/concepticon-data#955]
We can improve the mapping of [Galucio-2015-90](https://concepticon.clld.org/contributions/Galucio-2015-90), based on work by @jtbirchall. 

- Concepts not linked but existing in Concepticon:

  - GLOWWORM (vagalume) -> FIREFLY 206

- Concepts wrongly mapped:

  - PEACH PALM (PUPUNHA) is mapped to PEACH TREE (but it is PEACH PALM, not in Concepticon)
  - LARGE ANT (TOCANDEIRA) is mapped to ANT, but it is not a general term ("tocandeira" or "tucandeira" are a specific ant species, culturally important in some groups)
  - TIMBÓ LIANA is mapped to LIANA, but it is a different group of plants
  - CARÁ ROOT is mapped to ROOT, but it is not a general term (the closest match would be MANIOC 927)
  - PACU FISH is mapped to FISH, but it is not a general term (it a family)

- A number of concepts do not exist as concept sets, but at least some of them should be included as they are common in wordlists from the Amazonian/South American area and/or common concepts for study language and culture relationships (including borrowings). In order of importance for inclusion (order given by me), they are:

- [ ] BRAZIL NUT, perhaps one of the most important products ([in TuLeD](https://tuled.org/parameters/49))
- [X]   - PEACH PALM, as in the item above ([in TuLeD](https://tuled.org/parameters/249))
- [ ]   - ANATTO, the orange-red condiment and food coloring derived from the achiote tree, an extremely important cultural concept  ([in TuLeD](https://tuled.org/parameters/7))
- [ ]   - TIMBÓ, as in the item above, considering its importance for study of linguistic and cultural relations ([in TuLeD](https://tuled.org/parameters/353))
- [ ]   - GNAT (PIUM), could be added as GNAT, found also in other geographic areas ([in TuLeD](https://tuled.org/parameters/148))
- [ ]   - TUCUMÃ PALM, the *Astrocaryum vulgare*, one of the most important palms of the Amazon ([in TuLeD](https://tuled.org/parameters/364))
- [ ]   - TRAHIRA FISH, fish of the *Erythrinidae* family, found from Costa Rica to Argentina  ([in TuLeD](https://tuled.org/parameters/362))
- [x]   - GENIPA, the *Genipa americana*, an important plant/fruit of the region ([in TuLeD](https://tuled.org/parameters/145))
- [x]   - TINAMOU, a bird found everywhere in Central and South America  ([in TuLeD](https://tuled.org/parameters/354))
- [ ]   - LARGE MANDI FISH, a type of catfish (could probably be added as BAGRE)  ([in TuLeD](https://tuled.org/parameters/196))
- [ ]   - LARGE ANT (TOCANDEIRA)
- [ ] CARÁ ROOT, 
- [X] PACU FISH, as above

**Comment by tresoldi** [comment]
Also pinging  @LanguageStructure

**Comment by tresoldi** [comment]
Correcting above, we have YAM 410, which can be the map for "cará"

**Comment by LanguageStructure** [comment]
Tiago,

vc tem uma lista dos items adicionados?

abraço,

F

**Comment by AnnikaTjuka** [comment]
Regarding the proposed concept GNAT (PIUM) could this be mapped to 95 SANDFLY?

**Comment by LanguageStructure** [comment]
Tiago, regarding the improvements, an article of mine is about to be published. It uses a previous version of TuLeD so that you could use the publication to include some of the items. The actual version of TuLeD has just been accepted by _Language Resources and Evaluations_, so that further relevant SA concepts can be added.

**Comment by LinguList** [comment]
@LanguageStructure, could you please write an email to me and @tresoldi, where you summarize:

1. which articles are about to be published which contain tuled data (or parts of it)
2. when you will receive the proofs
3. in which state the CLDF datasets are?

It would be nice if we could do this quickly then: adding NEW concept lists for you to the concepticon, where we also reference the sources. We can also deal with Forthcoming in the reference, this is not directly a problem. But it would be cool to add specific concept lists here, and to also wrap up all CLDF so we have final versions there that you can put a zenodo DOI on. @tresoldi, glad if you help me on this.

**Comment by LinguList** [comment]
@LanguageStructure, could you please write an email to me and @tresoldi, where you summarize:

1. which articles are about to be published which contain tuled data (or parts of it)
2. when you will receive the proofs
3. in which state the CLDF datasets are?

It would be nice if we could do this quickly then: adding NEW concept lists for you to the concepticon, where we also reference the sources. We can also deal with Forthcoming in the reference, this is not directly a problem. But it would be cool to add specific concept lists here, and to also wrap up all CLDF so we have final versions there that you can put a zenodo DOI on. @tresoldi, glad if you help me on this.

**Comment by LinguList** [comment]
I suggest that we tackle this milestone before releasing 2.4.

**Comment by chrzyki** [comment]
Yes, would be good to have this. Will check tomorrow before release.

**Comment by chrzyki** [comment]
See #989 for some updates with respect to the mappings. We'll keep the majority of the updates (e.g. the new concepts proposed above) for 3.0.

**Comment by AnnikaTjuka** [comment]
I went through the suggestions for new concepts by @tresoldi again and some of them are already implemented. The other concepts that were not added occur in only 1-3 lists. @LinguList Can I close this issue?

**Comment by AnnikaTjuka** [comment]
I opened an issue for one unresolved discussion, but since the other suggestions seem to have been implemented, I'm closing this issue now.
