### ISSUE TITLE
New concept list: Pharao-2020-100

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#975]
This list is important, as it should be released along with a cldf dataset.

I add all info here and ask one of our concepticon team to make a check and submit the list then.

Cohncept list (mapped):

[concepts.txt](https://github.com/concepticon/concepticon-data/files/5429224/concepts.txt)

```
@incollection{Pharao2020,
	title={¿Familia o vecinos? Investigando la relación entre el proto-náhuatl y el proto-corachol [Family or neighbors? Investigating the relation between Proto-Náhuatl and Proto-Corachol]},
	author = {Pharao Hansen, Magnus},
	year={2020},
	booktitle={Lenguas yutoaztecas: historia, estructuras y contacto lingüístico. Homenaje a Karen Dakin},
	editor={Yañez Rosales, Rosa H.},
	publisher={Universidad de Guadalajara},
	address = {Guadelajara},
	chapter = {3},
}
```

Note: 
```
This concept list (based on the [100-item list by Swadesh (1955)](:ref:Swadesh-1955-100) was used in a study on Náhuatl and Corachol.
```

**Comment by CarolinHu** [comment]
It looks like this list has already been added.
https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/PharaoHansen-2020-100.tsv

**Comment by LinguList** [comment]
Thansk! good catch, so the issue can be closedd ;)
