### ISSUE TITLE
Chin-Dialect Survey

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#978]
This dataset has already been lexibankified, just needs to be added to Concepticon:

https://github.com/lexibank/chindialectsurvey/blob/master/etc/concepts.tsv

```
@book{chinds,
	title = {Chin dialect survey},
	author = {Language and Social Development Organization,
	year = {2019},
	address = {Yangon},
	publisher = {LSDO}
}

```

* Muhammad Zakaria helped with concept linking
* Nathan Statezni allowed us to use the data (so also in the contributors list)

ID: LSDO-2019-460

NOTE: 

```
This list was used as a questionnaire for an investigation of Chin dialects, carried out by the Language and Social Development Organization in 2019. Nathan Statezni was so kind to share the original data with us.
```

**Comment by chrzyki** [comment]
I can add this. A couple of questions:

- the list you've linked has a 'break' at about line 54; it looks like there should have been another gloss for `bamboo plant (large)` that is missing, causing the subsequent 7 concepts to have wrong entry in the `AlternativeName` column. This can easily be correct but I can't say for sure that there is/should be a `bamboo plant (large)` gloss
- the list appears to have 462 items, not 460?
- there are a couple of, it seems like, typos in the GLOSS column (to yarwn -> yawn, gost -> ghost, etc.) and superscript `m`s, e.g. `guᵐs` - is it safe to correct those?

**Comment by LinguList** [comment]
Okay, for the questions, I'd suggest that you consult the original data first (which is what I'd have to do as well now): there's an excel sheet that provides the information. If you are in doubt, let me know and I'll check again. Maybe, we already had an error in this stage, in which case we should be careful...

**Comment by chrzyki** [comment]
It seems to me that column `462E` (sheet: data) in https://github.com/lexibank/chindialectsurvey/blob/master/raw/Chin%20wordlist%20helps-with%20Uppu.ods most closely corresponds to the structure of the mapping. However, I'm not familiar with the data set and its origins so I'd appreciate if you could have another look/confirm this. Thanks!

**Comment by LinguList** [comment]
Yes, we have column E providing the number, and column F providing the gloss!
